### ISSUE TITLE
[core] NPE when resolving model properties

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1068]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Configure a Maven project with no binaries (a parent pom for example)
2. Attempt a release

### Expected Behaviour

Successful release.

### Actual Behaviour

NPE because `project.java.version` is null

```
java.lang.IllegalArgumentException: Argument 'version' must not be blank
	at org.jreleaser.util.StringUtils.requireNonBlank(StringUtils.java:526)
	at org.jreleaser.version.SemanticVersion.of(SemanticVersion.java:180)
	at org.jreleaser.model.internal.release.BaseReleaser.props(BaseReleaser.java:720)
	at org.jreleaser.model.internal.release.BaseReleaser.getResolvedTagName(BaseReleaser.java:189)
	at org.jreleaser.model.internal.validation.release.BaseReleaserValidator.validateGitService(BaseReleaserValidator.java:211)
	at org.jreleaser.model.internal.validation.release.GithubReleaserValidator.validateGithub(GithubReleaserValidator.java:38)
	at org.jreleaser.model.internal.validation.release.ReleaseValidator.validateRelease(ReleaseValidator.java:43)
	at org.jreleaser.model.internal.JReleaserModelValidator.validateModel(JReleaserModelValidator.java:70)
	at org.jreleaser.model.internal.JReleaserModelValidator.validate(JReleaserModelValidator.java:55)
	at org.jreleaser.model.internal.JReleaserContext.validateModel(JReleaserContext.java:454)
	at org.jreleaser.engine.context.ModelValidator.validate(ModelValidator.java:43)
	at org.jreleaser.cli.Config.doExecute(Config.java:54)
	at org.jreleaser.cli.AbstractModelCommand.execute(AbstractModelCommand.java:90)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:36)
	at org.jreleaser.cli.AbstractModelCommand.call(AbstractModelCommand.java:53)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:29)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.jreleaser.cli.Main.execute(Main.java:72)
	at org.jreleaser.cli.Main.run(Main.java:57)
	at org.jreleaser.cli.Main.main(Main.java:48)
```

### Environment Information

- **Operating System**: N/A
- **JReleaser Version:** 1.3.1
- **JDK Version:** N/A

**Comment by aalmiray** [comment]
Released in v1.4.0 -> https://github.com/jreleaser/jreleaser/releases/tag/v1.4.0
