### ISSUE TITLE
NPE when misconfiguring Scoop

### ISSUE THREAD

**Issue by maciejwalkowiak** [jreleaser/jreleaser#1081]
When I misconfigured Scoop distribution in Maven flavour of JReleaser like this:

```xml
<scoop>
    <active>ALWAYS</active>
    <owner>maciejwalkowiak</owner>
    <name>scoop-mypackage</name>
</scoop>
```

(note that `owner` and `name` are not inside the `bucket` key as they should be)

Instead of getting reasonable error message I am getting:

```
[ERROR] Failed to execute goal org.jreleaser:jreleaser-maven-plugin:1.3.1:full-release (default-cli) on project just: Execution default-cli of goal org.jreleaser:jreleaser-maven-plugin:1.3.1:full-release failed: JReleaser has not been properly configured.: Cannot invoke "org.jreleaser.model.internal.distributions.Distribution.asMap(boolean)" because "d" is null -> [Help 1]
```

Stacktrace from the `trace.log`:

```
[ERROR] == JReleaser ==
[ERROR] java.lang.NullPointerException
java.lang.NullPointerException: Cannot invoke "org.jreleaser.model.internal.distributions.Distribution.asMap(boolean)" because "d" is null
	at org.jreleaser.model.internal.JReleaserModel.lambda$asMap$3(JReleaserModel.java:429)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.jreleaser.model.internal.JReleaserModel.asMap(JReleaserModel.java:430)
	at org.jreleaser.engine.context.ModelValidator.validate(ModelValidator.java:46)
	at org.jreleaser.workflow.WorkflowImpl.<init>(WorkflowImpl.java:44)
	at org.jreleaser.workflow.Workflows.fullRelease(Workflows.java:132)
	at org.jreleaser.maven.plugin.JReleaserFullReleaseMojo.execute(JReleaserFullReleaseMojo.java:148)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:294)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:53)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:152)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:76)
```

### Environment Information

- **Operating System**: MacOS
- **JReleaser Version:** 1.3.1
- **JDK Version:** 17.0.5

**Comment by aalmiray** [comment]
I've seen this before. Maven fails to create an instance of a managed object that's supposed to be the value of a Map entry. When there's no match for a given property then Maven assigns a `null` to the entry silently. Later in the build we get this error because of the `null`. I've yet to find out why this is the case and there's no early failure.

**Comment by aalmiray** [comment]
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">I think <a href="https://t.co/BxaUufzOVF">https://t.co/BxaUufzOVF</a> is responsible for that logic. <a href="https://twitter.com/mcculls?ref_src=twsrc%5Etfw">@mcculls</a> is currently the one with indepth knowledge on this piece of code.</p>&mdash; Robert Scholte (@rfscholte) <a href="https://twitter.com/rfscholte/status/1598603411749933057?ref_src=twsrc%5Etfw">December 2, 2022</a></blockquote> 

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">I believe this was originally done to workaround a bug in the shade plugin (MSHADE-168) - it should be safe to change that behaviour, will see I can include it in the next milestone</p>&mdash; Stuart McCulloch (@mcculls) <a href="https://twitter.com/mcculls/status/1598607929648611328?ref_src=twsrc%5Etfw">December 2, 2022</a></blockquote>
