### ISSUE TITLE
[assemble] IOException when assembling a javaArchive without custom templates

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1108]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Configure a `javaArchive` assembler
```
  javaArchive:
    app:
      active: ALWAYS
      fileSets:
        - input: '.'
          includes:
            - 'LICENSE'
      mainJar:
        path: target/{{distributionName}}-{{projectVersion}}.jar
```
2. Execute the `assemble` command

### Expected Behaviour

Successful assembly.

### Actual Behaviour

An exception occurs because of missing templates

### Environment Information

- **Operating System**: N/A
- **JReleaser Version:** 1.3.1
- **JDK Version:** N/A

```
org.jreleaser.model.JReleaserException: Unexpected error reading templates from /Users/aalmiray/dev/github/jreleaser-smoke-test/src/jreleaser/assemblers/app/java-archive
	at org.jreleaser.templates.TemplateUtils.resolveTemplates(TemplateUtils.java:121)
	at org.jreleaser.assemblers.JavaArchiveAssemblerProcessor.doAssemble(JavaArchiveAssemblerProcessor.java:79)
	at org.jreleaser.assemblers.AbstractAssemblerProcessor.assemble(AbstractAssemblerProcessor.java:82)
	at org.jreleaser.assemblers.JavaArchiveAssemblerProcessor.assemble(JavaArchiveAssemblerProcessor.java:50)
	at org.jreleaser.engine.assemble.DistributionAssembler.assemble(DistributionAssembler.java:62)
	at org.jreleaser.engine.assemble.Assemblers.assemble(Assemblers.java:110)
	at org.jreleaser.engine.assemble.Assemblers.assemble(Assemblers.java:97)
	at org.jreleaser.workflow.AssembleWorkflowItem.doInvoke(AssembleWorkflowItem.java:35)
	at org.jreleaser.workflow.AbstractWorkflowItem.lambda$invoke$0(AbstractWorkflowItem.java:43)
	at org.jreleaser.engine.hooks.CommandHookExecutor.execute(CommandHookExecutor.java:52)
	at org.jreleaser.workflow.AbstractWorkflowItem.invoke(AbstractWorkflowItem.java:43)
	at org.jreleaser.workflow.WorkflowImpl.doExecute(WorkflowImpl.java:111)
	at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:51)
	at org.jreleaser.cli.Assemble.doExecute(Assemble.java:88)
	at org.jreleaser.cli.AbstractModelCommand.execute(AbstractModelCommand.java:91)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:37)
	at org.jreleaser.cli.AbstractModelCommand.call(AbstractModelCommand.java:53)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:29)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.jreleaser.cli.Main.execute(Main.java:73)
	at org.jreleaser.cli.Main.run(Main.java:58)
	at org.jreleaser.cli.Main.main(Main.java:49)
Caused by: java.nio.file.NoSuchFileException: /Users/aalmiray/dev/github/jreleaser-smoke-test/src/jreleaser/assemblers/app/java-archive
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1764)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2717)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2797)
	at org.jreleaser.templates.TemplateUtils.resolveTemplates(TemplateUtils.java:112)
	... 28 more
```

**Comment by aalmiray** [comment]
Released in v1.4.0 -> https://github.com/jreleaser/jreleaser/releases/tag/v1.4.0
