### ISSUE TITLE
[deploy] Error when querying Gitlab packages using dry-run mode

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1109]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Configure a Gitlab maven deployer
```
maven:
  deploy:
    gitlab:
      acme:
        active: ALWAYS
        url: https://gitlab.com/api/v4/projects/{{projectIdentifier}}/packages/maven
        projectIdentifier: 12345678
        stagingRepositories:
          - target/staging-deploy
```
3. Run the `deploy` command with `--dry-run` enabled

### Expected Behaviour

No errors

### Actual Behaviour

An error occurs when listing remote packages

### Environment Information

- **Operating System**: N/A
- **JReleaser Version:** 1.3.1
- **JDK Version:** N/A

```
org.jreleaser.sdk.commons.RestAPIException
	at org.jreleaser.sdk.commons.ClientUtils.lambda$builder$1(ClientUtils.java:110)
	at feign.ResponseHandler.decodeError(ResponseHandler.java:136)
	at feign.ResponseHandler.handleResponse(ResponseHandler.java:70)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:116)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:72)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:98)
	at com.sun.proxy.$Proxy20.listPackages0(Unknown Source)
	at org.jreleaser.sdk.gitlab.Gitlab.listPackages(Gitlab.java:559)
	at org.jreleaser.sdk.gitlab.GitlabMavenDeployer.deploy(GitlabMavenDeployer.java:82)
	at org.jreleaser.engine.deploy.maven.ProjectMavenDeployer.deploy(ProjectMavenDeployer.java:55)
	at org.jreleaser.engine.deploy.maven.MavenDeployers.deploy(MavenDeployers.java:124)
	at org.jreleaser.engine.deploy.maven.MavenDeployers.deploy(MavenDeployers.java:111)
	at org.jreleaser.workflow.DeployWorkflowItem.doInvoke(DeployWorkflowItem.java:35)
	at org.jreleaser.workflow.AbstractWorkflowItem.lambda$invoke$0(AbstractWorkflowItem.java:43)
	at org.jreleaser.engine.hooks.CommandHookExecutor.execute(CommandHookExecutor.java:52)
	at org.jreleaser.workflow.AbstractWorkflowItem.invoke(AbstractWorkflowItem.java:43)
	at org.jreleaser.workflow.WorkflowImpl.doExecute(WorkflowImpl.java:111)
	at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:51)
	at org.jreleaser.cli.Deploy.doExecute(Deploy.java:93)
	at org.jreleaser.cli.AbstractModelCommand.execute(AbstractModelCommand.java:91)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:37)
	at org.jreleaser.cli.AbstractModelCommand.call(AbstractModelCommand.java:53)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:29)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.jreleaser.cli.Main.execute(Main.java:73)
	at org.jreleaser.cli.Main.run(Main.java:58)
	at org.jreleaser.cli.Main.main(Main.java:49)
```

**Comment by aalmiray** [comment]
Released in v1.4.0 -> https://github.com/jreleaser/jreleaser/releases/tag/v1.4.0
