### ISSUE TITLE
[upload] NPE when invoking SFTP uploader in dry-run mode

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1110]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. configure an SFTP uploader
```
upload:
  sftp:
    u8:
      active: ALWAYS
      host: uploads.acme.com
      path: '/uploads/{{projectName}}/{{tagName}}/{{artifactFile}}'
      downloadUrl: 'https://download.acme.com/{{projectName}}/{{tagName}}/{{artifactFile}}'
```
2. Execute `upload` command with `--dry-run`

### Expected Behaviour

No errors.

### Actual Behaviour

NPE is thrown

### Environment Information

- **Operating System**: N/A
- **JReleaser Version:** 1.3.1
- **JDK Version:** N/A

```
java.lang.NullPointerException
	at org.jreleaser.sdk.ssh.SshUtils.close(SshUtils.java:174)
	at org.jreleaser.sdk.ssh.SftpArtifactUploader.upload(SftpArtifactUploader.java:95)
	at org.jreleaser.engine.upload.ProjectUploader.upload(ProjectUploader.java:56)
	at org.jreleaser.engine.upload.Uploaders.upload(Uploaders.java:123)
	at org.jreleaser.engine.upload.Uploaders.lambda$upload$0(Uploaders.java:83)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at org.jreleaser.engine.upload.Uploaders.upload(Uploaders.java:83)
	at org.jreleaser.workflow.UploadWorkflowItem.doInvoke(UploadWorkflowItem.java:35)
	at org.jreleaser.workflow.AbstractWorkflowItem.lambda$invoke$0(AbstractWorkflowItem.java:43)
	at org.jreleaser.engine.hooks.CommandHookExecutor.execute(CommandHookExecutor.java:52)
	at org.jreleaser.workflow.AbstractWorkflowItem.invoke(AbstractWorkflowItem.java:43)
	at org.jreleaser.workflow.WorkflowImpl.doExecute(WorkflowImpl.java:111)
	at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:51)
	at org.jreleaser.cli.Upload.doExecute(Upload.java:108)
	at org.jreleaser.cli.AbstractModelCommand.execute(AbstractModelCommand.java:91)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:37)
	at org.jreleaser.cli.AbstractModelCommand.call(AbstractModelCommand.java:53)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:29)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.jreleaser.cli.Main.execute(Main.java:73)
	at org.jreleaser.cli.Main.run(Main.java:58)
	at org.jreleaser.cli.Main.main(Main.java:49)
```

**Comment by aalmiray** [comment]
Released in v1.4.0 -> https://github.com/jreleaser/jreleaser/releases/tag/v1.4.0
