### ISSUE TITLE
[announce] Discord webhook does not work in 1.4.0

### ISSUE THREAD

**Issue by crschnick** [jreleaser/jreleaser#1133]
In 1.4.0, the discord webhook is completely broken:
- The old deprecated configuration does no longer work:

        announce {
            discord {
                active = 'RELEASE'
                webhook = proj.hasProperty("XPIPE_DISCORD_WEBHOOK") ? proj.property("XPIPE_DISCORD_WEBHOOK") : System.getenv("XPIPE_DISCORD_WEBHOOK")
                messageTemplate = 'misc/discord.tpl'
            }
        }
This configuration works for me in 1.3.1, but fails in 1.4.0:

        announce.discord is deprecated since 1.4.0 and will be removed in 2.0.0. Use announce.webhooks instead
        announce.discord is deprecated since 1.4.0 and will be removed in 2.0.0. Use announce.webhooks instead
        
        > Task :dist:jreleaserAnnounce FAILED
        [INFO]  JReleaser 1.4.0
        [INFO]    - basedir set to C:\Projects\xpipe\xpipe\dist
        [INFO]    - outputdir set to C:\Projects\xpipe\xpipe\dist\build\jreleaser
        [INFO]  git-root-search set to true
        [WARN]  Auto configure detected 'xpipe' as repository name but project has 'xpipe-app' configured
        [INFO]  Loading variables from C:\Users\Christopher Schnick\.jreleaser\config.properties
        [WARN]  Variables source C:\Users\Christopher Schnick\.jreleaser\config.properties does not exist
        [INFO]  Validating configuration
        [INFO]  Strict mode set to false
        [INFO]  Project version set to 0.0.4.7
        [INFO]  Release is not snapshot
        [INFO]  Timestamp is 2023-01-01T16:56:20.4513505+01:00
        [INFO]  HEAD is at 0746d76
        [INFO]  Platform is windows-x86_64
        [INFO]  dry-run set to false
        [INFO]  Generating changelog
        [WARN]  Cannot parse version 'release'
        [WARN]  Cannot parse version 'v0.0.1'
        [WARN]  Cannot parse version 'v1.0.0'
        [INFO]  Storing changelog: build\jreleaser\release\CHANGELOG.md
        [INFO]  Announcing release
        [INFO]    [webhook.discord] {"content":"­ƒÜÇ X-Pipe 0.0.4.7 has been released\r\n\r\nIf you have already installed X-Pipe and have updates enabled,\r\nthis update 
        will eventually be automatically installed when launching it the next time.\r\n\r\nYou can get the standalone version here: https://github.com/xpipe-io/xpipe-app/r
        eleases/tag/0.0.4.7"}
        [INFO]  Writing output properties to build\jreleaser\output.properties
        [ERROR] JReleaser failed after 0.126 s
        
        FAILURE: Build failed with an exception.
        
        * What went wrong:
        Execution failed for task ':dist:jreleaserAnnounce'.
        > Cannot invoke "java.lang.Integer.intValue()" because the return value of "org.jreleaser.model.internal.announce.WebhookAnnouncer.getConnectTimeout()" is null    
        
        * Try:
        > Run with --info or --debug option to get more log output.
        > Run with --scan to get full insights.
        
        * Exception is:
        org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':dist:jreleaserAnnounce'.
                at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:142)
                at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
                at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:140)
                at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:128)
                at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
                at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
                at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
                at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
                at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:57)
                at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
                at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
                at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
                at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
                at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
                at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
                at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
                at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
                at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
                at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
                at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
                at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
                at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
                at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:69)
                at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:322)
                at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:309)
                at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:302)
                at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:288)
                at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:462)
                at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:379)
                at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
                at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
        Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "org.jreleaser.model.internal.announce.WebhookA
        nnouncer.getConnectTimeout()" is null
                at org.jreleaser.sdk.webhooks.WebhooksAnnouncer.announce(WebhooksAnnouncer.java:123)
                at org.jreleaser.sdk.discord.DiscordAnnouncer.announce(DiscordAnnouncer.java:58)
                at org.jreleaser.engine.announce.Announcers.announce(Announcers.java:103)
                at org.jreleaser.engine.announce.Announcers.announce(Announcers.java:90)
                at org.jreleaser.workflow.AnnounceWorkflowItem.doInvoke(AnnounceWorkflowItem.java:39)
                at org.jreleaser.workflow.AbstractWorkflowItem.lambda$invoke$0(AbstractWorkflowItem.java:43)
                at org.jreleaser.engine.hooks.CommandHookExecutor.execute(CommandHookExecutor.java:52)
                at org.jreleaser.workflow.AbstractWorkflowItem.invoke(AbstractWorkflowItem.java:43)
                at org.jreleaser.workflow.WorkflowImpl.doExecute(WorkflowImpl.java:111)
                at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:51)
                at org.jreleaser.gradle.plugin.tasks.JReleaserAnnounceTask.performAction(JReleaserAnnounceTask.groovy:72)
                at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
                at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
                at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
                at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
                at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
                at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:236)
                at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
                at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
                at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
                at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
                at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
                at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
                at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
                at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
                at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:221)
                at org.gradle.api.internal.tasks.execution.TaskExecution.executeActions(TaskExecution.java:204)
                at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:187)
                at org.gradle.api.internal.tasks.execution.TaskExecution.execute(TaskExecution.java:165)
                at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:89)
                at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:40)
                at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:53)
                at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:50)
                at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
                at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
                at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
                at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
                at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
                at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
                at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
                at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
                at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:50)
                at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:40)
                at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:68)
                at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:38)
                at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:41)
                at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:74)
                at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55)
                at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
                at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:29)
                at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.executeDelegateBroadcastingChanges(CaptureStateAfterExecutionStep.java:124)
                at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:80)
                at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:58)
                at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
                at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:36)
                at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:181)
                at org.gradle.internal.execution.steps.BuildCacheStep.lambda$execute$1(BuildCacheStep.java:71)
                at org.gradle.internal.Either$Right.fold(Either.java:175)
                at org.gradle.internal.execution.caching.CachingState.fold(CachingState.java:59)
                at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:69)
                at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:47)
                at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:36)
                at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:25)
                at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:36)
                at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:22)
                at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:110)
                at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$2(SkipUpToDateStep.java:56)
                at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:56)
                at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
                at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:73)
                at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:44)
                at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
                at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
                at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:89)
                at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:50)
                at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:102)
                at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:57)
                at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:76)
                at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:50)
                at org.gradle.internal.execution.steps.SkipEmptyWorkStep.executeWithNoEmptySources(SkipEmptyWorkStep.java:254)
                at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:91)
                at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:56)
                at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:32)
                at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:21)
                at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
                at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:43)
                at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:31)
                at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:40)
                at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:281)
                at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:40)
                at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:30)
                at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:37)
                at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:27)
                at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:44)
                at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:33)
                at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:76)
                at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:139)
                at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:128)
                at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
                at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
                at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
                at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
                at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:57)
                at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
                at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
                at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
                at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:288)
                at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:462)
                at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:379)
                at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
                at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)

- The example configuration shown in the documentation for the new discord webhooks fails at compilation as the option `structuredMessage` is unrecognized.
- Even if that option is removed, I get the following error with this configuration:

        announce {
            webhooks {
                discord {
                    active = 'RELEASE'
                    webhook = proj.hasProperty("XPIPE_DISCORD_WEBHOOK") ? proj.property("XPIPE_DISCORD_WEBHOOK") : System.getenv(
                            "XPIPE_DISCORD_WEBHOOK")
                    messageTemplate = 'misc/discord.tpl'
                }
            }
        }

        > Task :dist:jreleaserAnnounce
        [INFO]  JReleaser 1.4.0
        [INFO]    - basedir set to C:\Projects\xpipe\xpipe\dist
        [INFO]    - outputdir set to C:\Projects\xpipe\xpipe\dist\build\jreleaser
        [INFO]  git-root-search set to true
        [WARN]  Auto configure detected 'xpipe' as repository name but project has 'xpipe-app' configured
        [INFO]  Loading variables from C:\Users\Christopher Schnick\.jreleaser\config.properties
        [WARN]    [webhook.discord] Webhook replied with: 400 reason: Bad Request,{"code": 50109, "message": "The request body contains invalid JSON."}
        [INFO]  Writing output properties to build\jreleaser\output.properties
        [INFO]  JReleaser succeeded after 0.824 s

### Environment Information

- **Operating System**: Windows 10
- **JReleaser Version:** 1.4.0 / Gradle 7.6
- **JDK Version:** 19

**Comment by aalmiray** [comment]
Could you paste the announce section after invoking `./gradlew jreleaserConfig`?

**Comment by crschnick** [comment]
When using legacy configuration:
    
    announce:
        enabled: true
        active: always
        discord:
            enabled: true
            active: release
            connectTimeout: 20
            readTimeout: 60
            webhook: ************
            messageTemplate: C:\Projects\xpipe\xpipe\dist\misc\discord.tpl

When using webhook configuration:

    announce:
        enabled: true
        active: always
        webhooks:
            discord:
                enabled: true
                active: release
                connectTimeout: 20
                readTimeout: 60
                webhook: ************
                messageTemplate: C:\Projects\xpipe\xpipe\dist\misc\discord.tpl
                structuredMessage: false

**Comment by aalmiray** [comment]
Thanks. I can see that the Gradle DSL is indeed missing the `structureMessage` property. However, what I find odd is the NPE when converting an integer value given that the output of config does show a value for `connectionTimeout`. Will dig deeper.

**Comment by crschnick** [comment]
Does this commit also fix the third issue? The bad request:

    [WARN]    [webhook.discord] Webhook replied with: 400 reason: Bad Request,{"code": 50109, "message": "The request body contains invalid JSON."}

**Comment by aalmiray** [comment]
It should as the payload must be a valid structured JSON message after this update.

**Comment by aalmiray** [comment]
Released in v1.5.0 -> https://github.com/jreleaser/jreleaser/releases/tag/v1.5.0
