### ISSUE TITLE
Docker login fails

### ISSUE THREAD

**Issue by jruaux** [jreleaser/jreleaser#1168]
- Steps to reproduce provided

Trying to perform `full-release` on project 
Fails at the docker login phase: https://github.com/redis-developer/riot/actions/runs/3927497273

```
[INFO]      [docker] publishing riot-db distribution
...
[DEBUG]     [docker] login into DEFAULT
[ERROR]     [docker] WARNING! Using --password via the CLI is insecure. Use --password-stdin.
[ERROR]     [docker] Error response from daemon: Get "https://registry-1.docker.io/v2/": unauthorized: incorrect username or password
```

Using JReleaser 1.3.1 it works fine:
```
[INFO]      [docker] publishing riot-db distribution
...
[DEBUG]     [docker] login into DEFAULT
[INFO]      [docker] Login Succeeded
[ERROR]     [docker] WARNING! Using --password via the CLI is insecure. Use --password-stdin.
[INFO]      [docker]  - fieldengineering/riot-db:latest
```

- Stacktrace

```
[ERROR]     [docker] WARNING! Using --password via the CLI is insecure. Use --password-stdin.
[ERROR]     [docker] Error response from daemon: Get "https://registry-1.docker.io/v2/": unauthorized: incorrect username or password
[INFO]  Writing output properties to out/jreleaser/output.properties
[ERROR] JReleaser failed after 42.937 s
jreleaser.shadow.org.jreleaser.model.JReleaserException: Unexpected error
	at jreleaser.shadow.org.jreleaser.engine.distribution.Distributions.processPackager(Distributions.java:145)
	at jreleaser.shadow.org.jreleaser.engine.distribution.Distributions.processDistribution(Distributions.java:111)
	at jreleaser.shadow.org.jreleaser.engine.distribution.Distributions.process(Distributions.java:95)
	at jreleaser.shadow.org.jreleaser.workflow.PublishWorkflowItem.doInvoke(PublishWorkflowItem.java:37)
	at jreleaser.shadow.org.jreleaser.workflow.AbstractWorkflowItem.lambda$invoke$0(AbstractWorkflowItem.java:43)
	at jreleaser.shadow.org.jreleaser.engine.hooks.CommandHookExecutor.execute(CommandHookExecutor.java:52)
	at jreleaser.shadow.org.jreleaser.workflow.AbstractWorkflowItem.invoke(AbstractWorkflowItem.java:43)
	at jreleaser.shadow.org.jreleaser.workflow.WorkflowImpl.doExecute(WorkflowImpl.java:111)
	at jreleaser.shadow.org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:51)
	at jreleaser.shadow.org.jreleaser.cli.FullRelease.doExecute(FullRelease.java:180)
	at jreleaser.shadow.org.jreleaser.cli.AbstractModelCommand.execute(AbstractModelCommand.java:92)
	at jreleaser.shadow.org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:37)
	at jreleaser.shadow.org.jreleaser.cli.AbstractModelCommand.call(AbstractModelCommand.java:53)
	at jreleaser.shadow.org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:29)
	at jreleaser.shadow.picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at jreleaser.shadow.picocli.CommandLine.access$1500(CommandLine.java:148)
	at jreleaser.shadow.picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at jreleaser.shadow.picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at jreleaser.shadow.picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at jreleaser.shadow.picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at jreleaser.shadow.picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at jreleaser.shadow.picocli.CommandLine.execute(CommandLine.java:2170)
	at jreleaser.shadow.org.jreleaser.cli.Main.execute(Main.java:73)
	at jreleaser.shadow.org.jreleaser.cli.Main.run(Main.java:69)
	at org.jreleaser.tool.JReleaser.main(JReleaser.java:47)
Caused by: jreleaser.shadow.org.jreleaser.model.spi.packagers.PackagerProcessingException: Unexpected error
	at jreleaser.shadow.org.jreleaser.packagers.AbstractPackagerProcessor.executeCommandWithInput(AbstractPackagerProcessor.java:266)
	at jreleaser.shadow.org.jreleaser.packagers.DockerPackagerProcessor.login(DockerPackagerProcessor.java:438)
	at jreleaser.shadow.org.jreleaser.packagers.DockerPackagerProcessor.publishDocker(DockerPackagerProcessor.java:370)
	at jreleaser.shadow.org.jreleaser.packagers.DockerPackagerProcessor.doPublishDistribution(DockerPackagerProcessor.java:361)
	at jreleaser.shadow.org.jreleaser.packagers.AbstractPackagerProcessor.publishDistribution(AbstractPackagerProcessor.java:183)
	at jreleaser.shadow.org.jreleaser.packagers.DockerPackagerProcessor.publishDistribution(DockerPackagerProcessor.java:343)
	at jreleaser.shadow.org.jreleaser.engine.distribution.DistributionProcessor.publishDistribution(DistributionProcessor.java:141)
	at jreleaser.shadow.org.jreleaser.engine.distribution.Distributions.processPackager(Distributions.java:140)
	... 24 more
Caused by: jreleaser.shadow.org.jreleaser.sdk.command.CommandException: Command execution error. exitValue = 1
	at jreleaser.shadow.org.jreleaser.packagers.AbstractPackagerProcessor.executeCommandWithInput(AbstractPackagerProcessor.java:263)
	... 31 more
```

- Example that reproduces the problem

See early-access action execution at https://github.com/redis-developer/riot/actions/runs/3927497273
for project https://github.com/redis-developer/riot

Please paste stacktraces from `[out|build|target]/jreleaser/trace.log`.
[trace.log](https://github.com/jreleaser/jreleaser/files/10423310/trace.log)

**Comment by aalmiray** [comment]
I see the following in the resolved configuration: 

```

    docker:
        enabled: true
        active: always
        useLocalArtifact: true
        imageNames:
            fieldengineering/{{distributionName}}:latest
            fieldengineering/{{distributionName}}:{{projectVersion}}
        labels:
            org.opencontainers.image.title: {{distributionName}}
        buildx:
            enabled: true
            platforms:
                linux/amd64
                linux/arm64
        commitAuthor:
            name: jreleaserbot
            email: jreleaser@kordamp.org
        repository:
            enabled: false
            active: never
            owner: redis-developer
            name: docker
            tagName: v{{projectVersion}}
            branch: HEAD
            username: redis-developer
            token: ************
            versionedSubfolders: false
        continueOnError: false
        registries:
            serverName: DEFAULT
            repositoryName: fieldengineering
            password: **unset**
```

`buildx` is enabled now. That's a 1.4.0 feature. If you did not explicitly enable it then that's a bug, and might be the cause of the problem. Will continue investigating.

**Comment by jruaux** [comment]
Yes I did enable `buildx`. I thought that could be the issue initially so I tried without it with the same result.

**Comment by aalmiray** [comment]
I see. I suppose credentials were left as they were before. IIRC there was an explicit change to the login procedure by that’s in the latest `early-access` and not in `1.4.0`.

**Comment by jruaux** [comment]
I think I tried with 1.4.0 and it failed but I'll try again to make sure

**Comment by jruaux** [comment]
I tried with 1.4.0 and got the same error:
```
[DEBUG]     [docker] login into DEFAULT
[ERROR]     [docker] WARNING! Using --password via the CLI is insecure. Use --password-stdin.
[ERROR]     [docker] Error response from daemon: Get "https://registry-1.docker.io/v2/": unauthorized: incorrect username or password
[INFO]  Writing output properties to out/jreleaser/output.properties
[ERROR] JReleaser failed after 01:54 m
org.jreleaser.model.JReleaserException: Unexpected error
	at org.jreleaser.engine.distribution.Distributions.processPackager(Distributions.java:145)
	at org.jreleaser.engine.distribution.Distributions.processDistribution(Distributions.java:111)
	at org.jreleaser.engine.distribution.Distributions.process(Distributions.java:95)
	at org.jreleaser.workflow.PublishWorkflowItem.doInvoke(PublishWorkflowItem.java:37)
	at org.jreleaser.workflow.AbstractWorkflowItem.lambda$invoke$0(AbstractWorkflowItem.java:43)
	at org.jreleaser.engine.hooks.CommandHookExecutor.execute(CommandHookExecutor.java:52)
	at org.jreleaser.workflow.AbstractWorkflowItem.invoke(AbstractWorkflowItem.java:43)
	at org.jreleaser.workflow.WorkflowImpl.doExecute(WorkflowImpl.java:111)
	at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:51)
	at org.jreleaser.cli.FullRelease.doExecute(FullRelease.java:180)
	at org.jreleaser.cli.AbstractModelCommand.execute(AbstractModelCommand.java:92)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:37)
	at org.jreleaser.cli.AbstractModelCommand.call(AbstractModelCommand.java:53)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:29)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.jreleaser.cli.Main.execute(Main.java:73)
	at org.jreleaser.cli.Main.run(Main.java:58)
	at org.jreleaser.cli.Main.main(Main.java:49)
Caused by: org.jreleaser.model.spi.packagers.PackagerProcessingException: Unexpected error
	at org.jreleaser.packagers.AbstractPackagerProcessor.executeCommandWithInput(AbstractPackagerProcessor.java:266)
	at org.jreleaser.packagers.DockerPackagerProcessor.login(DockerPackagerProcessor.java:438)
	at org.jreleaser.packagers.DockerPackagerProcessor.publishDocker(DockerPackagerProcessor.java:370)
	at org.jreleaser.packagers.DockerPackagerProcessor.doPublishDistribution(DockerPackagerProcessor.java:361)
	at org.jreleaser.packagers.AbstractPackagerProcessor.publishDistribution(AbstractPackagerProcessor.java:183)
	at org.jreleaser.packagers.DockerPackagerProcessor.publishDistribution(DockerPackagerProcessor.java:343)
	at org.jreleaser.engine.distribution.DistributionProcessor.publishDistribution(DistributionProcessor.java:141)
	at org.jreleaser.engine.distribution.Distributions.processPackager(Distributions.java:140)
	... 24 more
Caused by: org.jreleaser.sdk.command.CommandException: Command execution error. exitValue = 1
	at org.jreleaser.packagers.AbstractPackagerProcessor.executeCommandWithInput(AbstractPackagerProcessor.java:263)
	... 31 more
```

[trace.log](https://github.com/jreleaser/jreleaser/files/10431611/trace.log)

**Comment by jruaux** [comment]
Here is the trace for a successful run with JReleaser 1.3.1 and the `buildx` section commented out
[trace.log](https://github.com/jreleaser/jreleaser/files/10431641/trace.log)

**Comment by aalmiray** [comment]
FWIW `1.4.0-SNAPSHOT` and `1.5.0-SNAPHOT` are working correctly for JReleaser's own Docker images https://hub.docker.com/r/jreleaser/jreleaser-slim/tags

There's something odd going on here.

**Comment by jruaux** [comment]
I was able to get past this by moving the `docker` section under each section. Now the first distribution works but it fails at the 2nd distribution:

```
[INFO]      [docker] Login Succeeded
[ERROR]     [docker] WARNING! Using --password via the CLI is insecure. Use --password-stdin.
[ERROR]     [docker] WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
[ERROR]     [docker] Configure a credential helper to remove this warning. See
[ERROR]     [docker] https://docs.docker.com/engine/reference/commandline/login/#credentials-store
[DEBUG]     [docker] docker -l error buildx build --platform linux/amd64,linux/arm64 --quiet --file /home/runner/work/riot/riot/out/jreleaser/package/riot-db/docker/Dockerfile --tag fieldengineering/riot-db:early-access --push /home/runner/work/riot/riot/out/jreleaser/package/riot-db/docker
[INFO]      [docker] sha256:8497673b9b215a063cf031cb7ba8fa5df31d502359749f592bf0336d52327857
[DEBUG]     [docker] logout from DEFAULT (docker.io)
[INFO]      [docker] Removing login credentials for DEFAULT
[ERROR]     [docker] jreleaser removed
...
[DEBUG]     [docker] login into DEFAULT (docker.io)
[INFO]      [docker] Login Succeeded
[ERROR]     [docker] WARNING! Using --password via the CLI is insecure. Use --password-stdin.
[ERROR]     [docker] WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
[ERROR]     [docker] Configure a credential helper to remove this warning. See
[ERROR]     [docker] https://docs.docker.com/engine/reference/commandline/login/#credentials-store
[DEBUG]     [docker] docker -l error buildx build --platform linux/amd64,linux/arm64 --quiet --file /home/runner/work/riot/riot/out/jreleaser/package/riot-file/docker/Dockerfile --tag fieldengineering/riot-file:early-access --push /home/runner/work/riot/riot/out/jreleaser/package/riot-file/docker
[ERROR]     [docker] ERROR: multiple platforms feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
[INFO]  Writing output properties to out/jreleaser/output.properties
[ERROR] JReleaser failed after 47.557 s
jreleaser.shadow.org.jreleaser.model.JReleaserException: Unexpected error
	at jreleaser.shadow.org.jreleaser.engine.distribution.Distributions.processPackager(Distributions.java:149)
	at jreleaser.shadow.org.jreleaser.engine.distribution.Distributions.processDistribution(Distributions.java:115)
	at jreleaser.shadow.org.jreleaser.engine.distribution.Distributions.process(Distributions.java:99)
	at jreleaser.shadow.org.jreleaser.workflow.PublishWorkflowItem.doInvoke(PublishWorkflowItem.java:37)
	at jreleaser.shadow.org.jreleaser.workflow.AbstractWorkflowItem.lambda$invoke$0(AbstractWorkflowItem.java:43)
	at jreleaser.shadow.org.jreleaser.engine.hooks.CommandHookExecutor.execute(CommandHookExecutor.java:52)
	at jreleaser.shadow.org.jreleaser.workflow.AbstractWorkflowItem.invoke(AbstractWorkflowItem.java:43)
	at jreleaser.shadow.org.jreleaser.workflow.WorkflowImpl.doExecute(WorkflowImpl.java:113)
	at jreleaser.shadow.org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:52)
	at jreleaser.shadow.org.jreleaser.cli.FullRelease.doExecute(FullRelease.java:180)
	at jreleaser.shadow.org.jreleaser.cli.AbstractModelCommand.execute(AbstractModelCommand.java:92)
	at jreleaser.shadow.org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:37)
	at jreleaser.shadow.org.jreleaser.cli.AbstractModelCommand.call(AbstractModelCommand.java:53)
	at jreleaser.shadow.org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:29)
	at jreleaser.shadow.picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at jreleaser.shadow.picocli.CommandLine.access$1500(CommandLine.java:148)
	at jreleaser.shadow.picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at jreleaser.shadow.picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at jreleaser.shadow.picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at jreleaser.shadow.picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at jreleaser.shadow.picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at jreleaser.shadow.picocli.CommandLine.execute(CommandLine.java:2170)
	at jreleaser.shadow.org.jreleaser.cli.Main.execute(Main.java:73)
	at jreleaser.shadow.org.jreleaser.cli.Main.run(Main.java:69)
	at org.jreleaser.tool.JReleaser.main(JReleaser.java:47)
Caused by: jreleaser.shadow.org.jreleaser.model.spi.packagers.PackagerProcessingException: Unexpected error
	at jreleaser.shadow.org.jreleaser.packagers.AbstractPackagerProcessor.executeCommand(AbstractPackagerProcessor.java:240)
	at jreleaser.shadow.org.jreleaser.packagers.DockerPackagerProcessor.publishDocker(DockerPackagerProcessor.java:395)
	at jreleaser.shadow.org.jreleaser.packagers.DockerPackagerProcessor.doPublishDistribution(DockerPackagerProcessor.java:362)
	at jreleaser.shadow.org.jreleaser.packagers.AbstractPackagerProcessor.publishDistribution(AbstractPackagerProcessor.java:182)
	at jreleaser.shadow.org.jreleaser.packagers.DockerPackagerProcessor.publishDistribution(DockerPackagerProcessor.java:344)
	at jreleaser.shadow.org.jreleaser.engine.distribution.DistributionProcessor.publishDistribution(DistributionProcessor.java:140)
	at jreleaser.shadow.org.jreleaser.engine.distribution.Distributions.processPackager(Distributions.java:144)
	... 24 more
Caused by: jreleaser.shadow.org.jreleaser.sdk.command.CommandException: Command execution error. exitValue = 1
	at jreleaser.shadow.org.jreleaser.packagers.AbstractPackagerProcessor.executeCommand(AbstractPackagerProcessor.java:237)
	... 30 more
```

[trace.log](https://github.com/jreleaser/jreleaser/files/10443580/trace.log)

**Comment by aalmiray** [comment]
Please disable `buildx` and try again.

**Comment by aalmiray** [comment]
**1.3.0**
```yml
packagers:
    docker:
        enabled: true
        active: always
        useLocalArtifact: true
        imageNames:
            fieldengineering/{{distributionName}}:latest
            fieldengineering/{{distributionName}}:{{projectVersion}}
        labels:
            org.opencontainers.image.title: {{distributionName}}
        commitAuthor:
            name: jreleaserbot
            email: jreleaser@kordamp.org
        repository:
            enabled: false
            active: never
            owner: redis-developer
            name: docker
            tagName: v{{projectVersion}}
            branch: HEAD
            username: redis-developer
            token: ************
            versionedSubfolders: false
        continueOnError: false
        registries:
            serverName: DEFAULT
            repositoryName: fieldengineering
            username: jrdx
            password: ************
```

**1.5.0-SNAPSHOT**
```yml
packagers:
    docker:
        enabled: false
        active: never
        useLocalArtifact: true
        buildx:
            enabled: false
            createBuilder: true
        commitAuthor:
            name: jreleaserbot
            email: jreleaser@kordamp.org
        repository:
            enabled: false
            active: release
            owner: redis-developer
            name: docker
            tagName: v{{projectVersion}}
            branch: HEAD
            username: redis-developer
            token: ************
            versionedSubfolders: false
        continueOnError: false
```

Now, at the distributions level I see the following:

**1.3.0**
```yml
        docker:
            enabled: true
            active: always
            templateDirectory: src/jreleaser/distributions/riot-db/docker
            useLocalArtifact: true
            baseImage: azul/zulu-openjdk-alpine:{{distributionJavaVersion}}-jre
            imageNames:
                fieldengineering/{{distributionName}}:latest
            labels:
                org.opencontainers.image.title: {{distributionName}}
                org.opencontainers.image.description: {{projectDescription}}
                org.opencontainers.image.url: {{projectWebsite}}
                org.opencontainers.image.licenses: {{projectLicense}}
                org.opencontainers.image.version: {{projectVersion}}
                org.opencontainers.image.revision: {{commitFullHash}}
            commitAuthor:
                name: jreleaserbot
                email: jreleaser@kordamp.org
            repository:
                enabled: false
                active: release
                owner: redis-developer
                name: riot-docker
                tagName: v{{projectVersion}}
                branch: HEAD
                username: redis-developer
                token: ************
                commitMessage: {{distributionName}} {{tagName}}
                versionedSubfolders: false
            continueOnError: false
            registries:
                serverName: DEFAULT
                repositoryName: fieldengineering
                username: jrdx
                password: ************
```

**1.4.0**
```yml
        docker:
            enabled: true
            active: always
            templateDirectory: src/jreleaser/distributions/riot-db/docker
            useLocalArtifact: true
            baseImage: azul/zulu-openjdk-alpine:{{distributionJavaVersion}}-jre
            imageNames:
                fieldengineering/{{distributionName}}:{{tagName}}
            labels:
                org.opencontainers.image.title: {{distributionName}}
                org.opencontainers.image.description: {{projectDescription}}
                org.opencontainers.image.url: {{projectWebsite}}
                org.opencontainers.image.licenses: {{projectLicense}}
                org.opencontainers.image.version: {{projectVersion}}
                org.opencontainers.image.revision: {{commitFullHash}}
            buildx:
                enabled: true
                createBuilder: true
                createBuilderFlags:
                    --name
                    jreleaser
                    --driver
                    docker-container
                    --bootstrap
                    --use
                platforms:
                    linux/amd64
                    linux/arm64
            commitAuthor:
                name: jreleaserbot
                email: jreleaser@kordamp.org
            repository:
                enabled: false
                active: never
                owner: redis-developer
                name: riot-docker
                tagName: v{{projectVersion}}
                branch: HEAD
                username: redis-developer
                token: ************
                commitMessage: {{distributionName}} {{tagName}}
                versionedSubfolders: false
            continueOnError: false
            registries:
                registry 0:
                    server: docker.io
                    serverName: DEFAULT
                    repositoryName: fieldengineering
                    username: jrdx
                    password: ************
                    externalLogin: false
```

The `buildx` error is caused by the removal of the buldx builder after first publication

```
[ERROR]     [docker] WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
[ERROR]     [docker] Configure a credential helper to remove this warning. See
[ERROR]     [docker] https://docs.docker.com/engine/reference/commandline/login/#credentials-store
[DEBUG]     [docker] docker -l error buildx build --platform linux/amd64,linux/arm64 --quiet --file /home/runner/work/riot/riot/out/jreleaser/package/riot-db/docker/Dockerfile --tag fieldengineering/riot-db:early-access --push /home/runner/work/riot/riot/out/jreleaser/package/riot-db/docker
[INFO]      [docker] sha256:8497673b9b215a063cf031cb7ba8fa5df31d502359749f592bf0336d52327857
[DEBUG]     [docker] logout from DEFAULT (docker.io)
[INFO]      [docker] Removing login credentials for DEFAULT
[ERROR]     [docker] jreleaser removed  <-- THIS IS THE CAUSE
```

Later in the log we see

```
[ERROR]     [docker] WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
[ERROR]     [docker] Configure a credential helper to remove this warning. See
[ERROR]     [docker] https://docs.docker.com/engine/reference/commandline/login/#credentials-store
[DEBUG]     [docker] docker -l error buildx build --platform linux/amd64,linux/arm64 --quiet --file /home/runner/work/riot/riot/out/jreleaser/package/riot-file/docker/Dockerfile --tag fieldengineering/riot-file:early-access --push /home/runner/work/riot/riot/out/jreleaser/package/riot-file/docker
[ERROR]     [docker] ERROR: multiple platforms feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
```

Because the `jreleaser` builder is no longer available. Thus, there's an error in the code related to creating.removing buildx builders. But this does not explain the login problems you face when `buildx` is disabled. I can see that `1.3.0` used to register a DEFAULT registry at the `packagers.docker` level whereas `1.4.0` no longer does it. However, that should not matter much as there's a DEFAULT registry found at the `distributions` level and that's the actual configuration to be used.

**Comment by aalmiray** [comment]
Is this issue still happening with the latest `early-access` builds?
