### ISSUE TITLE
Execution failed for task ':kobweb:cli:kobweb:jreleaserAssemble' --> Unexpected Error

### ISSUE THREAD

**Issue by bitspittle** [jreleaser/jreleaser#1254]
Heads up, this is probably user error but I think you'd want me to report it anyway.

As a way to learn, I'm trying to incrementally add fields to `jlink` and `jpackage` blocks until things build. But then, with this:

```kotlin
        assemble {
            jlink {
                create("kobweb-jlink") {
                    active.set(Active.ALWAYS)
                    exported.set(false)
                    imageName.set("kobweb-{{projectVersion}}")
                    mainJar {
                        path.set(layout.buildDirectory.file("libs/kobweb-cli.jar"))
                    }
                }
            }
            jpackage {
                create("kobweb-installer") {
                    active.set(Active.ALWAYS)
                    jlink.set("kobweb-jlink")
                    attachPlatform.set(true)
                    exported.set(false)
                    applicationPackage {
                        vendor.set("Varabyte")
                    }

                    windows {
                        types.set(listOf("msi"))
                        console.set(true)
                        dirChooser.set(true)
                    }
                }
            }
        }
```

I got this output:

```
Caused by: org.jreleaser.model.JReleaserException: Unexpected error
	at org.jreleaser.engine.assemble.Assemblers.assemble(Assemblers.java:161)
	at org.jreleaser.engine.assemble.Assemblers.doAssemble(Assemblers.java:138)
	at org.jreleaser.engine.assemble.Assemblers.assemble(Assemblers.java:56)
	at org.jreleaser.workflow.AssembleWorkflowItem.doInvoke(AssembleWorkflowItem.java:35)
	at org.jreleaser.workflow.AbstractWorkflowItem.lambda$invoke$0(AbstractWorkflowItem.java:43)
	at org.jreleaser.engine.hooks.CommandHookExecutor.execute(CommandHookExecutor.java:53)
	at org.jreleaser.workflow.AbstractWorkflowItem.invoke(AbstractWorkflowItem.java:43)
	at org.jreleaser.workflow.WorkflowImpl.doExecute(WorkflowImpl.java:115)
	at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:52)
	at org.jreleaser.gradle.plugin.tasks.JReleaserAssembleTask.performAction(JReleaserAssembleTask.groovy:90)
        ...
Caused by: org.jreleaser.model.spi.assemble.AssemblerProcessingException: Unexpected error
	at org.jreleaser.assemblers.AbstractAssemblerProcessor.executeCommandCapturing(AbstractAssemblerProcessor.java:190)
	at org.jreleaser.assemblers.JlinkAssemblerProcessor.resolveModuleNames(JlinkAssemblerProcessor.java:304)
	at org.jreleaser.assemblers.JlinkAssemblerProcessor.doAssemble(JlinkAssemblerProcessor.java:113)
	at org.jreleaser.assemblers.AbstractAssemblerProcessor.assemble(AbstractAssemblerProcessor.java:102)
	at org.jreleaser.engine.assemble.DistributionAssembler.assemble(DistributionAssembler.java:62)
	at org.jreleaser.engine.assemble.Assemblers.assemble(Assemblers.java:155)
        ...
Caused by: org.jreleaser.sdk.command.CommandException: Command execution error. exitValue = 1
	at org.jreleaser.assemblers.AbstractAssemblerProcessor.executeCommandCapturing(AbstractAssemblerProcessor.java:187)
	...
```

I'm guessing what's missing is specifying JDKs for runtime images? But no matter what it ends up being, I suspect you'd want to throw a clearer error message in that case.

**Comment by aalmiray** [comment]
The `jlink` assembler failed for some reason. Either it failed when invoking `jdeps` or the `jlink` command. The clue is in the last debug statement before the stacktrace. It should print out the command that was attempted. If you have a copy of the `trace.log` file that would be swell.

There's no need to specify multiple JDKS for `jlink` _unless_ you want to build cross-platform Java runtimes in a single node. If no JDKs are specified then the current one is used. Be aware that JDK16 is required as a minimum for executing `jpackage`. I'd recommend using JDK17.

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.5.1` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.5.1))
