### ISSUE TITLE
[assemble] Jlink fails on Windows when globs are used

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1270]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. git clone https://github.com/aalmiray/javafx-canvas-plasma
2. Follow build instructions

### Expected Behaviour

Installer archive successfully created

### Actual Behaviour

An error occurs because of invalid paths

```
org.jreleaser.model.JReleaserException: java.nio.file.InvalidPathException: Illegal char <*> at index 77: D:\a\javafx-canvas-plasma\javafx-canvas-plasma\target/repositories/universal/*.jar
	at org.jreleaser.engine.assemble.Assemblers.assemble(Assemblers.java:161)
	at org.jreleaser.engine.assemble.Assemblers.doAssemble(Assemblers.java:138)
	at org.jreleaser.engine.assemble.Assemblers.assemble(Assemblers.java:56)
	at org.jreleaser.workflow.AssembleWorkflowItem.doInvoke(AssembleWorkflowItem.java:35)
	at org.jreleaser.workflow.AbstractWorkflowItem.lambda$invoke$0(AbstractWorkflowItem.java:43)
	at org.jreleaser.engine.hooks.CommandHookExecutor.execute(CommandHookExecutor.java:53)
	at org.jreleaser.workflow.AbstractWorkflowItem.invoke(AbstractWorkflowItem.java:43)
	at org.jreleaser.workflow.WorkflowImpl.doExecute(WorkflowImpl.java:115)
	at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:52)
	at org.jreleaser.maven.plugin.JReleaserAssembleMojo.doExecute(JReleaserAssembleMojo.java:73)
	at org.jreleaser.maven.plugin.AbstractJReleaserMojo.execute(AbstractJReleaserMojo.java:109)
	at org.jreleaser.maven.plugin.JReleaserAssembleMojo.execute(JReleaserAssembleMojo.java:34)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:298)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: org.jreleaser.model.spi.assemble.AssemblerProcessingException: java.nio.file.InvalidPathException: Illegal char <*> at index 77: D:\a\javafx-canvas-plasma\javafx-canvas-plasma\target/repositories/universal/*.jar
	at org.jreleaser.assemblers.AbstractAssemblerProcessor.assemble(AbstractAssemblerProcessor.java:103)
	at org.jreleaser.engine.assemble.DistributionAssembler.assemble(DistributionAssembler.java:62)
	at org.jreleaser.engine.assemble.Assemblers.assemble(Assemblers.java:155)
	... 35 more
Caused by: java.nio.file.InvalidPathException: Illegal char <*> at index 77: D:\a\javafx-canvas-plasma\javafx-canvas-plasma\target/repositories/universal/*.jar
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at org.jreleaser.model.internal.common.Glob.normalizePattern(Glob.java:206)
	at org.jreleaser.model.internal.common.Glob.getResolvedArtifactsPattern(Glob.java:166)
	at org.jreleaser.model.internal.common.Glob.getResolvedArtifacts(Glob.java:160)
	at org.jreleaser.assemblers.AssemblerUtils.copyJars(AssemblerUtils.java:88)
	at org.jreleaser.assemblers.JlinkAssemblerProcessor.doAssemble(JlinkAssemblerProcessor.java:112)
	at org.jreleaser.assemblers.AbstractAssemblerProcessor.assemble(AbstractAssemblerProcessor.java:101)
```

### Environment Information

- **Operating System**: Windows
- **JReleaser Version:** 1.5.1
- **JDK Version:** N/A

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.6.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.6.0))
