### ISSUE TITLE
[signing] NullPointerException is raised when artifact is signed

### ISSUE THREAD

**Issue by algomaster99** [jreleaser/jreleaser#1337]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Export PGP secret key as:
	```sh
		gpg --export-secret-key --armour  --output private.gpg 0EA6DE9E4988911867CA90CA1429025E3EDA19A5
		export JRELEASER_GPG_SECRET_KEY=$(cat private.gpg)
	```

  > Public key: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x1429025e3eda19a5

2. Signing config
	```sh
	  "signing": {
	    "active": "ALWAYS",
	    "armored": true,
	    "verify": false
	  }
	```
3. Run a dry run of `full-release` 
	```sh
    java -jar jreleaser-cli.jar full-release  --dry-run 
	```

### Expected Behaviour

There should be a proper error message at least if I am doing something wrong.

### Actual Behaviour

NPE is raised.

### Environment Information

- **Operating System**: Ubuntu 22.04LTS
- **JReleaser Version:** 1.5.1
- **JDK Version:** 11.0.18

Link to a GitHub workflow: https://github.com/SpoonLabs/sorald/actions/runs/4724170818/jobs/8381068203#step:14:109

```sh
java.lang.NullPointerException
	at jreleaser.shadow.org.jreleaser.sdk.signing.SigningUtils.initSignatureGenerator(SigningUtils.java:233)
	at jreleaser.shadow.org.jreleaser.engine.sign.Signer.sign(Signer.java:342)
	at jreleaser.shadow.org.jreleaser.engine.sign.Signer.bcSign(Signer.java:190)
	at jreleaser.shadow.org.jreleaser.engine.sign.Signer.sign(Signer.java:87)
	at jreleaser.shadow.org.jreleaser.workflow.SignWorkflowItem.doInvoke(SignWorkflowItem.java:39)
	at jreleaser.shadow.org.jreleaser.workflow.AbstractWorkflowItem.lambda$invoke$0(AbstractWorkflowItem.java:43)
	at jreleaser.shadow.org.jreleaser.engine.hooks.CommandHookExecutor.execute(CommandHookExecutor.java:53)
	at jreleaser.shadow.org.jreleaser.workflow.AbstractWorkflowItem.invoke(AbstractWorkflowItem.java:43)
	at jreleaser.shadow.org.jreleaser.workflow.WorkflowImpl.doExecute(WorkflowImpl.java:115)
	at jreleaser.shadow.org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:52)
	at jreleaser.shadow.org.jreleaser.cli.FullRelease.doExecute(FullRelease.java:219)
	at jreleaser.shadow.org.jreleaser.cli.AbstractModelCommand.execute(AbstractModelCommand.java:89)
	at jreleaser.shadow.org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:52)
	at jreleaser.shadow.org.jreleaser.cli.AbstractModelCommand.call(AbstractModelCommand.java:53)
	at jreleaser.shadow.org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:37)
	at jreleaser.shadow.picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at jreleaser.shadow.picocli.CommandLine.access$1500(CommandLine.java:148)
	at jreleaser.shadow.picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at jreleaser.shadow.picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at jreleaser.shadow.picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at jreleaser.shadow.picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at jreleaser.shadow.picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at jreleaser.shadow.picocli.CommandLine.execute(CommandLine.java:2170)
	at jreleaser.shadow.org.jreleaser.cli.Main.execute(Main.java:98)
	at jreleaser.shadow.org.jreleaser.cli.Main.run(Main.java:94)
	at org.jreleaser.tool.JReleaser.main(JReleaser.java:47)
```

**Comment by aalmiray** [comment]
This appears to be a problem with resolving the secret key from the keyring based on https://github.com/jreleaser/jreleaser/blob/b977b66baed1e4761af054c5d747a0804f457252/sdks/jreleaser-signing-java-sdk/src/main/java/org/jreleaser/sdk/signing/SigningUtils.java#L219-L222

Signing code was updated in recent versions. Please upgrade to `v1.5.1` and try again. Validation should kick much earlier if the secret key, public key, or passphrase were to be missing.

**Comment by aalmiray** [comment]
@algomaster99 FWIW release attempt N. 12 failed because signing was disabled. This won't work when deploying artifacts to Maven Central as signatures must be available. Resolved model has the following settings

```yaml
signing:
    enabled: false
    active: never
    armored: false
    artifacts: true
    files: true
    checksums: true
    passphrase: **unset**
    publicKey: **unset**
    secretKey: **unset**

deploy:
    enabled: true
    active: always
    maven:
        enabled: true
        active: always
        nexus2:
            maven-central:
                enabled: true
                active: always
                connectTimeout: 20
                readTimeout: 60
                authorization: basic
                url: https://s01.oss.sonatype.org/service/local
                username: ************
                password: ************
                sign: false
                verifyPom: true
                applyMavenCentralRules: true
                stagingRepositories:
                    target/staging-deploy
                closeRepository: true
                releaseRepository: true
                transitionDelay: 10
                transitionMaxRetries: 60
```

Moreover, deployment to nexus failed earlier with `403` (Operation not authorized. Please review your credentials and try again.) before signature rules were checked.

**Comment by algomaster99** [comment]
Hi @aalmiray !

Upgrading the version works. Thank you!

Release number 13 showed some problems with verification so I am trying to configure the GPG keys again. :D

**Comment by aalmiray** [comment]
Great. Release 14 failed because the passphrase was null. I can see in the logs that the error was triggered during validation as expected.

**Comment by algomaster99** [comment]
Yes, I did not set that accidentally. I just saw that it is required [here](https://jreleaser.org/guide/latest/reference/signing.html). :sweat_smile:

**Comment by algomaster99** [comment]
R15: `Could not find a staging profile matching se.kth.castor`

I am using `chains-bot` sonatype account to deploy it. Let me check again if that account has appropriate rights. I think it had.

**Comment by aalmiray** [comment]
Open the Sonatype UI. Browse to the `Staging Profiles` on the left side bar. Also, if your profile access was granted before Feb 2021 you might need to change the URL to point to the old instance. See the "caution" note at https://jreleaser.org/guide/latest/examples/maven/maven-central.html

**Comment by algomaster99** [comment]
Should I use https://oss.sonatype.org/service/local then?

**Comment by aalmiray** [comment]
> Should I use https://oss.sonatype.org/service/local then?

Yes. You can verify this by login into that instance and checking if the staging profile exists there.

**Comment by algomaster99** [comment]
It worked. Thank you so much for your help :D See https://github.com/SpoonLabs/sorald/actions/runs/4725512232/jobs/8384013026

The build failed overall, but I know how to deal with that.
