### ISSUE TITLE
[release] NPE when performing a release with dry-run enabled

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1341]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Make a copy of https://github.com/jreleaser/helloworld-java-bin and push it to a new repository (no fork)
2. Configure a bogus value for `JRELEASER_GITHUB_TOKEN`
3. Build the project
4. Perform a release in dry-run mode `jreleaser release --dry-run`

### Expected Behaviour

A successful release in dry-run mode.

### Actual Behaviour

NPE occurs

### Environment Information

- **Operating System**: N/A
- **JReleaser Version:** 1.5.1
- **JDK Version:** N/A

```
jreleaser.shadow.org.kohsuke.github.HttpException: {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
	at jreleaser.shadow.org.kohsuke.github.GitHubClient.interpretApiError(GitHubClient.java:483)
	at jreleaser.shadow.org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:407)
	at jreleaser.shadow.org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:355)
	at jreleaser.shadow.org.kohsuke.github.Requester.fetch(Requester.java:76)
	at jreleaser.shadow.org.kohsuke.github.GHRepository.read(GHRepository.java:130)
	at jreleaser.shadow.org.kohsuke.github.GitHub.getRepository(GitHub.java:624)
	at jreleaser.shadow.org.jreleaser.sdk.github.Github.findReleaseByTag(Github.java:171)
	at jreleaser.shadow.org.jreleaser.sdk.github.GithubReleaser.createRelease(GithubReleaser.java:196)
	at jreleaser.shadow.org.jreleaser.model.spi.release.AbstractReleaser.release(AbstractReleaser.java:53)
	at jreleaser.shadow.org.jreleaser.engine.release.Releasers.release(Releasers.java:56)
	at jreleaser.shadow.org.jreleaser.workflow.ReleaseWorkflowItem.doInvoke(ReleaseWorkflowItem.java:39)
	at jreleaser.shadow.org.jreleaser.workflow.AbstractWorkflowItem.lambda$invoke$0(AbstractWorkflowItem.java:43)
	at jreleaser.shadow.org.jreleaser.engine.hooks.CommandHookExecutor.execute(CommandHookExecutor.java:53)
	at jreleaser.shadow.org.jreleaser.workflow.AbstractWorkflowItem.invoke(AbstractWorkflowItem.java:43)
	at jreleaser.shadow.org.jreleaser.workflow.WorkflowImpl.doExecute(WorkflowImpl.java:115)
	at jreleaser.shadow.org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:52)
	at jreleaser.shadow.org.jreleaser.cli.FullRelease.doExecute(FullRelease.java:219)
	at jreleaser.shadow.org.jreleaser.cli.AbstractModelCommand.execute(AbstractModelCommand.java:89)
	at jreleaser.shadow.org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:52)
	at jreleaser.shadow.org.jreleaser.cli.AbstractModelCommand.call(AbstractModelCommand.java:53)
	at jreleaser.shadow.org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:37)
	at jreleaser.shadow.picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at jreleaser.shadow.picocli.CommandLine.access$1500(CommandLine.java:148)
	at jreleaser.shadow.picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at jreleaser.shadow.picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at jreleaser.shadow.picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at jreleaser.shadow.picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at jreleaser.shadow.picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at jreleaser.shadow.picocli.CommandLine.execute(CommandLine.java:2170)
	at jreleaser.shadow.org.jreleaser.cli.Main.execute(Main.java:98)
	at jreleaser.shadow.org.jreleaser.cli.Main.run(Main.java:94)
	at org.jreleaser.tool.JReleaser.main(JReleaser.java:47)
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.github.com/repos/SpoonLabs/sorald
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1974)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1968)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at jreleaser.shadow.org.kohsuke.github.GitHubHttpUrlConnectionClient$HttpURLConnectionResponseInfo.bodyStream(GitHubHttpUrlConnectionClient.java:174)
	at jreleaser.shadow.org.kohsuke.github.GitHubResponse$ResponseInfo.getBodyAsString(GitHubResponse.java:314)
	at jreleaser.shadow.org.kohsuke.github.GitHubResponse.parseBody(GitHubResponse.java:92)
	at jreleaser.shadow.org.kohsuke.github.Requester.lambda$fetch$1(Requester.java:76)
	at jreleaser.shadow.org.kohsuke.github.GitHubClient.createResponse(GitHubClient.java:449)
	at jreleaser.shadow.org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:399)
	... 30 more
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.github.com/repos/SpoonLabs/sorald
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
	at jreleaser.shadow.org.kohsuke.github.GitHubHttpUrlConnectionClient.getResponseInfo(GitHubHttpUrlConnectionClient.java:63)
	at jreleaser.shadow.org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:387)
	... 30 more
```

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.6.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.6.0))
