### ISSUE TITLE
[deploy] Pomchecker validation failure is not captured by `release` while `--dry-run`

### ISSUE THREAD

**Issue by algomaster99** [jreleaser/jreleaser#1362]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

The `release` with `--dry-run` flag passed on this [commit](https://github.com/ASSERT-KTH/collector-sahab/commit/bbb15047a65377778d95b7c73a2f9264630be4fc). However, the actual release failed. See https://github.com/ASSERT-KTH/collector-sahab/actions/runs/4787404774.

### Expected Behaviour

The dry run phase should inform me about my invalid POM.

### Actual Behaviour

The dry run does not notify me.

### Environment Information

- **Operating System**: Ubuntu 22.04
- **JReleaser Version:** 1.5.1
- **JDK Version:** 11.0.18

Please paste stacktraces from `[out|build|target]/jreleaser/trace.log`.
```sh
[INFO]  Cataloging artifacts
[INFO]    [sbom] Cataloging is not enabled. Skipping
[INFO]  Calculating checksums for distributions and files
[DEBUG]   [checksum] checksum does not exist: out/jreleaser/checksums/collector-sahab/collector-sahab-0.1.6-jar-with-dependencies.jar.sha256
[INFO]    [checksum] main/target/collector-sahab-0.1.6-jar-with-dependencies.jar.sha256
[DEBUG]   [checksum] reading out/jreleaser/checksums/collector-sahab/collector-sahab-0.1.6-jar-with-dependencies.jar.sha256
[INFO]  Signing distributions and files
[DEBUG]   [sign] signature does not exist: out/jreleaser/signatures/collector-sahab-0.1.6-jar-with-dependencies.jar.asc
[DEBUG]   [sign] signature does not exist: out/jreleaser/signatures/checksums_sha256.txt.asc
[DEBUG]   [sign] signing 2 files into out/jreleaser/signatures
[INFO]    [sign] main/target/collector-sahab-0.1.6-jar-with-dependencies.jar
[INFO]    [sign] out/jreleaser/checksums/checksums_sha256.txt
[DEBUG]   [sign] verifying 2 signatures
[DEBUG]   [verify] out/jreleaser/signatures/collector-sahab-0.1.6-jar-with-dependencies.jar.asc
[DEBUG]   [verify] out/jreleaser/signatures/checksums_sha256.txt.asc
[INFO]  Deploying Maven artifacts
[INFO]    [maven] Deploying all staged artifacts
[INFO]      [nexus2] Deploying to maven-central
[DEBUG]     [nexus2] Cannot run program "pomchecker": error=2, No such file or directory
[DEBUG]     [nexus2] located pomchecker-1.8.0.zip
[DEBUG]     [nexus2] downloading https://github.com/kordamp/pomchecker/releases/download/v1.8.0/pomchecker-1.8.0.zip
[DEBUG]     [nexus2] downloaded pomchecker-1.8.0.zip successfully
[DEBUG]     [nexus2] unpacked pomchecker-1.8.0.zip
[DEBUG]     [nexus2] cached /home/runner/.jreleaser/caches/pomchecker/1.8.0/pomchecker-1.8.0/bin/pomchecker
[DEBUG]     [nexus2] [ERROR] <description> is not defined in POM. Will use value from parent: 
[DEBUG]     [nexus2] 	A tool for augmenting the static diff with runtime information
[DEBUG]     [nexus2] <url> is not defined in POM. Will use computed value from parent: 
[DEBUG]     [nexus2] 	https://github.com/ASSERT-KTH/collector-sahab/matched-line-finder/
[DEBUG]     [nexus2] [ERROR] <description> is not defined in POM. Will use value from parent: 
[DEBUG]     [nexus2] 	A tool for augmenting the static diff with runtime information
[DEBUG]     [nexus2] <url> is not defined in POM. Will use computed value from parent: 
[DEBUG]     [nexus2] 	https://github.com/ASSERT-KTH/collector-sahab/collector-sahab/
[DEBUG]     [nexus2] [ERROR] <description> is not defined in POM. Will use value from parent: 
[DEBUG]     [nexus2] 	A tool for augmenting the static diff with runtime information
[DEBUG]     [nexus2] <url> is not defined in POM. Will use computed value from parent: 
[DEBUG]     [nexus2] 	https://github.com/ASSERT-KTH/collector-sahab/trace-diff/
[DEBUG]     [nexus2] [ERROR] <description> is not defined in POM. Will use value from parent: 
[DEBUG]     [nexus2] 	A tool for augmenting the static diff with runtime information
[DEBUG]     [nexus2] <url> is not defined in POM. Will use computed value from parent: 
[DEBUG]     [nexus2] 	https://github.com/ASSERT-KTH/collector-sahab/collector-sahab-commons/
[DEBUG]     [nexus2] [ERROR] <description> is not defined in POM. Will use value from parent: 
[DEBUG]     [nexus2] 	A tool for augmenting the static diff with runtime information
[DEBUG]     [nexus2] <url> is not defined in POM. Will use computed value from parent: 
[DEBUG]     [nexus2] 	https://github.com/ASSERT-KTH/collector-sahab/trace-collector/
[ERROR]     [nexus2] Command execution error. exitValue = 1
[INFO]  Writing output properties to out/jreleaser/output.properties
[ERROR] JReleaser failed after 13.907 s
org.jreleaser.model.JReleaserException: Rules for publishing to Maven Central were not met
	at jreleaser.shadow.org.jreleaser.sdk.commons.AbstractMavenDeployer.collectDeployables(AbstractMavenDeployer.java:136)
	at jreleaser.shadow.org.jreleaser.sdk.nexus2.Nexus2MavenDeployer.deploy(Nexus2MavenDeployer.java:57)
	at jreleaser.shadow.org.jreleaser.engine.deploy.maven.ProjectMavenDeployer.deploy(ProjectMavenDeployer.java:55)
	at jreleaser.shadow.org.jreleaser.engine.deploy.maven.MavenDeployers.deploy(MavenDeployers.java:167)
	at jreleaser.shadow.org.jreleaser.engine.deploy.maven.MavenDeployers.doDeploy(MavenDeployers.java:150)
	at jreleaser.shadow.org.jreleaser.engine.deploy.maven.MavenDeployers.deploy(MavenDeployers.java:59)
	at jreleaser.shadow.org.jreleaser.workflow.DeployWorkflowItem.doInvoke(DeployWorkflowItem.java:35)
	at jreleaser.shadow.org.jreleaser.workflow.AbstractWorkflowItem.lambda$invoke$0(AbstractWorkflowItem.java:43)
	at jreleaser.shadow.org.jreleaser.engine.hooks.CommandHookExecutor.execute(CommandHookExecutor.java:53)
	at jreleaser.shadow.org.jreleaser.workflow.AbstractWorkflowItem.invoke(AbstractWorkflowItem.java:43)
	at jreleaser.shadow.org.jreleaser.workflow.WorkflowImpl.doExecute(WorkflowImpl.java:115)
	at jreleaser.shadow.org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:52)
	at jreleaser.shadow.org.jreleaser.cli.Release.doExecute(Release.java:380)
	at jreleaser.shadow.org.jreleaser.cli.AbstractModelCommand.execute(AbstractModelCommand.java:89)
	at jreleaser.shadow.org.jreleaser.cli.Release.execute(Release.java:307)
	at jreleaser.shadow.org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:52)
	at jreleaser.shadow.org.jreleaser.cli.AbstractModelCommand.call(AbstractModelCommand.java:53)
	at jreleaser.shadow.org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:37)
	at jreleaser.shadow.picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at jreleaser.shadow.picocli.CommandLine.access$1500(CommandLine.java:148)
	at jreleaser.shadow.picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at jreleaser.shadow.picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at jreleaser.shadow.picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at jreleaser.shadow.picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at jreleaser.shadow.picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at jreleaser.shadow.picocli.CommandLine.execute(CommandLine.java:2170)
	at jreleaser.shadow.org.jreleaser.cli.Main.execute(Main.java:98)
	at jreleaser.shadow.org.jreleaser.cli.Main.run(Main.java:94)
	at org.jreleaser.tool.JReleaser.main(JReleaser.java:47)
```

To see the full stack trace, you may download the artifact [here](https://github.com/ASSERT-KTH/collector-sahab/actions/runs/4787404774).

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.6.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.6.0))
