### ISSUE TITLE
[release] JRELEASER_DEFAULT_GIT_REMOTE ignored during tagging

### ISSUE THREAD

**Issue by gunnarmorling** [jreleaser/jreleaser#1434]
I have set the `JRELEASER_DEFAULT_GIT_REMOTE` env var by running this:

```
JRELEASER_DEFAULT_GIT_REMOTE=upstream ./gradlew jreleaserFullRelease --stacktrace
```

It still tries to use the name "origin" though:

```
org.jreleaser.model.spi.release.ReleaseException: org.eclipse.jgit.api.errors.TransportException: origin: not found.
        at org.jreleaser.sdk.git.release.ReleaseUtils.tagRelease(ReleaseUtils.java:94)
        at org.jreleaser.sdk.git.release.ReleaseUtils.createTag(ReleaseUtils.java:65)
        at org.jreleaser.sdk.git.release.AbstractReleaser.createTag(AbstractReleaser.java:73)
        at org.jreleaser.sdk.git.release.AbstractReleaser.release(AbstractReleaser.java:56)
        at org.jreleaser.engine.release.Releasers.release(Releasers.java:56)
        at org.jreleaser.workflow.ReleaseWorkflowItem.doInvoke(ReleaseWorkflowItem.java:39)
```

**Comment by gunnarmorling** [comment]
Hum, hum, interesting. Are you actually creating a tag there? In case you can't reproduce it, let's close this one. I'm solely running that job on GH Actions now, where the remote is named origin anyways, i.e. this is not a blocker for me. Thanks for all your efforts?

**Comment by aalmiray** [comment]
I'll double check but yes, I created a tag and a release at a remote repo.
