### ISSUE TITLE
Cannot release using the provided Docker images

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#150]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. clone https://github.com/aalmiray/test.git
2. configure environment variables
3. run either `jreleaser/jreleaser-slim:early-access` or `jreleaser/jreleaser-alpine:early-access` image with `release -y`.

### Expected Behaviour

Successful release

### Actual Behaviour

Release failure

```
[INFO]  Releasing to https://github.com/aalmiray/test
[DEBUG] looking up release with tag v1.0.0 at repository aalmiray/test
[DEBUG] fetching release on aalmiray/test with tag v1.0.0
org.kohsuke.github.HttpException: Server returned HTTP response code: -1, message: 'null' for URL: https://api.github.com/repos/aalmiray/test
	at org.kohsuke.github.GitHubClient.interpretApiError(GitHubClient.java:490)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:409)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:357)
	at org.kohsuke.github.Requester.fetch(Requester.java:76)
	at org.kohsuke.github.GHRepository.read(GHRepository.java:130)
	at org.kohsuke.github.GitHub.getRepository(GitHub.java:624)
	at org.jreleaser.sdk.github.Github.findReleaseByTag(Github.java:132)
	at org.jreleaser.sdk.github.GithubReleaser.release(GithubReleaser.java:64)
	at org.jreleaser.engine.release.Releasers.release(Releasers.java:42)
	at org.jreleaser.workflow.ReleaseWorkflowItem.invoke(ReleaseWorkflowItem.java:33)
	at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:51)
	at org.jreleaser.cli.Release.doExecute(Release.java:178)
	at org.jreleaser.cli.AbstractModelCommand.execute(AbstractModelCommand.java:64)
	at org.jreleaser.cli.Release.execute(Release.java:125)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:72)
	at org.jreleaser.cli.AbstractModelCommand.call(AbstractModelCommand.java:38)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.jreleaser.cli.Main.execute(Main.java:73)
	at org.jreleaser.cli.Main.run(Main.java:59)
	at org.jreleaser.cli.Main.main(Main.java:51)
Caused by: javax.net.ssl.SSLProtocolException: Cannot decode named group: x25519
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.KeyShareExtension$SHKeyShareConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.SSLExtension.consumeOnLoad(Unknown Source)
	at java.base/sun.security.ssl.SSLExtensions.consumeOnLoad(Unknown Source)
	at java.base/sun.security.ssl.ServerHello$T13ServerHelloConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.ServerHello$ServerHelloConsumer.onServerHello(Unknown Source)
	at java.base/sun.security.ssl.ServerHello$ServerHelloConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at org.kohsuke.github.GitHubHttpUrlConnectionClient.getResponseInfo(GitHubHttpUrlConnectionClient.java:63)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:389)
	... 25 more
[INFO]  Writing output properties to out/jreleaser/output.properties
[ERROR] JReleaser failed after 1.372 s
org.jreleaser.model.JReleaserException: Unexpected error when creating release.
	at org.jreleaser.workflow.ReleaseWorkflowItem.invoke(ReleaseWorkflowItem.java:35)
	at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:51)
	at org.jreleaser.cli.Release.doExecute(Release.java:178)
	at org.jreleaser.cli.AbstractModelCommand.execute(AbstractModelCommand.java:64)
	at org.jreleaser.cli.Release.execute(Release.java:125)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:72)
	at org.jreleaser.cli.AbstractModelCommand.call(AbstractModelCommand.java:38)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.jreleaser.cli.Main.execute(Main.java:73)
	at org.jreleaser.cli.Main.run(Main.java:59)
	at org.jreleaser.cli.Main.main(Main.java:51)
Caused by: org.jreleaser.model.releaser.spi.ReleaseException: org.kohsuke.github.HttpException: Server returned HTTP response code: -1, message: 'null' for URL: https://api.github.com/repos/aalmiray/test
	at org.jreleaser.sdk.github.GithubReleaser.release(GithubReleaser.java:91)
	at org.jreleaser.engine.release.Releasers.release(Releasers.java:42)
	at org.jreleaser.workflow.ReleaseWorkflowItem.invoke(ReleaseWorkflowItem.java:33)
	... 17 more
Caused by: org.kohsuke.github.HttpException: Server returned HTTP response code: -1, message: 'null' for URL: https://api.github.com/repos/aalmiray/test
	at org.kohsuke.github.GitHubClient.interpretApiError(GitHubClient.java:490)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:409)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:357)
	at org.kohsuke.github.Requester.fetch(Requester.java:76)
	at org.kohsuke.github.GHRepository.read(GHRepository.java:130)
	at org.kohsuke.github.GitHub.getRepository(GitHub.java:624)
	at org.jreleaser.sdk.github.Github.findReleaseByTag(Github.java:132)
	at org.jreleaser.sdk.github.GithubReleaser.release(GithubReleaser.java:64)
	... 19 more
Caused by: javax.net.ssl.SSLProtocolException: Cannot decode named group: x25519
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.KeyShareExtension$SHKeyShareConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.SSLExtension.consumeOnLoad(Unknown Source)
	at java.base/sun.security.ssl.SSLExtensions.consumeOnLoad(Unknown Source)
	at java.base/sun.security.ssl.ServerHello$T13ServerHelloConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.ServerHello$ServerHelloConsumer.onServerHello(Unknown Source)
	at java.base/sun.security.ssl.ServerHello$ServerHelloConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at org.kohsuke.github.GitHubHttpUrlConnectionClient.getResponseInfo(GitHubHttpUrlConnectionClient.java:63)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:389)
	... 25 more
```

### Environment Information

- **Operating System**: N/A
- **JReleaser Version:** 0.4.0-SNAPsHOT
- **JDK Version:** N/A

**Comment by aalmiray** [comment]
This is likely an issue with the Java security certificates that may be missing in the Docker images.
