### ISSUE TITLE
Invalid field on github release

### ISSUE THREAD

**Issue by evanchooly** [jreleaser/jreleaser#1500]
This might be a duplicate of #1421 but i get this stacktrace on a release.  The artifacts are successfully deployed to maven central but the jreleaser run itself fails.

But the root cause is:  
```{"message":"Validation Failed","errors":[{ "resource" : "Release", "code" : "invalid", "field" : "target_commitish"}], "documentation_url":"https://docs.github.com/rest/releases/releases#create-a-release"}```

```
[DEBUG] creating release on MorphiaOrg/morphia with tag v2.4.6
org.jreleaser.sdk.commons.RestAPIException: 422: Unprocessable Entity
{"message":"Validation Failed","errors":[{"resource":"Release","code":"invalid","field":"target_commitish"}],"documentation_url":"https://docs.github.com/rest/releases/releases#create-a-release"}
	at org.jreleaser.sdk.commons.ClientUtils.lambda$builder$1(ClientUtils.java:114)
	at feign.ResponseHandler.decodeError(ResponseHandler.java:139)
	at feign.ResponseHandler.handleResponse(ResponseHandler.java:73)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:114)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:70)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:96)
	at com.sun.proxy.$Proxy35.createRelease(Unknown Source)
	at org.jreleaser.sdk.github.Github.createRelease(Github.java:334)
	at org.jreleaser.sdk.github.GithubReleaser.createRelease(GithubReleaser.java:360)
	at org.jreleaser.sdk.github.GithubReleaser.createRelease(GithubReleaser.java:231)
	at org.jreleaser.sdk.git.release.AbstractReleaser.release(AbstractReleaser.java:59)
	at org.jreleaser.engine.release.Releasers.release(Releasers.java:56)
	at org.jreleaser.workflow.ReleaseWorkflowItem.doInvoke(ReleaseWorkflowItem.java:39)
	at org.jreleaser.workflow.AbstractWorkflowItem.lambda$invoke$0(AbstractWorkflowItem.java:43)
	at org.jreleaser.engine.hooks.HookExecutor.execute(HookExecutor.java:70)
	at org.jreleaser.workflow.AbstractWorkflowItem.invoke(AbstractWorkflowItem.java:43)
	at org.jreleaser.workflow.WorkflowImpl.doExecute(WorkflowImpl.java:115)
	at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:52)
	at org.jreleaser.maven.plugin.JReleaserFullReleaseMojo.doExecute(JReleaserFullReleaseMojo.java:156)
	at org.jreleaser.maven.plugin.AbstractJReleaserMojo.execute(AbstractJReleaserMojo.java:109)
	at org.jreleaser.maven.plugin.JReleaserFullReleaseMojo.execute(JReleaserFullReleaseMojo.java:33)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:52)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:161)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:73)
[INFO]  Writing output properties to target/jreleaser/output.properties
[ERROR] JReleaser failed after 01:34 m
org.jreleaser.model.JReleaserException: Unexpected error when creating release
	at org.jreleaser.workflow.ReleaseWorkflowItem.doInvoke(ReleaseWorkflowItem.java:41)
	at org.jreleaser.workflow.AbstractWorkflowItem.lambda$invoke$0(AbstractWorkflowItem.java:43)
	at org.jreleaser.engine.hooks.HookExecutor.execute(HookExecutor.java:70)
	at org.jreleaser.workflow.AbstractWorkflowItem.invoke(AbstractWorkflowItem.java:43)
	at org.jreleaser.workflow.WorkflowImpl.doExecute(WorkflowImpl.java:115)
	at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:52)
	at org.jreleaser.maven.plugin.JReleaserFullReleaseMojo.doExecute(JReleaserFullReleaseMojo.java:156)
	at org.jreleaser.maven.plugin.AbstractJReleaserMojo.execute(AbstractJReleaserMojo.java:109)
	at org.jreleaser.maven.plugin.JReleaserFullReleaseMojo.execute(JReleaserFullReleaseMojo.java:33)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:52)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:161)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:73)
Caused by: org.jreleaser.model.spi.release.ReleaseException: org.jreleaser.sdk.commons.RestAPIException: 422: Unprocessable Entity
{"message":"Validation Failed","errors":[{"resource":"Release","code":"invalid","field":"target_commitish"}],"documentation_url":"https://docs.github.com/rest/releases/releases#create-a-release"}
	at org.jreleaser.sdk.github.GithubReleaser.createRelease(GithubReleaser.java:235)
	at org.jreleaser.sdk.git.release.AbstractReleaser.release(AbstractReleaser.java:59)
	at org.jreleaser.engine.release.Releasers.release(Releasers.java:56)
	at org.jreleaser.workflow.ReleaseWorkflowItem.doInvoke(ReleaseWorkflowItem.java:39)
	... 42 more
Caused by: org.jreleaser.sdk.commons.RestAPIException: 422: Unprocessable Entity
{"message":"Validation Failed","errors":[{"resource":"Release","code":"invalid","field":"target_commitish"}],"documentation_url":"https://docs.github.com/rest/releases/releases#create-a-release"}
	at org.jreleaser.sdk.commons.ClientUtils.lambda$builder$1(ClientUtils.java:114)
	at feign.ResponseHandler.decodeError(ResponseHandler.java:139)
	at feign.ResponseHandler.handleResponse(ResponseHandler.java:73)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:114)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:70)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:96)
	at com.sun.proxy.$Proxy35.createRelease(Unknown Source)
	at org.jreleaser.sdk.github.Github.createRelease(Github.java:334)
	at org.jreleaser.sdk.github.GithubReleaser.createRelease(GithubReleaser.java:360)
	at org.jreleaser.sdk.github.GithubReleaser.createRelease(GithubReleaser.java:231)
	... 45 more
```

**Comment by evanchooly** [comment]
[jreleaser.log.zip](https://github.com/jreleaser/jreleaser/files/12778066/jreleaser.log.zip)

**Comment by aalmiray** [comment]
What is the name of your default git remote? JReleaser expects it to be `origin` but it may be set to a different value using `JRELEASER_DEFAULT_REMOTE` env var.

**Comment by aalmiray** [comment]
I asked because I recently got the same error when the default remote was not named `origin` snd thought this would be the cause of the error you saw.
