### ISSUE TITLE
[signing] ECDH keys not being recognized

### ISSUE THREAD

**Issue by bmarwell** [jreleaser/jreleaser#152]
This is an upstream issue. This issue only exists for upgrading as soon as upstream is fixed.

Follow-up to https://github.com/jreleaser/jreleaser/issues/136.
Of course I created a new key using Curve25519.

```
[INFO]  Writing output properties to out/jreleaser/output.properties
[ERROR] JReleaser failed after 1.012 s
org.jreleaser.model.JReleaserException: Unexpected error when signing release.
        at org.jreleaser.workflow.SignWorkflowItem.invoke(SignWorkflowItem.java:35)
        at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:51)
        at org.jreleaser.cli.Sign.doExecute(Sign.java:34)
        at org.jreleaser.cli.AbstractModelCommand.execute(AbstractModelCommand.java:64)
        at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:72)
        at org.jreleaser.cli.AbstractModelCommand.call(AbstractModelCommand.java:38)
        at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at org.jreleaser.cli.Main.execute(Main.java:73)
        at org.jreleaser.cli.Main.run(Main.java:59)
        at org.jreleaser.cli.Main.main(Main.java:51)
Caused by: org.jreleaser.util.signing.SigningException: Unexpected error when initializing signature generator
        at org.jreleaser.engine.sign.Signer.initSignatureGenerator(Signer.java:218)
        at org.jreleaser.engine.sign.Signer.sign(Signer.java:194)
        at org.jreleaser.engine.sign.Signer.sign(Signer.java:104)
        at org.jreleaser.workflow.SignWorkflowItem.invoke(SignWorkflowItem.java:33)
        ... 16 more
Caused by: org.bouncycastle.openpgp.PGPException: unknown algorithm tag in signature:18
        at org.bouncycastle.openpgp.operator.jcajce.OperatorHelper.createSignature(Unknown Source)
        at org.bouncycastle.openpgp.operator.jcajce.JcaPGPContentSignerBuilder.build(Unknown Source)
        at org.bouncycastle.openpgp.operator.jcajce.JcaPGPContentSignerBuilder.build(Unknown Source)
        at org.bouncycastle.openpgp.PGPSignatureGenerator.init(Unknown Source)
        at org.jreleaser.engine.sign.Signer.initSignatureGenerator(Signer.java:214)
        ... 19 more                                                                                                                                                                                              
```

### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create an ECDH key using GnuPG or similar
2. use in jreleaser

### Expected Behaviour

Key being used

### Actual Behaviour

Exception: https://github.com/bcgit/bc-java/blob/4a937ecd3ed3934fecb742063ea2fea6e7b9af8d/pg/src/main/java/org/bouncycastle/openpgp/operator/jcajce/OperatorHelper.java#L276
also
https://github.com/bcgit/bc-java/blob/4a937ecd3ed3934fecb742063ea2fea6e7b9af8d/pg/src/main/java/org/bouncycastle/bcpg/PublicKeyAlgorithmTags.java#L17

### Environment Information

- **Operating System**: Ubuntu 20.04
- **JReleaser Version:** 0.3.0 or 0.4.0-SNAPSHOT
- **JDK Version:** 11 OpenJ9

**Comment by dghgit** [comment]
Could I suggest creating the Curve25519 key for signing rather than encryption instead? 18 is ECDH, the key should be 19 (ECDSA) if it is being used for signature generation.

**Comment by bmarwell** [comment]
@dghgit thanks, I thought I used a template for key generation (sadly I deleted it).
My key looks like this:
```
sec   ed25519/0x31605D40DD2A99F4 2021-05-16 [SC] [expires: 2025-05-15]
      Key fingerprint = 331C 8E5F F20D 3A48 C8E1  81A9 3160 5D40 DD2A 99F4
uid                   [ultimate] bmarwell <--------redacted----->
ssb   cv25519/0x825FDF7EC5B29A57 2021-05-16 [E] [expires: 2025-05-15]
```

Is this wrong?

**Comment by bmarwell** [comment]
I will backtrack if the correct key will be used. Backtracking from here: https://github.com/jreleaser/jreleaser/blob/v0.3.0/core/jreleaser-engine/src/main/java/org/jreleaser/engine/sign/Signer.java

Yes, I double checked my config.toml file.
I used `gpg --armor --export-secret-keys 0x31605D40DD2A99F4` for the secret key and `gpg --armor --export 0xdd2a99f4` for the public one.

**Comment by bmarwell** [comment]
Got it.
If I change this line to negate, it works:
https://github.com/jreleaser/jreleaser/blob/3daccfe4490299686ef2614a15629890bb0b091e/core/jreleaser-utils/src/main/java/org/jreleaser/util/signing/InMemoryKeyring.java#L91
Maybe the encryption key is not the same as the signing key?

**Comment by aalmiray** [comment]
I see. We need a better way to detect the default public key. Other tools use the last 8 characters of a keyId parameter for example. I'll look for alternatives.

**Comment by bmarwell** [comment]
> I see. We need a better way to detect the default public key. Other tools use the last 8 characters of a keyId parameter for example. I'll look for alternatives.

a method `isSigningKey()` would make sense for BC’s PublicKey class.
But maybe just hand over a key ID, yes. both would work.
