### ISSUE TITLE
[announce] Could not announce via HTTP announcer

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1523]
During the `v1.9.0` release the HTTP announcer for jreleaser.noticeable.io failed with

```
Exception in thread "main" java.lang.NoSuchMethodError: 'org.apache.commons.lang3.Range org.apache.commons.lang3.Range.of(java.lang.Comparable, java.lang.Comparable)'
	at org.apache.commons.text.translate.NumericEntityEscaper.<init>(NumericEntityEscaper.java:97)
	at org.apache.commons.text.translate.NumericEntityEscaper.between(NumericEntityEscaper.java:59)
	at org.apache.commons.text.StringEscapeUtils.<clinit>(StringEscapeUtils.java:271)
	at org.jreleaser.extensions.internal.mustache.DefaultMustacheExtensionPoint$DelegatingFunction.apply(DefaultMustacheExtensionPoint.java:285)
	at org.jreleaser.extensions.internal.mustache.DefaultMustacheExtensionPoint$DelegatingFunction.apply(DefaultMustacheExtensionPoint.java:276)
	at com.github.mustachejava.codes.IterableCode.handleFunction(IterableCode.java:119)
	at com.github.mustachejava.codes.IterableCode.handle(IterableCode.java:50)
	at com.github.mustachejava.codes.IterableCode.execute(IterableCode.java:42)
	at com.github.mustachejava.codes.DefaultMustache.run(DefaultMustache.java:34)
	at com.github.mustachejava.codes.DefaultCode.execute(DefaultCode.java:162)
	at com.github.mustachejava.codes.DefaultMustache.execute(DefaultMustache.java:57)
	at com.github.mustachejava.codes.IterableCode.writeTemplate(IterableCode.java:134)
	at com.github.mustachejava.codes.IterableCode.handleFunction(IterableCode.java:116)
	at com.github.mustachejava.codes.IterableCode.handle(IterableCode.java:50)
	at com.github.mustachejava.codes.IterableCode.execute(IterableCode.java:42)
	at com.github.mustachejava.codes.DefaultMustache.run(DefaultMustache.java:34)
	at com.github.mustachejava.codes.DefaultCode.execute(DefaultCode.java:162)
	at com.github.mustachejava.codes.DefaultMustache.execute(DefaultMustache.java:57)
	at com.github.mustachejava.Mustache.execute(Mustache.java:38)
	at org.jreleaser.mustache.MustacheUtils.applyTemplate(MustacheUtils.java:67)
	at org.jreleaser.mustache.MustacheUtils.applyTemplate(MustacheUtils.java:87)
	at org.jreleaser.model.internal.announce.HttpAnnouncer.getResolvedPayloadTemplate(HttpAnnouncer.java:204)
	at org.jreleaser.sdk.http.HttpAnnouncer.announce(HttpAnnouncer.java:96)
	at org.jreleaser.sdk.http.HttpAnnouncer.announce(HttpAnnouncer.java:79)
	at org.jreleaser.engine.announce.Announcers.announce(Announcers.java:127)
	at org.jreleaser.engine.announce.Announcers.announce(Announcers.java:109)
	at org.jreleaser.workflow.AnnounceWorkflowItem.doInvoke(AnnounceWorkflowItem.java:35)
	at org.jreleaser.workflow.AbstractWorkflowItem.lambda$invoke$0(AbstractWorkflowItem.java:43)
	at org.jreleaser.engine.hooks.HookExecutor.execute(HookExecutor.java:70)
	at org.jreleaser.workflow.AbstractWorkflowItem.invoke(AbstractWorkflowItem.java:43)
	at org.jreleaser.workflow.WorkflowImpl.doExecute(WorkflowImpl.java:115)
	at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:52)
	at org.jreleaser.cli.Announce.doExecute(Announce.java:82)
	at org.jreleaser.cli.AbstractModelCommand.execute(AbstractModelCommand.java:89)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:52)
	at org.jreleaser.cli.AbstractModelCommand.call(AbstractModelCommand.java:53)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.jreleaser.cli.Main.execute(Main.java:98)
	at org.jreleaser.cli.Main.run(Main.java:81)
	at org.jreleaser.cli.Main.main(Main.java:70)
```

**Comment by aalmiray** [comment]
Fixed with 84626492dd8d6b9650cb9fc7f01eeee23e371181
