### ISSUE TITLE
[announce] Bluesky announcer failed due to date format error

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1564]
Got the following when releasing JReleaser `1.10.0`

```
[INFO]  Announcing release
[DEBUG]   [article] disabled. Skipping
[INFO]    [bluesky] skeeting: 🚀 JReleaser 1.10.0 has been released! [https://github.com/jreleaser/jreleaser/releases/tag/v1.10.0](https://github.com/jreleaser/jreleaser/releases/tag/v1.10.0)
[DEBUG]   [bluesky] status is 161 chars long
[INFO]    [bluesky] skeeting: 😅 This is mostly a fix release with a handful of enhancements. We'd like to thank our most recent contributors [https://github.com/jreleaser/jreleaser/blob/main/CONTRIBUTORS.md](https://github.com/jreleaser/jreleaser/blob/main/CONTRIBUTORS.md)
[DEBUG]   [bluesky] status is 244 chars long
[INFO]    [bluesky] skeeting: 📣 Links in Bluesky announcer will be automatically converted to markdown links
[DEBUG]   [bluesky] status is 79 chars long
[INFO]    [bluesky] skeeting: 📦 Homebrew packager now supports defining custom download strategy and additional require relative statements
[DEBUG]   [bluesky] status is 110 chars long
[INFO]    [bluesky] skeeting: 🗒️  Changelog commits can now be identified by author/contributor, not just title and body
[DEBUG]   [bluesky] status is 91 chars long
[INFO]    [bluesky] skeeting: 🏗️  Several updates to hooks such as new session event, conditional evaluation, and access to stacktrace upon failure
[DEBUG]   [bluesky] status is 118 chars long
[INFO]    [bluesky] skeeting: ☕️ Provide custom JAVA_OPTS to the launcher generated by the Jlink assembler
[DEBUG]   [bluesky] status is 76 chars long
[INFO]    [bluesky] skeeting: 📝 Full list of changes available at the v1.10.0 milestone [https://github.com/jreleaser/jreleaser/milestones?state=closed](https://github.com/jreleaser/jreleaser/milestones?state=closed)
[DEBUG]   [bluesky] status is 187 chars long
[INFO]    [bluesky] skeeting: 🙏 As always, feedback is welcome. Feel free to raise a ticket at [https://github.com/jreleaser/jreleaser/issues](https://github.com/jreleaser/jreleaser/issues)
[DEBUG]   [bluesky] status is 160 chars long
[DEBUG]   [bluesky] dry-run set to false
jreleaser.shadow.org.jreleaser.sdk.commons.RestAPIException: 400: Bad Request
{"error":"InvalidRequest","message":"Invalid app.bsky.feed.post record: createdAt must be an valid atproto datetime (both RFC-3339 and ISO-8601)"}
	at jreleaser.shadow.org.jreleaser.sdk.commons.ClientUtils.lambda$builder$1(ClientUtils.java:114)
	at jreleaser.shadow.feign.InvocationContext.decodeError(InvocationContext.java:126)
	at jreleaser.shadow.feign.InvocationContext.proceed(InvocationContext.java:72)
	at jreleaser.shadow.feign.ResponseHandler.handleResponse(ResponseHandler.java:63)
	at jreleaser.shadow.feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:114)
	at jreleaser.shadow.feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:70)
	at jreleaser.shadow.feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:99)
	at jdk.proxy2/jdk.proxy2.$Proxy24.createRecord(Unknown Source)
	at jreleaser.shadow.org.jreleaser.sdk.bluesky.BlueskySdk.lambda$skeet$0(BlueskySdk.java:89)
	at jreleaser.shadow.org.jreleaser.sdk.bluesky.BlueskySdk.wrap(BlueskySdk.java:107)
	at jreleaser.shadow.org.jreleaser.sdk.bluesky.BlueskySdk.skeet(BlueskySdk.java:83)
	at jreleaser.shadow.org.jreleaser.sdk.bluesky.BlueskyAnnouncer.announce(BlueskyAnnouncer.java:114)
	at jreleaser.shadow.org.jreleaser.engine.announce.Announcers.announce(Announcers.java:127)
	at jreleaser.shadow.org.jreleaser.engine.announce.Announcers.announce(Announcers.java:109)
	at jreleaser.shadow.org.jreleaser.workflow.AnnounceWorkflowItem.doInvoke(AnnounceWorkflowItem.java:35)
	at jreleaser.shadow.org.jreleaser.workflow.AbstractWorkflowItem.lambda$invoke$0(AbstractWorkflowItem.java:43)
	at jreleaser.shadow.org.jreleaser.engine.hooks.HookExecutor.execute(HookExecutor.java:70)
	at jreleaser.shadow.org.jreleaser.workflow.AbstractWorkflowItem.invoke(AbstractWorkflowItem.java:43)
	at jreleaser.shadow.org.jreleaser.workflow.WorkflowImpl.doExecute(WorkflowImpl.java:129)
	at jreleaser.shadow.org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:54)
	at jreleaser.shadow.org.jreleaser.cli.FullRelease.doExecute(FullRelease.java:219)
	at jreleaser.shadow.org.jreleaser.cli.AbstractModelCommand.execute(AbstractModelCommand.java:89)
	at jreleaser.shadow.org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:52)
	at jreleaser.shadow.org.jreleaser.cli.AbstractModelCommand.call(AbstractModelCommand.java:53)
	at jreleaser.shadow.org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:37)
	at jreleaser.shadow.picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at jreleaser.shadow.picocli.CommandLine.access$1500(CommandLine.java:148)
	at jreleaser.shadow.picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at jreleaser.shadow.picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at jreleaser.shadow.picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at jreleaser.shadow.picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at jreleaser.shadow.picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at jreleaser.shadow.picocli.CommandLine.execute(CommandLine.java:2170)
	at jreleaser.shadow.org.jreleaser.cli.Main.execute(Main.java:98)
	at jreleaser.shadow.org.jreleaser.cli.Main.run(Main.java:94)
	at org.jreleaser.tool.JReleaser.main(JReleaser.java:47)
[WARN]    [bluesky] jreleaser.shadow.org.jreleaser.sdk.bluesky.BlueskyException: Bluesky operation failed
```

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.11.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.11.0))
