### ISSUE TITLE
Failure when using jreleaser/jreleaser-slim:early-access Docker image

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1629]
Reported at https://github.com/jreleaser/jreleaser/issues/1621#issuecomment-2020996690

Exception occurs during a release

```
Exception in thread "main" java.lang.NoClassDefFoundError: java/rmi/UnexpectedException
	at feign.form.FormEncoder.getCharset(FormEncoder.java:138)
	at feign.form.FormEncoder.encode(FormEncoder.java:104)
	at feign.RequestTemplateFactoryResolver$BuildFormEncodedTemplateFromArgs.resolve(RequestTemplateFactoryResolver.java:235)
	at feign.RequestTemplateFactoryResolver$BuildTemplateByResolvingArgs.create(RequestTemplateFactoryResolver.java:106)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:65)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:99)
	at jdk.proxy2/jdk.proxy2.$Proxy20.uploadFile(Unknown Source)
	at org.jreleaser.sdk.gitlab.Gitlab.uploadAssets(Gitlab.java:379)
	at org.jreleaser.sdk.gitlab.GitlabReleaser.createRelease(GitlabReleaser.java:294)
	at org.jreleaser.sdk.gitlab.GitlabReleaser.createRelease(GitlabReleaser.java:1[62](https://gitlab.com/sinch/sinch-projects/enterprise-and-messaging/beehive/teams/platform-core/experiments/test-releases/-/jobs/6480923815#L62))
	at org.jreleaser.sdk.git.release.AbstractReleaser.release(AbstractReleaser.java:59)
	at org.jreleaser.engine.release.Releasers.release(Releasers.java:56)
	at org.jreleaser.workflow.ReleaseWorkflowItem.doInvoke(ReleaseWorkflowItem.java:39)
	at org.jreleaser.workflow.AbstractWorkflowItem.lambda$invoke$0(AbstractWorkflowItem.java:43)
	at org.jreleaser.engine.hooks.HookExecutor.execute(HookExecutor.java:[70](https://gitlab.com/sinch/sinch-projects/enterprise-and-messaging/beehive/teams/platform-core/experiments/test-releases/-/jobs/6480923815#L70))
	at org.jreleaser.workflow.AbstractWorkflowItem.invoke(AbstractWorkflowItem.java:43)
	at org.jreleaser.workflow.WorkflowImpl.doExecute(WorkflowImpl.java:129)
	at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:54)
	at org.jreleaser.cli.FullRelease.doExecute(FullRelease.java:219)
	at org.jreleaser.cli.AbstractModelCommand.execute(AbstractModelCommand.java:89)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:52)
	at org.jreleaser.cli.AbstractModelCommand.call(AbstractModelCommand.java:53)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:22[73](https://gitlab.com/sinch/sinch-projects/enterprise-and-messaging/beehive/teams/platform-core/experiments/test-releases/-/jobs/6480923815#L73))
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.jreleaser.cli.Main.execute(Main.java:98)
	at org.jreleaser.cli.Main.run(Main.java:[81](https://gitlab.com/sinch/sinch-projects/enterprise-and-messaging/beehive/teams/platform-core/experiments/test-releases/-/jobs/6480923815#L81))
	at org.jreleaser.cli.Main.main(Main.java:70)
Caused by: java.lang.ClassNotFoundException: java.rmi.UnexpectedException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 34 more
```

Listing Java modules available from the JR packaged in the Docker image results in

```
java.base@17.0.2
java.datatransfer@17.0.2
java.desktop@17.0.2
java.logging@17.0.2
java.management@17.0.2
java.naming@17.0.2
java.prefs@17.0.2
java.scripting@17.0.2
java.security.jgss@17.0.2
java.security.sasl@17.0.2
java.sql@17.0.2
java.transaction.xa@17.0.2
java.xml@17.0.2
jdk.crypto.cryptoki@17.0.2
jdk.crypto.ec@17.0.2
jdk.localedata@17.0.2
jdk.net@17.0.2
jdk.security.auth@17.0.2
jdk.security.jgss@17.0.2
```

`java.rmi` is clearly missing.

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.12.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.12.0))
