### ISSUE TITLE
Maven Central verification fails for relocated artifact

### ISSUE THREAD

**Issue by filiphr** [jreleaser/jreleaser#1654]
I've been trying to setup JReleaser for [MapStruct](https://github.com/mapstruct/mapstruct). However, I hit some hurdles. I've used [Moditect](https://github.com/moditect/moditect) as an inspiration for setting it up.

There seems to be an issue with the Maven Deployer validation. In MapStruct we have an artifact that has been relocated. i.e. it has:

```xml
<distributionManagement>
    <relocation>
        <artifactId>mapstruct</artifactId>
    </relocation>
</distributionManagement>
```

This artifact does not have any javadoc or sources attached to it. This Maven Central allows deploying such an artifact. 

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Check out https://github.com/filiphr/mapstruct/tree/jreleaser
2. Run ` ./mvnw -ntp -B --file pom.xml -Ppublication,stage -Dmaven.site.skip=true -Drelease=true `
3. Run `./mvnw -ntp -B --file pom.xml -pl :mapstruct-parent -Pjreleaser jreleaser:release -Djreleaser.dry.run=true `

### Expected Behaviour

The maven central verification does not fail.

### Actual Behaviour

The maven central verification fails due to missing javadoc and sources artifacts

### Environment Information

- **Operating System**: macOS Sonoma 14.4.1
- **JReleaser Version:** 1.12.0
- **JDK Version:** 17.0.10

```
org.jreleaser.model.JReleaserException: Rules for publishing to Maven Central were not met
	at org.jreleaser.sdk.commons.AbstractMavenDeployer.collectDeployables(AbstractMavenDeployer.java:116)
	at org.jreleaser.sdk.nexus2.Nexus2MavenDeployer.deploy(Nexus2MavenDeployer.java:94)
	at org.jreleaser.engine.deploy.maven.ProjectMavenDeployer.deploy(ProjectMavenDeployer.java:55)
	at org.jreleaser.engine.deploy.maven.MavenDeployers.deploy(MavenDeployers.java:167)
	at org.jreleaser.engine.deploy.maven.MavenDeployers.doDeploy(MavenDeployers.java:150)
	at org.jreleaser.engine.deploy.maven.MavenDeployers.deploy(MavenDeployers.java:59)
	at org.jreleaser.workflow.DeployWorkflowItem.doInvoke(DeployWorkflowItem.java:35)
	at org.jreleaser.workflow.AbstractWorkflowItem.lambda$invoke$0(AbstractWorkflowItem.java:43)
	at org.jreleaser.engine.hooks.HookExecutor.execute(HookExecutor.java:70)
	at org.jreleaser.workflow.AbstractWorkflowItem.invoke(AbstractWorkflowItem.java:43)
	at org.jreleaser.workflow.WorkflowImpl.doExecute(WorkflowImpl.java:129)
	at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:54)
	at org.jreleaser.maven.plugin.JReleaserReleaseMojo.doExecute(JReleaserReleaseMojo.java:128)
	at org.jreleaser.maven.plugin.AbstractJReleaserMojo.execute(AbstractJReleaserMojo.java:109)
	at org.jreleaser.maven.plugin.JReleaserReleaseMojo.execute(JReleaserReleaseMojo.java:33)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:61)
```

**Comment by aalmiray** [comment]
Have you tried configuring `artifactOverrides` to skip sources and javadoc for that given artifact? https://github.com/jreleaser/jreleaser/discussions/1355#discussioncomment-5698440

**Comment by filiphr** [comment]
Seems like I've missed that option.  Using:

```xml
<artifactOverride>
    <groupId>org.mapstruct</groupId>
    <artifactId>mapstruct-jdk8</artifactId>
    <sourceJar>false</sourceJar>
    <javadocJar>false</javadocJar>
</artifactOverride>
```

works great. Thanks @aalmiray.

Should we close this or do you think that supporting relocation artifacts is something that JReleaser (I guess this is https://github.com/kordamp/pomchecker) should support?
