### ISSUE TITLE
[deploy] Zip artifact cannot be deployed

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1669]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Configure deployment for a pom file with `zip` packaging.
2. Attempt a deployment to GitHub

### Expected Behaviour

Deployment should work as expected.

### Actual Behaviour

An error occurs becuase Maven Central rules were not met

### Environment Information

- **Operating System**: N/A
- **JReleaser Version:** 1.12.0
- **JDK Version:** N/A

```
org.jreleaser.model.JReleaserException: Rules for publishing to Maven Central were not met
	at org.jreleaser.sdk.commons.AbstractMavenDeployer.collectDeployables(AbstractMavenDeployer.java:116)
	at org.jreleaser.sdk.commons.AbstractMavenDeployer.deployPackages(AbstractMavenDeployer.java:442)
	at org.jreleaser.sdk.github.GithubMavenDeployer.deploy(GithubMavenDeployer.java:60)
	at org.jreleaser.engine.deploy.maven.ProjectMavenDeployer.deploy(ProjectMavenDeployer.java:55)
	at org.jreleaser.engine.deploy.maven.MavenDeployers.deploy(MavenDeployers.java:167)
	at org.jreleaser.engine.deploy.maven.MavenDeployers.doDeploy(MavenDeployers.java:150)
	at org.jreleaser.engine.deploy.maven.MavenDeployers.deploy(MavenDeployers.java:59)
	at org.jreleaser.workflow.DeployWorkflowItem.doInvoke(DeployWorkflowItem.java:35)
	at org.jreleaser.workflow.AbstractWorkflowItem.lambda$invoke$0(AbstractWorkflowItem.java:43)
	at org.jreleaser.engine.hooks.HookExecutor.execute(HookExecutor.java:70)
	at org.jreleaser.workflow.AbstractWorkflowItem.invoke(AbstractWorkflowItem.java:43)
	at org.jreleaser.workflow.WorkflowImpl.doExecute(WorkflowImpl.java:129)
	at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:54)
	at org.jreleaser.cli.Deploy.doExecute(Deploy.java:104)
	at org.jreleaser.cli.AbstractModelCommand.execute(AbstractModelCommand.java:89)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:52)
	at org.jreleaser.cli.AbstractModelCommand.call(AbstractModelCommand.java:53)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.jreleaser.cli.Main.execute(Main.java:98)
	at org.jreleaser.cli.Main.run(Main.java:81)
	at org.jreleaser.cli.Main.main(Main.java:70)
```

cc: @lagergren

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.13.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.13.0))
