### ISSUE TITLE
[deploy] NPE when reading response after uploading a file

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#1677]
@evanchooly found an NPE when publishing a snapshot version of Morphia via the Nexus2 deployer

```
Caused by: java.lang.NullPointerException
    at java.io.Reader.<init>(Reader.java:168)
    at java.io.InputStreamReader.<init>(InputStreamReader.java:112)
    at org.jreleaser.sdk.commons.ClientUtils.uploadFile(ClientUtils.java:318)
    at org.jreleaser.sdk.commons.ClientUtils.putFile(ClientUtils.java:251)
    at org.jreleaser.sdk.nexus2.Nexus2.deploy(Nexus2.java:288)
    at org.jreleaser.sdk.nexus2.Nexus2MavenDeployer.uploadArtifacts(Nexus2MavenDeployer.java:241)
    at org.jreleaser.sdk.nexus2.Nexus2MavenDeployer.deploy(Nexus2MavenDeployer.java:158)
    ...
```

Connection from the server may have been severed before the error stream could be read.

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.13.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.13.0))
