### ISSUE TITLE
Cryptical NPE when running `jreleaser deploy --dry-run`

### ISSUE THREAD

**Issue by gastaldi** [jreleaser/jreleaser#1748]
I'd like to validate if the repository content is "Maven Central-ready" before the release prepare is called, so that validation errors can be detected BEFORE performing the release.   

I created a reproducer that can be executed locally: [Archive.zip](https://github.com/user-attachments/files/17452517/Archive.zip)

When I call `jreleaser deploy --dry-run` I get a cryptic output (Same when running `jbang jreleaser-snapshot@jreleaser deploy --dry-run`): 

```java
org.jreleaser.model.JReleaserException: JReleaser has not been properly configured.
java.lang.NullPointerException: Cannot invoke "org.jreleaser.model.internal.release.BaseReleaser.getServiceName()" because "service" is null

	at org.jreleaser.engine.context.ModelValidator.validate(ModelValidator.java:65)
	at org.jreleaser.workflow.WorkflowImpl.<init>(WorkflowImpl.java:47)
	at org.jreleaser.workflow.Workflows.deploy(Workflows.java:74)
	at org.jreleaser.cli.Deploy.doExecute(Deploy.java:105)
	at org.jreleaser.cli.AbstractModelCommand.execute(AbstractModelCommand.java:90)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:52)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at org.jreleaser.cli.Main.execute(Main.java:98)
	at org.jreleaser.cli.Main.run(Main.java:81)
	at org.jreleaser.cli.Main.main(Main.java:70)
```

I'm missing some settings, but I have no idea what's missing.

**Comment by aalmiray** [comment]
I believe the expectation is to resolve a releaser by default. It may be the case the validator has enough information to figure out if the releaser is needed at all.

**Comment by gastaldi** [comment]
The stacktrace above disappears if I add `sign: false` to the deploy, but I think it's worth reporting here if we could make it less cryptic: 

```yaml
project:
  description: Quarkiverse Deployment
  copyright: Copyright(C) 2024 - Red Hat
  java:
    groupId: io.quarkiverse

signing:
  verify: false

deploy:
  maven:
    pomchecker:
      failOnWarning: false
    nexus2:
      maven-central:
        active: ALWAYS
        url: https://s01.oss.sonatype.org/service/local
        snapshotUrl: https://s01.oss.sonatype.org/content/repositories/snapshots/
        closeRepository: true
        releaseRepository: true
        stagingProfileId: 166ff053e5f61f
        username: foo
        password: bar
        sign: false
        stagingRepositories:
          - ./repository
```

**Comment by aalmiray** [comment]
Signing must be enabled. See instructions at https://jreleaser.org/guide/latest/examples/maven/maven-central.html

**Comment by aalmiray** [comment]
Do you have a copy of the `trace.log`? Looks to me that validation of the signing block was skipped, otherwise an error should had appeared earlier stating signing secrets/keys were missing or invalid.

**Comment by gastaldi** [comment]
```
[INFO]  JReleaser 1.15.0-SNAPSHOT
------------------------------------------------------------
jreleaser 1.15.0-SNAPSHOT
------------------------------------------------------------
Build time:   2024-10-23 12:15:13+02:00
Revision:     778cedc90b9fd283a5e20a0ed4b63b4b9084229b
JVM:          23 (Eclipse Adoptium 23+37)
------------------------------------------------------------
[INFO]  Configuring with jreleaser.yml
[INFO]    - basedir set to /Users/ggastald/Downloads/jreleaser
[INFO]    - outputdir set to /Users/ggastald/Downloads/jreleaser/out/jreleaser
[INFO]  Reading configuration
[DEBUG]   - basedir set to /Users/ggastald/Downloads/jreleaser
[DEBUG]   - baseOutputDirectory set to /Users/ggastald/Downloads/jreleaser/out
[DEBUG]   - outputDirectory set to /Users/ggastald/Downloads/jreleaser/out/jreleaser
[DEBUG]   - checksumDirectory set to /Users/ggastald/Downloads/jreleaser/out/jreleaser/checksums
[DEBUG]   - catalogsDirectory set to /Users/ggastald/Downloads/jreleaser/out/jreleaser/catalogs
[DEBUG]   - signaturesDirectory set to /Users/ggastald/Downloads/jreleaser/out/jreleaser/signatures
[DEBUG]   - prepareDirectory set to /Users/ggastald/Downloads/jreleaser/out/jreleaser/prepare
[DEBUG]   - packageDirectory set to /Users/ggastald/Downloads/jreleaser/out/jreleaser/package
[DEBUG]   - downloadDirectory set to /Users/ggastald/Downloads/jreleaser/out/jreleaser/download
[DEBUG]   - assembleDirectory set to /Users/ggastald/Downloads/jreleaser/out/jreleaser/assemble
[DEBUG]   - artifactsDirectory set to /Users/ggastald/Downloads/jreleaser/out/jreleaser/artifacts
[DEBUG]   - deployDirectory set to /Users/ggastald/Downloads/jreleaser/out/jreleaser/deploy
[INFO]  git-root-search set to false
[INFO]  Loading variables from /Users/ggastald/.jreleaser/config.properties
[WARN]  Variables source /Users/ggastald/.jreleaser/config.properties does not exist
[INFO]  Loading variables from /Users/ggastald/Downloads/jreleaser/.env
[DEBUG] The following variables are defined in .env:
[DEBUG]   JRELEASER_PROJECT_NAME
[DEBUG]   JRELEASER_PROJECT_VERSION
[INFO]  Validating configuration
[INFO]  Strict mode set to false
[DEBUG]   [validation] --== DEPLOY ==--
[DEBUG]   [validation] hooks
[DEBUG]   [validation] hooks.command
[DEBUG]   [validation] - disabled
[DEBUG]   [validation] hooks.script
[DEBUG]   [validation] - disabled
[DEBUG]   [validation] - disabled
[DEBUG]   [validation] project
[DEBUG]   [validation] project.java
[DEBUG]   [validation] download
[DEBUG]   [validation] catalog.swid
[DEBUG]   [validation] assemble
[DEBUG]   [validation] - disabled
[DEBUG]   [validation] signing
[DEBUG]   [validation] - disabled
[DEBUG]   [validation] checksum
[DEBUG]   [validation] deploy
[DEBUG]   [validation] deploy.maven
[DEBUG]   [validation] deploy.maven.nexus2
[DEBUG]   [validation] deploy.maven.nexus2.maven-central
[DEBUG]   [validation] upload
[DEBUG]   [validation] catalog
[DEBUG]   [validation] catalog.sbom
[DEBUG]   [validation] catalog.sbom.cyclonedx
[DEBUG]   [validation] - disabled
[DEBUG]   [validation] catalog.sbom.syft
[DEBUG]   [validation] - disabled
[DEBUG]   [validation] catalog.github
[DEBUG]   [validation] - disabled
[DEBUG]   [validation] catalog.slsa
[DEBUG]   [validation] - disabled
[DEBUG]   [validation] announce
[DEBUG]   [validation] - disabled
[DEBUG]   [postvalidation] project
environment:
 
hooks:
    enabled: false
    active: NEVER
    command:
        enabled: false
        active: NEVER
    script:
        enabled: false
        active: NEVER
 
project:
    name: Quarkiverse Deployment
    version: 1.0.0
    versionPattern: SEMVER
    snapshot:
        enabled: false
        pattern: .*-SNAPSHOT
        label: early-access
        fullChangelog: false
    description: Quarkiverse Deployment
    copyright: Copyright(C) 2024 - Red Hat
    stereotype: NONE
    java:
        enabled: true
        groupId: io.quarkiverse
        artifactId: Quarkiverse Deployment
        jvmOptions:
        environmentVariables:
        multiProject: false
 
platform:
 
 
checksum:
    name: checksums.txt
    individual: false
    algorithms:
        SHA_256
    artifacts: true
    files: true
 
signing:
    enabled: false
    active: NEVER
    armored: false
    verify: false
    artifacts: true
    files: true
    checksums: true
    catalogs: true
    passphrase: **unset**
    publicKey: **unset**
    secretKey: **unset**
 
announce:
    enabled: true
    article:
        enabled: false
        commitAuthor:
        repository:
            enabled: false
            name: article
            token: **unset**
    bluesky:
        enabled: false
        handle: **unset**
        password: **unset**
    discord:
        enabled: false
        webhook: **unset**
    discourse:
        enabled: false
        apiKey: **unset**
        username: **unset**
    discussions:
        enabled: false
    gitter:
        enabled: false
        webhook: **unset**
    googlechat:
        enabled: false
        webhook: **unset**
    linkedin:
        enabled: false
        owner: **unset**
        accessToken: **unset**
    smtp:
        enabled: false
        auth: false
        password: **unset**
    mastodon:
        enabled: false
        accessToken: **unset**
    mattermost:
        enabled: false
        webhook: **unset**
        structuredMessage: true
    opencollective:
        enabled: false
        token: **unset**
    sdkman:
        enabled: false
        consumerKey: **unset**
        consumerToken: **unset**
    slack:
        enabled: false
        webhook: **unset**
        token: **unset**
    teams:
        enabled: false
        webhook: **unset**
    telegram:
        enabled: false
        token: **unset**
        chatId: **unset**
    twitter:
        enabled: false
        consumerKey: **unset**
        consumerSecret: **unset**
        accessToken: **unset**
        accessTokenSecret: **unset**
    zulip:
        enabled: false
        apiKey: **unset**
 
packagers:
    appimage:
        enabled: false
        continueOnError: false
        commitAuthor:
        requiresTerminal: false
        repository:
            enabled: false
            name: appimage
            token: **unset**
    asdf:
        enabled: false
        continueOnError: false
        commitAuthor:
        repository:
            enabled: false
            name: asdf
            token: **unset**
    brew:
        enabled: false
        continueOnError: false
        commitAuthor:
        multiPlatform: false
        repository:
            enabled: false
            name: homebrew-tap
            token: **unset**
        cask:
            enabled: false
    chocolatey:
        enabled: false
        continueOnError: false
        commitAuthor:
        apiKey: **unset**
        remoteBuild: false
        repository:
            enabled: false
            name: chocolatey-bucket
            token: **unset**
    docker:
        enabled: false
        useLocalArtifact: true
        buildx:
            enabled: false
            createBuilder: true
        commitAuthor:
        repository:
            enabled: false
            name: docker
            token: **unset**
            versionedSubfolders: false
        continueOnError: false
    flatpak:
        enabled: false
        continueOnError: false
        commitAuthor:
        repository:
            enabled: false
            name: flatpak
            token: **unset**
    gofish:
        enabled: false
        continueOnError: false
        commitAuthor:
        repository:
            enabled: false
            name: fish-food
            token: **unset**
    jbang:
        enabled: false
        continueOnError: false
        commitAuthor:
        repository:
            enabled: false
            name: jbang-catalog
            token: **unset**
    jib:
        enabled: false
        commitAuthor:
        repository:
            enabled: false
            name: jib
            token: **unset**
            versionedSubfolders: false
        continueOnError: false
    macports:
        enabled: false
        continueOnError: false
        commitAuthor:
        repository:
            enabled: false
            name: macports
            token: **unset**
    scoop:
        enabled: false
        continueOnError: false
        commitAuthor:
        repository:
            enabled: false
            name: scoop
            token: **unset**
    sdkman:
        enabled: false
        continueOnError: false
        connectTimeout: 0
        readTimeout: 0
        consumerKey: **unset**
        consumerToken: **unset**
    snap:
        enabled: false
        continueOnError: false
        commitAuthor:
        remoteBuild: false
        repository:
            enabled: false
            name: snap
            token: **unset**
    spec:
        enabled: false
        continueOnError: false
        commitAuthor:
        repository:
            enabled: false
            name: spec
            token: **unset**
    winget:
        enabled: false
        continueOnError: false
        commitAuthor:
        package:
        publisher:
        installer:
            type: WIX
            scope: MACHINE
            upgradeBehavior: INSTALL
            dependencies:
        repository:
            enabled: false
            name: winget
            token: **unset**
 
download:
    enabled: true
 
assemble:
    enabled: true
 
deploy:
    enabled: true
    active: ALWAYS
    maven:
        enabled: true
        active: ALWAYS
        pomchecker:
            version: 1.14.0
            failOnWarning: false
            failOnError: true
        nexus2:
            maven-central:
                enabled: true
                active: ALWAYS
                connectTimeout: 20
                readTimeout: 60
                authorization: BASIC
                url: https://s01.oss.sonatype.org/service/local
                username: ************
                password: ************
                sign: true
                checksums: true
                sourceJar: true
                javadocJar: true
                verifyPom: true
                applyMavenCentralRules: true
                snapshotSupported: true
                stagingRepositories:
                    ./repository
                verifyUrl: https://repo1.maven.org/maven2/{{path}}/{{filename}}
                snapshotUrl: https://s01.oss.sonatype.org/content/repositories/snapshots/
                closeRepository: true
                releaseRepository: true
                transitionDelay: 10
                transitionMaxRetries: 60
                stagingProfileId: 166ff053e5f61f
 
upload:
    enabled: true
 
catalog:
    enabled: true
    github:
        enabled: false
        active: NEVER
        artifacts: true
        files: true
        deployables: true
    sbom:
        enabled: true
        cyclonedx:
            enabled: false
            active: NEVER
            distributions: false
            files: false
            pack:
                enabled: false
        syft:
            enabled: false
            active: NEVER
            distributions: false
            files: false
            pack:
                enabled: false
    slsa:
        enabled: false
        active: NEVER
        artifacts: true
        files: true
        deployables: true
    swid:
        enabled: false
        name: swid-tag
        corpus: false
        patch: false
 
[INFO]  Project version set to 1.0.0
[INFO]  Release is not snapshot
[INFO]  Timestamp is 2024-10-23T11:38:42.105522-03:00
[INFO]  Platform is osx-aarch_64
[DEBUG] loading extension default-jreleaser-mustache:org.jreleaser.extensions.internal.mustache.DefaultMustacheExtension
[DEBUG] adding org.jreleaser.extensions.internal.mustache.DefaultMustacheExtensionPoint from default-jreleaser-mustache extension
[INFO]  dry-run set to true
[INFO]  Deploying Maven artifacts
[INFO]    [maven] Deploying all staged artifacts
[INFO]      [nexus2] Deploying to maven-central
[INFO]      [nexus2] nexus2 set to FULL_DEPLOYMENT
[DEBUG]     [nexus2] stagingProfileId set to 166ff053e5f61f
[INFO]      [nexus2] Verifying prerequisites
[INFO]      [nexus2] Verifying POMs
[DEBUG]     [nexus2] ------------------------------------------------------------
[DEBUG]     [nexus2] pomchecker 1.14.0
[DEBUG]     [nexus2] ------------------------------------------------------------
[DEBUG]     [nexus2] Build timestamp: 2024-10-23T08:22:02Z
[DEBUG]     [nexus2] Revision:        33edbd4b8e7f5c5b95d61852ca0b99d6e13dce10
[DEBUG]     [nexus2] JVM:             23 (Eclipse Adoptium 23+37)
[DEBUG]     [nexus2] ------------------------------------------------------------
[DEBUG]     [nexus2] Verifying /Users/ggastald/Downloads/jreleaser/repository/io/quarkiverse/reactivemessaging/nats-jetstream/relocations-parent/3.15.7/relocations-parent-3.15.7.pom
[DEBUG]     [nexus2] Verifying /Users/ggastald/Downloads/jreleaser/repository/io/quarkiverse/reactivemessaging/nats-jetstream/quarkus-messaging-nats-jetstream-parent/3.15.7/quarkus-messaging-nats-jetstream-parent-3.15.7.pom
[DEBUG]     [nexus2] Verifying /Users/ggastald/Downloads/jreleaser/repository/io/quarkiverse/reactivemessaging/nats-jetstream/quarkus-messaging-nats-jetstream/3.15.7/quarkus-messaging-nats-jetstream-3.15.7.pom
[DEBUG]     [nexus2] Verifying /Users/ggastald/Downloads/jreleaser/repository/io/quarkiverse/reactivemessaging/nats-jetstream/quarkus-reactive-messsaging-nats-jetstream-parent/3.15.7/quarkus-reactive-messsaging-nats-jetstream-parent-3.15.7.pom
[DEBUG]     [nexus2] Verifying /Users/ggastald/Downloads/jreleaser/repository/io/quarkiverse/reactivemessaging/nats-jetstream/quarkus-messaging-nats-jetstream-deployment/3.15.7/quarkus-messaging-nats-jetstream-deployment-3.15.7.pom
[DEBUG]     [nexus2] Verifying /Users/ggastald/Downloads/jreleaser/repository/io/quarkiverse/reactivemessaging/nats-jetstream/quarkus-reactive-messaging-nats-jetstream-deployment/3.15.7/quarkus-reactive-messaging-nats-jetstream-deployment-3.15.7.pom
[DEBUG]     [nexus2] Verifying /Users/ggastald/Downloads/jreleaser/repository/io/quarkiverse/reactivemessaging/nats-jetstream/quarkus-reactive-messsaging-nats-jetstream/3.15.7/quarkus-reactive-messsaging-nats-jetstream-3.15.7.pom
[INFO]  Writing output properties to out/jreleaser/output.properties
[ERROR] JReleaser failed after 5.372 s
java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because the return value of "org.jreleaser.model.internal.signing.Signing.getSecretKey()" is null
	at org.jreleaser.model.internal.JReleaserContext.createKeyring(JReleaserContext.java:1056)
	at org.jreleaser.model.internal.JReleaserContext$1.createKeyring(JReleaserContext.java:382)
	at org.jreleaser.sdk.signing.SigningUtils.getPublicKeyID(SigningUtils.java:82)
	at org.jreleaser.sdk.commons.AbstractMavenDeployer.verifyKeyIsValid(AbstractMavenDeployer.java:421)
	at org.jreleaser.sdk.commons.AbstractMavenDeployer.signDeployables(AbstractMavenDeployer.java:368)
	at org.jreleaser.sdk.commons.AbstractMavenDeployer.collectDeployables(AbstractMavenDeployer.java:131)
	at org.jreleaser.sdk.nexus2.Nexus2MavenDeployer.deploy(Nexus2MavenDeployer.java:96)
	at org.jreleaser.engine.deploy.maven.ProjectMavenDeployer.deploy(ProjectMavenDeployer.java:55)
	at org.jreleaser.engine.deploy.maven.MavenDeployers.deploy(MavenDeployers.java:167)
	at org.jreleaser.engine.deploy.maven.MavenDeployers.doDeploy(MavenDeployers.java:150)
	at org.jreleaser.engine.deploy.maven.MavenDeployers.deploy(MavenDeployers.java:59)
	at org.jreleaser.workflow.DeployWorkflowItem.doInvoke(DeployWorkflowItem.java:35)
	at org.jreleaser.workflow.AbstractWorkflowItem.lambda$invoke$0(AbstractWorkflowItem.java:43)
	at org.jreleaser.engine.hooks.HookExecutor.execute(HookExecutor.java:70)
	at org.jreleaser.workflow.AbstractWorkflowItem.invoke(AbstractWorkflowItem.java:43)
	at org.jreleaser.workflow.WorkflowImpl.doExecute(WorkflowImpl.java:129)
	at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:54)
	at org.jreleaser.cli.Deploy.doExecute(Deploy.java:105)
	at org.jreleaser.cli.AbstractModelCommand.execute(AbstractModelCommand.java:90)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:52)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at org.jreleaser.cli.Main.execute(Main.java:98)
	at org.jreleaser.cli.Main.run(Main.java:81)
	at org.jreleaser.cli.Main.main(Main.java:70)
	at jreleaser_snapshot.main(jreleaser_snapshot.java:9)
```

**Comment by aalmiray** [comment]
Signing was disabled for sure as witnessed by

```
[DEBUG]   [validation] signing
[DEBUG]   [validation] - disabled
```

And the resolved model

```
signing:
    enabled: false
    active: NEVER
    armored: false
    verify: false
    artifacts: true
    files: true
    checksums: true
    catalogs: true
    passphrase: **unset**
    publicKey: **unset**
    secretKey: **unset**
```

This shows no secrets were defined as they appear as `**unset**`. The minimum settings for publishing to Maven Central require

```
signing:
  active: ALWAYS
  armored: true
```

As shown in the guide https://jreleaser.org/guide/latest/examples/maven/maven-central.html

The error message should not have been an NPE but a more concrete message. Fixing it shortly.

**Comment by aalmiray** [comment]
🎉 This issue has been resolved in `v1.15.0` ([Release Notes](https://github.com/jreleaser/jreleaser/releases/tag/v1.15.0))
