### ISSUE TITLE
bluesky exception / doc not clear

### ISSUE THREAD

**Issue by maxandersen** [jreleaser/jreleaser#1766]
was doing jbang release for first time with bluesky announcer and hit two things:

error shown was:

`jreleaser.shadow.org.jreleaser.sdk.bluesky.BlueskyException: Bluesky operation failed` which wasn't that helpful i github action logs.

Reproducing locally trace.log gave me this:

```
org.jreleaser.sdk.commons.RestAPIException: 401: Unauthorized
	at org.jreleaser.sdk.commons.ClientUtils.lambda$builder$1(ClientUtils.java:120)
	at feign.InvocationContext.decodeError(InvocationContext.java:133)
	at feign.InvocationContext.proceed(InvocationContext.java:80)
	at feign.RedirectionInterceptor.intercept(RedirectionInterceptor.java:46)
	at feign.ResponseInterceptor.lambda$apply$2(ResponseInterceptor.java:68)
	at feign.ResponseHandler.handleResponse(ResponseHandler.java:69)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:109)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:53)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:104)
	at jdk.proxy2/jdk.proxy2.$Proxy19.createSession(Unknown Source)
	at org.jreleaser.sdk.bluesky.BlueskySdk.createSession(BlueskySdk.java:105)
	at org.jreleaser.sdk.bluesky.BlueskySdk.lambda$skeet$0(BlueskySdk.java:87)
	at org.jreleaser.sdk.bluesky.BlueskySdk.wrap(BlueskySdk.java:110)
	at org.jreleaser.sdk.bluesky.BlueskySdk.skeet(BlueskySdk.java:86)
	at org.jreleaser.sdk.bluesky.BlueskyAnnouncer.announce(BlueskyAnnouncer.java:106)
	at org.jreleaser.engine.announce.Announcers.announce(Announcers.java:127)
	at org.jreleaser.engine.announce.Announcers.announce(Announcers.java:89)
	at org.jreleaser.workflow.AnnounceWorkflowItem.doInvoke(AnnounceWorkflowItem.java:35)
	at org.jreleaser.workflow.AbstractWorkflowItem.lambda$invoke$0(AbstractWorkflowItem.java:43)
	at org.jreleaser.engine.hooks.HookExecutor.execute(HookExecutor.java:70)
	at org.jreleaser.workflow.AbstractWorkflowItem.invoke(AbstractWorkflowItem.java:43)
	at org.jreleaser.workflow.WorkflowImpl.doExecute(WorkflowImpl.java:129)
	at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:54)
	at org.jreleaser.cli.Announce.doExecute(Announce.java:83)
	at org.jreleaser.cli.AbstractModelCommand.execute(AbstractModelCommand.java:90)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:52)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at org.jreleaser.cli.Main.execute(Main.java:98)
	at org.jreleaser.cli.Main.run(Main.java:81)
	at org.jreleaser.cli.Main.main(Main.java:70)
	at jreleaser.main(jreleaser.java:8)
```

It would have been great if the error message would have included that was a auth issue and not some other arbitrary error.

Doc require handle - but does not say it excludes the `@` part, i.e. `jbang.dev` instead of `@jbang.dev`

Finally, would be great to mention to use app specific password from bluesky.

**Comment by TomCools** [comment]
@aalmiray, I'll make a PR to improve these things tonight.
