### ISSUE TITLE
[model] Cannot parse version '2021.06.05'

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#202]
https://github.com/sormuras/modules/runs/2753660171?check_suite_focus=true#step:6:43

```
java.lang.IllegalArgumentException: Cannot parse version '2021.06.05'
	at jreleaser.shadow.org.jreleaser.util.Version.of(Version.java:194)
	at jreleaser.shadow.org.jreleaser.engine.context.ContextCreator.parseVersion(ContextCreator.java:95)
	at jreleaser.shadow.org.jreleaser.engine.context.ContextCreator.report(ContextCreator.java:86)
	at jreleaser.shadow.org.jreleaser.engine.context.ContextCreator.create(ContextCreator.java:66)
	at jreleaser.shadow.org.jreleaser.engine.context.ModelAutoConfigurer.createAutoConfiguredContext(ModelAutoConfigurer.java:234)
	at jreleaser.shadow.org.jreleaser.engine.context.ModelAutoConfigurer.autoConfigure(ModelAutoConfigurer.java:230)
	at jreleaser.shadow.org.jreleaser.cli.Release.execute(Release.java:161)
	at jreleaser.shadow.org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:76)
	at jreleaser.shadow.org.jreleaser.cli.AbstractModelCommand.call(AbstractModelCommand.java:38)
	at jreleaser.shadow.org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:37)
	at jreleaser.shadow.picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at jreleaser.shadow.picocli.CommandLine.access$1300(CommandLine.java:145)
	at jreleaser.shadow.picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at jreleaser.shadow.picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at jreleaser.shadow.picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at jreleaser.shadow.picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at jreleaser.shadow.picocli.CommandLine.execute(CommandLine.java:2078)
	at jreleaser.shadow.org.jreleaser.cli.Main.execute(Main.java:73)
	at jreleaser.shadow.org.jreleaser.cli.Main.run(Main.java:69)
	at org.jreleaser.tool.JReleaser.main(JReleaser.java:45)
```

Found by @sormuras

**Comment by aalmiray** [comment]
The input string `2021.06.05` does not match semver. JReleaser expects a version that follows semver. Perhaps a setting to disable this check is required,
