### ISSUE TITLE
[release] `IndexOutOfBoundsException` when generating changelog

### ISSUE THREAD

**Issue by sormuras** [jreleaser/jreleaser#203]
https://github.com/sormuras/modules/runs/2755690715?check_suite_focus=true#step:6:50

```
[INFO]  JReleaser 0.5.0-SNAPSHOT
[INFO]  Auto configure is ON
[INFO]    - basedir set to /home/runner/work/modules/modules
[INFO]    - project.name: com.github.sormuras.modules
[INFO]    - project.version: 2021.06.06
[INFO]    - project.version.pattern: java-module
[INFO]    - release.tagName: 2021.06.06
[INFO]    - release.update: true
[INFO]  Loading properties from /home/runner/.jreleaser/config.properties
[WARN]  Properties source /home/runner/.jreleaser/config.properties does not exist
[INFO]  Validating configuration
[INFO]  Project version set to 2021.06.06
[INFO]  Release is not snapshot
[INFO]  Timestamp is 2021-06-06T04:12:21.49123915Z
[INFO]  HEAD is at 04d9a1c
[INFO]  dryrun set to false
java.lang.IndexOutOfBoundsException: No group 1
	at java.base/java.util.regex.Matcher.group(Matcher.java:646)
	at jreleaser.shadow.org.jreleaser.sdk.git.ChangelogGenerator.javaModuleVersionOf(ChangelogGenerator.java:141)
	at jreleaser.shadow.org.jreleaser.sdk.git.ChangelogGenerator.version(ChangelogGenerator.java:159)
	at jreleaser.shadow.org.jreleaser.sdk.git.ChangelogGenerator.resolveCommits(ChangelogGenerator.java:228)
	at jreleaser.shadow.org.jreleaser.sdk.git.ChangelogGenerator.createChangelog(ChangelogGenerator.java:88)
	at jreleaser.shadow.org.jreleaser.sdk.git.ChangelogGenerator.generate(ChangelogGenerator.java:72)
	at jreleaser.shadow.org.jreleaser.sdk.git.ChangelogProvider.resolveChangelog(ChangelogProvider.java:74)
	at jreleaser.shadow.org.jreleaser.sdk.git.ChangelogProvider.getChangelog(ChangelogProvider.java:39)
	at jreleaser.shadow.org.jreleaser.engine.changelog.Changelog.createChangelog(Changelog.java:35)
	at jreleaser.shadow.org.jreleaser.workflow.ChangelogWorkflowItem.invoke(ChangelogWorkflowItem.java:30)
	at jreleaser.shadow.org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:51)
	at jreleaser.shadow.org.jreleaser.cli.Release.doExecute(Release.java:201)
	at jreleaser.shadow.org.jreleaser.cli.Release.execute(Release.java:173)
	at jreleaser.shadow.org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:76)
	at jreleaser.shadow.org.jreleaser.cli.AbstractModelCommand.call(AbstractModelCommand.java:38)
	at jreleaser.shadow.org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:37)
	at jreleaser.shadow.picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at jreleaser.shadow.picocli.CommandLine.access$1300(CommandLine.java:145)
	at jreleaser.shadow.picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at jreleaser.shadow.picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at jreleaser.shadow.picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at jreleaser.shadow.picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at jreleaser.shadow.picocli.CommandLine.execute(CommandLine.java:2078)
	at jreleaser.shadow.org.jreleaser.cli.Main.execute(Main.java:73)
	at jreleaser.shadow.org.jreleaser.cli.Main.run(Main.java:69)
	at org.jreleaser.tool.JReleaser.main(JReleaser.java:45)
```

**Comment by aalmiray** [comment]
Could you print out the list of tags currently available at the local repository?

**Comment by aalmiray** [comment]
Checked out the project and ran it using the latest snapshot, can't get it to fail in the same way. Matter of fact, can't get it to fail at all

```
$ /tmp/jreleaser/jreleaser-0.5.0-SNAPSHOT/bin/jreleaser release --auto-config --project-version 2021.06.05 --tag-name 2021.06.05 --project-version-pattern java_module --project-name com.github.sormuras.modules --update -y
jreleaser 0.5.0-SNAPSHOT. Consider becoming a patron at https://www.patreon.com/aalmiray
[INFO]  JReleaser 0.5.0-SNAPSHOT
[INFO]  Auto configure is ON
[INFO]    - basedir set to /private/tmp/modules
[INFO]    - project.name: com.github.sormuras.modules
[INFO]    - project.version: 2021.06.05
[INFO]    - project.version.pattern: java_module
[INFO]    - release.tagName: 2021.06.05
[INFO]    - release.update: true
[INFO]  Loading properties from /Users/aalmiray/.jreleaser/config.properties
[WARN]  Properties source /Users/aalmiray/.jreleaser/config.properties does not exist
[INFO]  Validating configuration
[INFO]  Project version set to 2021.06.05
[INFO]  Release is not snapshot
[INFO]  Timestamp is 2021-06-06T12:40:16.088+02:00
[INFO]  HEAD is at 04d9a1c
[INFO]  dryrun set to true
[INFO]  Generating changelog: out/jreleaser/release/CHANGELOG.md
[INFO]  Calculating checksums
[INFO]  No files configured for checksum. Skipping
[INFO]  Signing files
[INFO]  Signing is not enabled. Skipping
[INFO]  Uploading is not enabled. Skipping.
[INFO]  Releasing to https://github.com/sormuras/modules
[INFO]  Writing output properties to out/jreleaser/output.properties
[INFO]  JReleaser succeeded after 1.206 s
```

**Comment by aalmiray** [comment]
I think I have a clue of what might be the problem: the use `jreleaser/release-action` readme states

"Note the fetch-depth: 0 option on the Checkout workflow step. It is required for JReleaser to work properly. Without that, JReleaser might fail or behave incorrectly."

Which means the checkout block should look like

```
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
```

**Comment by pmverma** [comment]
I believe I am also having the same problem.
I have the following maven configuration

```
<plugin>
    <groupId>org.jreleaser</groupId>
    <artifactId>jreleaser-maven-plugin</artifactId>
    <version>0.4.0</version>
    <configuration>
        <jreleaser>
            <project>
                <java>
                    <mainClass>${start-class}</mainClass>
                </java>
                <website>https://example.com</website>
                <docsUrl>https://example.com</docsUrl>
                <license>Apache 2.0</license>
                <copyright>2021 Xyz</copyright>
                <authors>
                    <author>Author 1</author>
                </authors>
            </project>
            <release>
                <github>
                    <owner>pmverma</owner>
                    <overwrite>true</overwrite>
                    <tagName>v1.0.0</tagName>
                    <changelog>
                        <enabled>false</enabled>
                    </changelog>
                </github>
            </release>
            <distributions>
                <distribution>
                    <name>app</name>
                    <artifacts>
                        <artifact>
                            <path>
                                ${app.distribution.directory}/${project.artifactId}-${project.version}-linux.zip
                            </path>
                        </artifact>
                    </artifacts>
                </distribution>
            </distributions>
        </jreleaser>
    </configuration>
</plugin>
```

Even though the changelog is disabled, getting the following error.
```
Caused by: java.lang.IndexOutOfBoundsException: No group 1
    at java.util.regex.Matcher.group (Matcher.java:647)
    at org.jreleaser.sdk.git.ChangelogGenerator.versionOf (ChangelogGenerator.java:131)
    at org.jreleaser.sdk.git.ChangelogGenerator.lambda$resolveCommits$1 (ChangelogGenerator.java:146)
    at java.util.TimSort.countRunAndMakeAscending (TimSort.java:355)
    at java.util.TimSort.sort (TimSort.java:220)
    at java.util.Arrays.sort (Arrays.java:1515)
    at java.util.ArrayList.sort (ArrayList.java:1750)
    at org.jreleaser.sdk.git.ChangelogGenerator.resolveCommits (ChangelogGenerator.java:145)
    at org.jreleaser.sdk.git.ChangelogGenerator.createChangelog (ChangelogGenerator.java:86)
    at org.jreleaser.sdk.git.ChangelogGenerator.generate (ChangelogGenerator.java:70)
    at org.jreleaser.sdk.git.ChangelogProvider.resolveChangelog (ChangelogProvider.java:74)
    at org.jreleaser.sdk.git.ChangelogProvider.getChangelog (ChangelogProvider.java:39)
    at org.jreleaser.engine.changelog.Changelog.createChangelog (Changelog.java:35)
    at org.jreleaser.workflow.ChangelogWorkflowItem.invoke (ChangelogWorkflowItem.java:30)
    at org.jreleaser.workflow.WorkflowImpl.execute (WorkflowImpl.java:51)
    at org.jreleaser.maven.plugin.JReleaserFullReleaseMojo.execute (JReleaserFullReleaseMojo.java:48)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:39)
    at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:122)
    at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:61)
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

I have only two tags at both local & remote repository.

`1.0.0.-M1`
`v1.0.0`

I see a PR for this bug, is 0.50 release going to fix this?

**Comment by aalmiray** [comment]
Yes, the fix is already in place for `0.5.0`.

**Comment by aalmiray** [comment]
FWIW `1.0.0.-M1` does not comply with the semver spec but `1.0.0.M1` does. I think the code will accept `1.0.0-M1` as well.

**Comment by pmverma** [comment]
Thanks for the quick reply. It is `1.0.0-M1` actually, typo error.
