### ISSUE TITLE
Error parsing Java Version 1.8

### ISSUE THREAD

**Issue by javydreamercsw** [jreleaser/jreleaser#211]
### Steps to Reproduce

1. Set up a project with Java 1.8 configured as per https://github.com/jreleaser/jreleaser/discussions/210.
2. Run `mvn jreleaser:config`
3. See error.

### Expected Behaviour

Plugin work as expected.

### Actual Behaviour

IllegalArgumentException: Cannot parse version '1.'

### Environment Information

- **Operating System**: Mac OS Catalina 10.15.7
- **JReleaser Version:** 0.4.0
- **JDK Version:** 8

Here's the curated log:

```
[INFO]  JReleaser 0.4.0
------------------------------------------------------------
Build time:   2021-05-31 09:45:22Z
Revision:     b06c0dc89a0cabb2829220c5b1095554330c74cb
------------------------------------------------------------
[INFO]    - basedir set to /Users/javierortiz/Documents/XXX/automation-interface
[INFO]  Loading properties from /Users/javierortiz/.jreleaser/config.properties
[WARN]  Properties source /Users/javierortiz/.jreleaser/config.properties does not exist
[INFO]  Validating configuration
[DEBUG] adjusting distributions with assemblies
[DEBUG]   [validation] project
[DEBUG]   [validation] upload
[DEBUG]   [validation] artifactory
[DEBUG]   [validation] http
[DEBUG]   [validation] release
[DEBUG]   [validation] release.gitlab
java.lang.IllegalArgumentException: Cannot parse version '1.'
	at org.jreleaser.util.Version.of(Version.java:194)
	at org.jreleaser.model.GitService.props(GitService.java:546)
	at org.jreleaser.model.Gitlab.props(Gitlab.java:72)
	at org.jreleaser.model.GitService.getResolvedTagName(GitService.java:148)
	at org.jreleaser.model.validation.GitServiceValidator.validateGitService(GitServiceValidator.java:165)
	at org.jreleaser.model.validation.GitlabValidator.validateGitlab(GitlabValidator.java:33)
	at org.jreleaser.model.validation.ReleaseValidator.validateRelease(ReleaseValidator.java:41)
	at org.jreleaser.model.JReleaserModelValidator.validateModel(JReleaserModelValidator.java:59)
	at org.jreleaser.model.JReleaserModelValidator.validate(JReleaserModelValidator.java:47)
	at org.jreleaser.model.JReleaserContext.adjustDistributions(JReleaserContext.java:132)
	at org.jreleaser.model.JReleaserContext.validateModel(JReleaserContext.java:109)
	at org.jreleaser.engine.context.ModelConfigurer.configure(ModelConfigurer.java:76)
	at org.jreleaser.engine.context.ContextCreator.create(ContextCreator.java:64)
	at org.jreleaser.maven.plugin.AbstractJReleaserMojo.createContext(AbstractJReleaserMojo.java:114)
	at org.jreleaser.maven.plugin.JReleaserChangelogMojo.execute(JReleaserChangelogMojo.java:48)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[DEBUG]   [validation] project
[DEBUG]   [validation] checksum
[DEBUG]   [validation] signing
[DEBUG]   [validation] upload
[DEBUG]   [validation] artifactory
[DEBUG]   [validation] http
[DEBUG]   [validation] release
[DEBUG]   [validation] release.gitlab
java.lang.IllegalArgumentException: Cannot parse version '1.'
	at org.jreleaser.util.Version.of(Version.java:194)
	at org.jreleaser.model.GitService.props(GitService.java:546)
	at org.jreleaser.model.Gitlab.props(Gitlab.java:72)
	at org.jreleaser.model.GitService.getResolvedTagName(GitService.java:148)
	at org.jreleaser.model.validation.GitServiceValidator.validateGitService(GitServiceValidator.java:165)
	at org.jreleaser.model.validation.GitlabValidator.validateGitlab(GitlabValidator.java:33)
	at org.jreleaser.model.validation.ReleaseValidator.validateRelease(ReleaseValidator.java:41)
	at org.jreleaser.model.JReleaserModelValidator.validateModel(JReleaserModelValidator.java:59)
	at org.jreleaser.model.JReleaserModelValidator.validate(JReleaserModelValidator.java:47)
	at org.jreleaser.model.JReleaserContext.validateModel(JReleaserContext.java:113)
	at org.jreleaser.engine.context.ModelConfigurer.configure(ModelConfigurer.java:76)
	at org.jreleaser.engine.context.ContextCreator.create(ContextCreator.java:64)
	at org.jreleaser.maven.plugin.AbstractJReleaserMojo.createContext(AbstractJReleaserMojo.java:114)
	at org.jreleaser.maven.plugin.JReleaserChangelogMojo.execute(JReleaserChangelogMojo.java:48)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR] == JReleaser ==
[ERROR] java.lang.IllegalArgumentException: Cannot parse version '1.'
[ERROR] java.lang.IllegalArgumentException: Cannot parse version '1.'
project:
    name: XXX
    version: 5.0.7-SNAPSHOT
    snapshotPattern: .*-SNAPSHOT
    snapshot: true
    java:
        enabled: true
        version: 1.
        groupId: com.XXX.automation
        artifactId: automation-interface
        multiProject: false
 
release:
    gitlab:
        enabled: true
        host: gitlab.com
        owner: javierortiz
        name: XXX-5.0.7-SNAPSHOT
        username: javierortiz
        token: ************
        repoUrlFormat: https://{{repoHost}}/{{repoOwner}}/{{repoName}}
        repoCloneUrlFormat: https://{{repoHost}}/{{repoOwner}}/{{repoName}}.git
        commitUrlFormat: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/-/commits
        downloadUrlFormat: "https://{{repoHost}}/{{repoOwner}}/{{repoName}}/-/archive/v{{projectVersion}}/{{artifactFileName}}
        releaseNotesUrlFormat: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/-/releases/v{{projectVersion}}
        latestReleaseUrlFormat: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/-/releases/v{{projectVersion}}
        issueTrackerUrlFormat: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/-/issues
        tagName: v{{projectVersion}}
        releaseName: Release {{tagName}}
        branch: master
        commitAuthor:
            name: javierortiz
            email: javierortiz@email.com
        sign: false
        skipTag: false
        overwrite: true
        update: true
        apiEndpoint: https://gitlab.corp.XXX.com
        connectTimeout: 20
        readTimeout: 60
        changelog:
            enabled: true
            links: false
            sort: DESC
            formatted: always
            change: - {{commitShortHash}} {{commitTitle}}
            contentTemplate: src/main/resources/changelog.tpl
            hideUncategorized: false
            categories:
                title: 🚀 Features
                labels:
                    feature
                    enhancement
                title: 🐛 Bug Fixes
                labels:
                    fix
                    bug
            replacers:
                search: \[chore\]\s
                search: /P14C-(\d+)/g
                replace: https://jira.XXX.com/browse/P14C-$1
            labelers:
                label: issue
                title: ^fix:
                body: Fixes #
        milestone:
            name: {{tagName}}
            close: true
        identifier: 1861
 
checksum:
    name: checksums.txt
    individual: false
    algorithms:
        SHA_256
 
signing:
    enabled: false
    active: never
    armored: false
    publicKey: **unset**
    secretKey: **unset**
    passphrase: **unset**
 
announce:
    enabled: false
    discord:
        enabled: false
        connectTimeout: 0
        readTimeout: 0
        webhook: **unset**
    discussions:
        enabled: false
        connectTimeout: 0
        readTimeout: 0
    gitter:
        enabled: false
        connectTimeout: 0
        readTimeout: 0
        webhook: **unset**
    mail:
        enabled: false
        connectTimeout: 0
        readTimeout: 0
        auth: false
        password: **unset**
    mastodon:
        enabled: false
        connectTimeout: 0
        readTimeout: 0
        accessToken: **unset**
    mattermost:
        enabled: false
        connectTimeout: 0
        readTimeout: 0
        webhook: **unset**
    sdkman:
        enabled: false
        connectTimeout: 0
        readTimeout: 0
        consumerKey: **unset**
        consumerToken: **unset**
        major: true
    slack:
        enabled: false
        active: always
        connectTimeout: 20
        readTimeout: 60
        webhook: ************
        token: **unset**
        channel: #p14c-qa
        message: {{projectNameCapitalized}} {{projectVersion}} has been released! {{releaseNotesUrl}}
    teams:
        enabled: false
        connectTimeout: 0
        readTimeout: 0
        webhook: **unset**
    twitter:
        enabled: false
        connectTimeout: 0
        readTimeout: 0
        consumerKey: **unset**
        consumerSecret: **unset**
        accessToken: **unset**
        accessTokenSecret: **unset**
    zulip:
        enabled: false
        connectTimeout: 0
        readTimeout: 0
        apiKey: **unset**
 
packagers:
    brew:
        enabled: false
        commitAuthor:
        tap:
            name: homebrew-tap
            token: **unset**
    chocolatey:
        enabled: false
        commitAuthor:
        remoteBuild: false
        bucket:
            name: chocolatey-bucket
            token: **unset**
    docker:
        enabled: false
    jbang:
        enabled: false
        commitAuthor:
        catalog:
            name: jbang-catalog
            token: **unset**
    scoop:
        enabled: false
        commitAuthor:
        bucket:
            name: scoop
            token: **unset**
    snap:
        enabled: false
        commitAuthor:
        base: core20
        grade: stable
        confinement: strict
        remoteBuild: false
        snap:
            name: snap
            token: **unset**
 
assemble:
    enabled: false
 
upload:
    enabled: false
 
org.jreleaser.model.JReleaserException: JReleaser has not been properly configured.
	at org.jreleaser.engine.context.ModelConfigurer.configure(ModelConfigurer.java:89)
	at org.jreleaser.engine.context.ContextCreator.create(ContextCreator.java:64)
	at org.jreleaser.maven.plugin.AbstractJReleaserMojo.createContext(AbstractJReleaserMojo.java:114)
	at org.jreleaser.maven.plugin.JReleaserChangelogMojo.execute(JReleaserChangelogMojo.java:48)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

**Comment by aalmiray** [comment]
Does your `pom.xml` define any of the following properties:

* maven.compiler.release
* maven.compiler.target
* maven.compiler.source

**Comment by javydreamercsw** [comment]
In my case it was defined here:

```
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
```

**Comment by aalmiray** [comment]
I see. Properties set in the `<configuration>` block of the compiler plugin are not taken into account, for the time being.
