### ISSUE TITLE
[core] NFE parsing Java version running with a Panama build

### ISSUE THREAD

**Issue by gunnarmorling** [jreleaser/jreleaser#387]
Running with a Panama EA build yields this:

```
[INFO]  Writing output properties to out/jreleaser/output.properties
java.lang.NumberFormatException: For input string: "17-panama"
    at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
    at java.base/java.lang.Integer.parseInt(Integer.java:668)
    at java.base/java.lang.Integer.parseInt(Integer.java:786)
    at jreleaser.shadow.org.jreleaser.util.Version.javaMajorVersion(Version.java:132)
    at jreleaser.shadow.org.jreleaser.model.JReleaserContext$SortedProperties.entrySet(JReleaserContext.java:496)
    at java.base/java.util.Properties.store0(Properties.java:920)
    at java.base/java.util.Properties.store(Properties.java:906)
    at jreleaser.shadow.org.jreleaser.model.JReleaserContext.report(JReleaserContext.java:437)
    at jreleaser.shadow.org.jreleaser.cli.Config.doExecute(Config.java:43)
    at jreleaser.shadow.org.jreleaser.cli.AbstractModelCommand.execute(AbstractModelCommand.java:82)
    at jreleaser.shadow.org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:76)
    at jreleaser.shadow.org.jreleaser.cli.AbstractModelCommand.call(AbstractModelCommand.java:46)
    at jreleaser.shadow.org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:37)
    at jreleaser.shadow.picocli.CommandLine.executeUserObject(CommandLine.java:1953)
    at jreleaser.shadow.picocli.CommandLine.access$1300(CommandLine.java:145)
    at jreleaser.shadow.picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
    at jreleaser.shadow.picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
    at jreleaser.shadow.picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
    at jreleaser.shadow.picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
    at jreleaser.shadow.picocli.CommandLine.execute(CommandLine.java:2078)
    at jreleaser.shadow.org.jreleaser.cli.Main.execute(Main.java:73)
    at jreleaser.shadow.org.jreleaser.cli.Main.run(Main.java:69)
    at org.jreleaser.tool.JReleaser.main(JReleaser.java:45)
```

**Comment by aalmiray** [comment]
Looks like the regex that detects a valid Java version can't handle `${major}-${tag}`.

**Comment by aalmiray** [comment]
Right, do I think I lifted the regex from the official sources. @sormuras is my witness 😉

**Comment by sormuras** [comment]
Me? I didn't do anything! This time. 😛

**Comment by aalmiray** [comment]
@sormuras: You pointed me to the regex. Don't make me fetch the Slack logs, or so help me ... 😜

**Comment by sormuras** [comment]
I no see regex. I only see reg(ular)tex(t): https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/module/ModuleDescriptor.Version.html

**Comment by sormuras** [comment]
Beware: Java Runtime Version Syntax `!=` Java Module Version Syntax

**Comment by aalmiray** [comment]
JAVA_RUNTIME is not a supported version pattern besides SEMVER, JAVA_MODULE, and CUSTOM.
