### ISSUE TITLE
[changelog] RestAPIException when generating changelog

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#388]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Configure contributor formatting to pull in username
2. Generate the changelog invoking `jreleaser changelog`

### Expected Behaviour

Changelog created, no errors.

### Actual Behaviour

An exception might occur when resolving usernames

```
org.jreleaser.sdk.commons.RestAPIException
	at org.jreleaser.sdk.commons.ClientUtils.lambda$builder$1(ClientUtils.java:81)
	at feign.AsyncResponseHandler.handleResponse(AsyncResponseHandler.java:96)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
	at com.sun.proxy.$Proxy17.searchUser(Unknown Source)
	at org.jreleaser.sdk.github.XGithub.findUser(XGithub.java:90)
	at org.jreleaser.sdk.github.GithubReleaser.findUser(GithubReleaser.java:158)
	at org.jreleaser.sdk.git.ChangelogGenerator.lambda$formatContributors$17(ChangelogGenerator.java:360)
	at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:441)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.jreleaser.sdk.git.ChangelogGenerator.formatContributors(ChangelogGenerator.java:364)
	at org.jreleaser.sdk.git.ChangelogGenerator.formatChangelog(ChangelogGenerator.java:339)
	at org.jreleaser.sdk.git.ChangelogGenerator.createChangelog(ChangelogGenerator.java:102)
	at org.jreleaser.sdk.git.ChangelogGenerator.generate(ChangelogGenerator.java:77)
	at org.jreleaser.sdk.git.ChangelogProvider.resolveChangelog(ChangelogProvider.java:75)
	at org.jreleaser.sdk.git.ChangelogProvider.getChangelog(ChangelogProvider.java:40)
	at org.jreleaser.engine.changelog.Changelog.createChangelog(Changelog.java:36)
	at org.jreleaser.workflow.ChangelogWorkflowItem.invoke(ChangelogWorkflowItem.java:30)
	at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:51)
	at org.jreleaser.cli.Release.doExecute(Release.java:249)
	at org.jreleaser.cli.AbstractModelCommand.execute(AbstractModelCommand.java:82)
	at org.jreleaser.cli.Release.execute(Release.java:167)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:76)
	at org.jreleaser.cli.AbstractModelCommand.call(AbstractModelCommand.java:46)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.jreleaser.cli.Main.execute(Main.java:73)
	at org.jreleaser.cli.Main.run(Main.java:59)
	at org.jreleaser.cli.Main.main(Main.java:51)
```

### Environment Information

- **Operating System**: N/A
- **JReleaser Version:** 0.7.0
- **JDK Version:** N/A

**Comment by aalmiray** [comment]
Might be better to warn when such exception occurs and let execution continue.
Should this be configurable, i.e, `failOnError` ?

**Comment by aalmiray** [comment]
Failure to resolve a username is already logged in debug mode.
