### ISSUE TITLE
getCurrentUser(Unknown Source)

### ISSUE THREAD

**Issue by anyulled** [jreleaser/jreleaser#41]
There's an uncomprehensible exception when releasing with Gitlab, I've been looking at the code but I think we need better exception handling at [sdks/gitlab-java-sdk/src/main/java/org/jreleaser/sdk/gitlab/Gitlab.java](https://github.com/jreleaser/jreleaser/blob/main/sdks/gitlab-java-sdk/src/main/java/org/jreleaser/sdk/gitlab/Gitlab.java#L162)

I have a **JRELEASER_GITLAB_TOKEN** environment variable already defined in my project.

This is my jreleaser file:
```yaml
project:
  name: jave-test
  version: 0.1.0-SNAPSHOT
  description: Java Test sample project
  website: https://code.roche.com
  license: MIT
  authors:
    - Anyul Rivas
release:
  gitlab:
    enabled: true
    owner: anyul.rivas_oropeza
    name: java-test
    host: code.roche.com
    username: anyul.rivas_oropeza
    tagName: v1.0.0
    releaseName: Release v1.0.0
    overwrite: true
    allowUploadToExisting: true
    skipTagging: false
    # The Gitlab API endpoint to use.
    # You can skip `/api/v4` as it will be added by default.
    # Defaults to `https://gitlab.com`.
    #
    apiEndpoint: https://gitlab.com
    commitAuthor:
      name: anyul.rivas_oropeza
      email: anyul.rivas_oropeza@roche.com

    sign: false
    changelog:
      enabled: true
      sort: DESC
      external: /changelog.md
      links: false
    milestone:
      close: false
      name: Sprint-1
    ref: master
    # The following properties define  URL formats.
    # Defaults are shown.
    # Review the available Name Templates.
    repoUrlFormat: https://{{repoHost}}/{{repoOwner}}/{{repoName}}
    repoCloneUrlFormat: https://{{repoHost}}/{{repoOwner}}/{{repoName}}.git
    commitUrlFormat: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/-/commits
    downloadUrlFormat: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/-/releases/{{tagName}}/downloads/{{artifactFileName}}
    releaseNotesUrlFormat: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/-/releases/{{tagName}}
    latestReleaseUrlFormat: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/-/releases/{{tagName}}
    issueTrackerUrlFormat: https://{{repoHost}}/{{repoOwner}}/{{repoName}}/-/issues
```
And the pipeline ci file

```yaml
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: '-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository'

.shared_runners:
  tags:
    - Linux
    - amd64
    - docker
    - on-prem
    - cache

build:
  extends:
    - .shared_runners
  image: azul/zulu-openjdk:11
  stage: build
  script:
    - ./mvnw --batch-mode verify
  artifacts:
    paths:
      - target/*.zip

get-jreleaser:
  stage: build
  extends:
    - .shared_runners
  script:
    - curl -sL https://git.io/get-jreleaser > get_jreleaser.java
  artifacts:
    paths:
      - '*.java'

download-jreleaser:
  image: azul/zulu-openjdk:11
  stage: test
  script:
    - java get_jreleaser.java
    - java -jar jreleaser-cli.jar --version
  artifacts:
    paths:
      - jreleaser-cli.jar

release:
  image: azul/zulu-openjdk:11
  stage: deploy
  variables:
    JRELEASER_GPG_PASSPHRASE: $GPG_PASSPHRASE
    JRELEASER_GPG_PUBLIC_KEY: $GPG_PUBLIC_KEY
    JRELEASER_GPG_SECRET_KEY: $GPG_SECRET_KEY
    JRELEASER_GITLAB_TOKEN: $GL_PAT
    GIT_DEPTH: 0
  script:
    - java -jar jreleaser-cli.jar full-release
```

This is the error I'm getting:

```log
java -jar jreleaser-cli.jar full-release
jrleaser 0.1.0. Consider becoming a patron at https://www.patreon.com/aalmiray
[INFO]  JReleaser 0.1.0
[INFO]  Configuring with jreleaser.yml
[INFO]    - basedir set to /builds/anyul.rivas_oropeza/java-test
[INFO]  Reading configuration
[INFO]  Validating configuration
[INFO]  Project version set to 0.1.0-SNAPSHOT
[INFO]  Release is snapshot
[INFO]  Timestamp is 2021-04-12T07:15:04.865684Z
[INFO]  HEAD is at fab1aac
[INFO]  dryrun set to false
[INFO]  Generating changelog: out/jreleaser/release/CHANGELOG.md
[INFO]  Calculating checksums
[INFO]  No files configured for checksum. Skipping
[INFO]  Signing files
[INFO]  Signing is not enabled. Skipping
[INFO]  Releasing to https://code.roche.com/anyul.rivas_oropeza/java-test
jreleaser.shadow.org.jreleaser.sdk.gitlab.api.GitlabAPIException
	at jreleaser.shadow.org.jreleaser.sdk.gitlab.Gitlab.lambda$new$1(Gitlab.java:100)
	at jreleaser.shadow.feign.AsyncResponseHandler.handleResponse(AsyncResponseHandler.java:96)
	at jreleaser.shadow.feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138)
	at jreleaser.shadow.feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89)
	at jreleaser.shadow.feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
	at com.sun.proxy.$Proxy12.getCurrentUser(Unknown Source)
	at jreleaser.shadow.org.jreleaser.sdk.gitlab.Gitlab.getCurrentUser(Gitlab.java:162)
	at jreleaser.shadow.org.jreleaser.sdk.gitlab.Gitlab.getProject(Gitlab.java:169)
	at jreleaser.shadow.org.jreleaser.sdk.gitlab.Gitlab.findReleaseByTag(Gitlab.java:189)
	at jreleaser.shadow.org.jreleaser.sdk.gitlab.GitlabReleaser.release(GitlabReleaser.java:62)
	at jreleaser.shadow.org.jreleaser.engine.release.Releasers.release(Releasers.java:41)
	at jreleaser.shadow.org.jreleaser.workflow.ReleaseWorkflowItem.invoke(ReleaseWorkflowItem.java:33)
	at jreleaser.shadow.org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:72)
	at jreleaser.shadow.org.jreleaser.cli.FullRelease.doExecute(FullRelease.java:38)
	at jreleaser.shadow.org.jreleaser.cli.AbstractModelCommand.execute(AbstractModelCommand.java:62)
	at jreleaser.shadow.org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:85)
	at jreleaser.shadow.org.jreleaser.cli.AbstractModelCommand.call(AbstractModelCommand.java:37)
	at jreleaser.shadow.org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:33)
	at jreleaser.shadow.picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at jreleaser.shadow.picocli.CommandLine.access$1300(CommandLine.java:145)
	at jreleaser.shadow.picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at jreleaser.shadow.picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at jreleaser.shadow.picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at jreleaser.shadow.picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at jreleaser.shadow.picocli.CommandLine.execute(CommandLine.java:2078)
	at jreleaser.shadow.org.jreleaser.cli.Main.execute(Main.java:72)
	at jreleaser.shadow.org.jreleaser.cli.Main.run(Main.java:68)
	at org.jreleaser.tool.JReleaser.main(JReleaser.java:43)
```

**Comment by aalmiray** [comment]
The last `INFO` line reads as

`Releasing to https://code.roche.com/anyul.rivas_oropeza/java-test`

That's the wrong URL. It should had been

`Releasing to https://gitlab.com/anyul.rivas_oropeza/java-test`

Looks like the wrong host may have been configured

```
release:
  gitlab:
    host: code.roche.com
```

Is `https://code.roche.com` running a GgitLab instance?

**Comment by anyulled** [comment]
Yes, we're using a Gitlab CE instance running on our premises. I changed it later along with other changes and it finally worked

**Comment by dimidevk** [comment]
@anyulled we have got a similar issue with a corporate gitlab, can you tell me how it was solved?

**Comment by aalmiray** [comment]
@dimidevk you must update both `host:` and `apiEndpoint:` to the correct values of your environment. you can verify the settings by invoking:

* CLI: `jreleaser config`
* Maven: `mvn jreleaser:config`
* Gradle: `gradle jreleaserConfig`

**Comment by dimidevk** [comment]
@aalmiray both settings are correctly set, the api token also has got all rights, but unfortunaly i am not able to create the release, following stacktrace is thrown:

org.jreleaser.sdk.commons.RestAPIException
        at org.jreleaser.sdk.gitlab.Gitlab.getProject(Gitlab.java:173)
        at org.jreleaser.sdk.gitlab.Gitlab.findReleaseByTag(Gitlab.java:188)
        at org.jreleaser.sdk.gitlab.GitlabReleaser.createRelease(GitlabReleaser.java:78)
        at org.jreleaser.model.releaser.spi.AbstractReleaser.release(AbstractReleaser.java:52)
        at org.jreleaser.engine.release.Releasers.release(Releasers.java:44)
        at org.jreleaser.workflow.ReleaseWorkflowItem.invoke(ReleaseWorkflowItem.java:34)
        at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:64)
        at org.jreleaser.cli.Release.doExecute(Release.java:251)
        at org.jreleaser.cli.AbstractModelCommand.execute(AbstractModelCommand.java:79)
        at org.jreleaser.cli.Release.execute(Release.java:185)
        at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:70)
        at org.jreleaser.cli.AbstractModelCommand.call(AbstractModelCommand.java:46)
        at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:41)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at org.jreleaser.cli.Main.execute(Main.java:71)
        at org.jreleaser.cli.Main.run(Main.java:56)
        at org.jreleaser.cli.Main.main(Main.java:47)

also there is no evidence of any error in the trace.log

**Comment by aalmiray** [comment]
@dimidevk the code throwing the exception is found inside this method

https://github.com/jreleaser/jreleaser/blob/8011872fe8431baeac3af905502597bfa79afd8e/sdks/gitlab-java-sdk/src/main/java/org/jreleaser/sdk/gitlab/Gitlab.java#L160-L183

Specifically the check for a list of projects associated with the current user, which are obtained by issuing a REST call such as `GET /users/{userId}/projects`. There's a logging statement right before the exception is thrown (look for it inside trace.log) that states the project name, username, and user id to use. Should look similar to "fetching project {} for user {} ({})".

Are those values correct for your environment? Does the given username and user id have access to the configured project name? Alternatively if you know the project id you may set it in which case it'll be found regardless of the username/user id.

**Comment by dimidevk** [comment]
@aalmiray thanks for the insights and for your support, the trick with the projectId worked. I guess the problem was that the Gitlab-Api-Query was not correct, because the project was nested in a group and a subgroup. Anyways - thanks again!
