### ISSUE TITLE
[jlink] can't assemble due to invalid module names

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#476]
Assembling a jlink distribution with a Quarkus uberjar yields the following

```
[INFO]   [jlink] Error: Module Warning: split package: org.graalvm.polyglot.io jrt:/org.graalvm.sdk /Users/aalmiray/tmp/q-cli-jlink/target/q-cli-jlink-0.1.0-runner.jar not found
[INFO]   [jlink] java.lang.module.FindException: Module Warning: split package: org.graalvm.polyglot.io jrt:/org.graalvm.sdk /Users/aalmiray/tmp/q-cli-jlink/target/q-cli-jlink-0.1.0-runner.jar not found
[INFO]   [jlink] 	at java.base/java.lang.module.Resolver.findFail(Resolver.java:893)
[INFO]   [jlink] 	at java.base/java.lang.module.Resolver.resolve(Resolver.java:129)
[INFO]   [jlink] 	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:492)
[INFO]   [jlink] 	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:298)
[INFO]   [jlink] 	at jdk.jlink/jdk.tools.jlink.internal.Jlink$JlinkConfiguration.resolveAndBind(Jlink.java:206)
[INFO]   [jlink] 	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.createImageProvider(JlinkTask.java:535)
[INFO]   [jlink] 	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.createImage(JlinkTask.java:424)
[INFO]   [jlink] 	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.run(JlinkTask.java:276)
[INFO]   [jlink] 	at jdk.jlink/jdk.tools.jlink.internal.Main.run(Main.java:55)
[INFO]   [jlink] 	at jdk.jlink/jdk.tools.jlink.internal.Main.main(Main.java:33)
[INFO] Writing output properties to target/jreleaser/output.properties
[ERROR] JReleaser failed after 2.777 s
```

The cause is the output of `jdeps` contains warnings. The captured output of `jdeps` is passed in as the list of modules to be used by `jlink`.

**Comment by aalmiray** [comment]
Fixed with https://github.com/jreleaser/jreleaser/commit/e70ff1c998da0ab8fb61d86eed1856d9819e5fc3
