### ISSUE TITLE
javax.net.ssl.SSLHandshakeException when attempting release in Ubuntu

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#609]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Provision an Ubuntu instance on OCI
2. Clone https://github.com/aalmiray/app/
3. Download [`jreleaser-standalone-0.9.1-linux](https://github.com/jreleaser/jreleaser/releases/download/v0.9.1/jreleaser-standalone-0.9.1-linux-x86_64.zip)
4. Install Java 11 via Sdkman
5. Build the project (`./mvnw verify`)
6. Set `JRELEASER_GITHUB_TOKEN` to a valid value
7. Attempt a release with `releaser-standalone-0.9.1-linux-x86_64/bin/jreleaser release -y`

### Expected Behaviour

Successful release in dryrun mode

### Actual Behaviour

An exception occurs

```
feign.RetryableException: Received fatal alert: handshake_failure executing GET https://api.github.com/search/users?q=aalmiray%40gmail.com
	at feign.FeignException.errorExecuting(FeignException.java:268)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:129)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
	at jdk.proxy2/jdk.proxy2.$Proxy18.searchUser(Unknown Source)
	at org.jreleaser.sdk.github.XGithub.findUser(XGithub.java:87)
	at org.jreleaser.sdk.github.GithubReleaser.findUser(GithubReleaser.java:168)
	at org.jreleaser.sdk.git.ChangelogGenerator.lambda$formatContributors$19(ChangelogGenerator.java:432)
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.jreleaser.sdk.git.ChangelogGenerator.formatContributors(ChangelogGenerator.java:436)
	at org.jreleaser.sdk.git.ChangelogGenerator.formatChangelog(ChangelogGenerator.java:404)
	at org.jreleaser.sdk.git.ChangelogGenerator.createChangelog(ChangelogGenerator.java:104)
	at org.jreleaser.sdk.git.ChangelogGenerator.generate(ChangelogGenerator.java:532)
	at org.jreleaser.sdk.git.ChangelogProvider.resolveChangelog(ChangelogProvider.java:76)
	at org.jreleaser.sdk.git.ChangelogProvider.getChangelog(ChangelogProvider.java:41)
	at org.jreleaser.engine.changelog.Changelog.createChangelog(Changelog.java:37)
	at org.jreleaser.workflow.ChangelogWorkflowItem.invoke(ChangelogWorkflowItem.java:30)
	at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:64)
	at org.jreleaser.cli.Release.doExecute(Release.java:251)
	at org.jreleaser.cli.AbstractModelCommand.execute(AbstractModelCommand.java:79)
	at org.jreleaser.cli.Release.execute(Release.java:185)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:70)
	at org.jreleaser.cli.AbstractModelCommand.call(AbstractModelCommand.java:46)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:41)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.jreleaser.cli.Main.execute(Main.java:71)
	at org.jreleaser.cli.Main.run(Main.java:56)
	at org.jreleaser.cli.Main.main(Main.java:47)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at feign.httpclient.ApacheHttpClient.execute(ApacheHttpClient.java:83)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:119)
	... 40 more
```

### Environment Information

- **Operating System**: `Linux ubuntu 5.11.0-1022-oracle #23~20.04.1-Ubuntu SMP Fri Nov 12 15:45:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- **JReleaser Version:** 0.9.1
- **JDK Version:** 17.0.1

```
$ ./jreleaser-standalone-0.9.1-linux-x86_64/bin/java -version
openjdk version "17.0.1" 2021-10-19 LTS
OpenJDK Runtime Environment Zulu17.30+15-CA (build 17.0.1+12-LTS)
OpenJDK 64-Bit Server VM Zulu17.30+15-CA (build 17.0.1+12-LTS, mixed mode)
```

```
$ cat /proc/cpuinfo
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 1
model name	: AMD EPYC 7551 32-Core Processor
stepping	: 2
microcode	: 0x1000065
cpu MHz		: 1996.249
cache size	: 512 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext perfctr_core ssbd ibpb vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 virt_ssbd arat
bugs		: fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 3992.49
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 1
model name	: AMD EPYC 7551 32-Core Processor
stepping	: 2
microcode	: 0x1000065
cpu MHz		: 1996.249
cache size	: 512 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext perfctr_core ssbd ibpb vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 virt_ssbd arat
bugs		: fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 3992.49
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:
```

**Comment by aalmiray** [comment]
Missing modules:

 - 'java.security.sasl'
 - 'java.security.jgss'
 - 'jdk.crypto.cryptoki'
 - 'jdk.crypto.ec'
 - 'jdk.localedata'
 - 'jdk.net'
 - 'jdk.security.auth'
 - 'jdk.security.jgss'
