### ISSUE TITLE
"dryrun set to false" stage always fails !!

### ISSUE THREAD

**Issue by ApfelSaucell** [jreleaser/jreleaser#681]
executing release: ` % ../../apps/jreleaser-standalone-0.10.0-osx-x86_64/bin/jreleaser full-release `  leads to errors

* Environment Information

    - Operating System: OSX
    - JReleaser Version: 0.10.0
    - project JDK Version: jdk15
    - environment JDK Version: jdk17

```
**[INFO]  dryrun set to false**
feign.RetryableException: Received fatal alert: handshake_failure executing GET https://api.github.com/search/users?q=[username]%40yahoo.com
	at feign.FeignException.errorExecuting(FeignException.java:268)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:129)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
	at jdk.proxy2/jdk.proxy2.$Proxy18.searchUser(Unknown Source)
	at org.jreleaser.sdk.github.XGithub.findUser(XGithub.java:87)
	at org.jreleaser.sdk.github.GithubReleaser.findUser(GithubReleaser.java:168)
	at org.jreleaser.sdk.git.ChangelogGenerator.lambda$formatContributors$19(ChangelogGenerator.java:432)
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.jreleaser.sdk.git.ChangelogGenerator.formatContributors(ChangelogGenerator.java:436)
	at org.jreleaser.sdk.git.ChangelogGenerator.formatChangelog(ChangelogGenerator.java:404)
	at org.jreleaser.sdk.git.ChangelogGenerator.createChangelog(ChangelogGenerator.java:104)
	at org.jreleaser.sdk.git.ChangelogGenerator.generate(ChangelogGenerator.java:532)
	at org.jreleaser.sdk.git.ChangelogProvider.resolveChangelog(ChangelogProvider.java:76)
	at org.jreleaser.sdk.git.ChangelogProvider.getChangelog(ChangelogProvider.java:41)
	at org.jreleaser.engine.changelog.Changelog.createChangelog(Changelog.java:37)
	at org.jreleaser.workflow.ChangelogWorkflowItem.invoke(ChangelogWorkflowItem.java:30)
	at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:64)
	at org.jreleaser.cli.FullRelease.doExecute(FullRelease.java:35)
	at org.jreleaser.cli.AbstractModelCommand.execute(AbstractModelCommand.java:79)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:38)
	at org.jreleaser.cli.AbstractModelCommand.call(AbstractModelCommand.java:46)
	at org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:29)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.jreleaser.cli.Main.execute(Main.java:72)
	at org.jreleaser.cli.Main.run(Main.java:57)
	at org.jreleaser.cli.Main.main(Main.java:48)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at feign.httpclient.ApacheHttpClient.execute(ApacheHttpClient.java:83)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:119)
	... 39 more
```

- I did all the proper configuration as in documentation.
any Idea?

**Comment by ApfelSaucell** [comment]
**Solved**

after changing the environmental jdk to 15, I could make a release

**Comment by aalmiray** [comment]
This means you ran `jreleaser` with JDK 17 and got an SSL exception but it works if running with JDK 15?

**Comment by ApfelSaucell** [comment]
> This means you ran `jreleaser` with JDK 17 and got an SSL exception but it works if running with JDK 15?

sorry, problem is still open.   still getting the same problem.

**Comment by ApfelSaucell** [comment]
+ also with jdk 15 still not working !!

**Comment by ApfelSaucell** [comment]
> FWIW if you're running `jreleaser-standalone` then you don't need an external JVM. `v0.10.0` ships with a custom Java Runtime based on Zulu JDK17.

I think I got lost Andres, I still try to deploy to my **private** github repo. and in this stage i always fail: `feign.RetryableException: Received fatal alert: handshake_failure executing GET`

any ideas why this happens !!

**Comment by aalmiray** [comment]
This may be similar to https://github.com/jreleaser/jreleaser/issues/609 except that in your case it happens on OSX instead Ubuntu.

**Comment by ApfelSaucell** [comment]
> This may be similar to #609 except that in your case it happens on OSX instead Ubuntu.

- That is **exactly** the same error 👍 . Do you know if it is security issue? any solution meanwhile?

**Comment by aalmiray** [comment]
Are you running the build behind a firewall or vpn?

**Comment by ApfelSaucell** [comment]
> Are you running the build behind a firewall or vpn?

Nop :-(

**Comment by aalmiray** [comment]
Found the root cause based on https://stackoverflow.com/questions/54770538/received-fatal-alert-handshake-failure-in-jlinked-jre

Basically the jlink distribution is missing module `jdk.crypto.ec`. To be honest there are a couple more modules that may need to be included as well. There's nothing you can do on your side, the next release will include the fix).

**Comment by aalmiray** [comment]
Closing this one report in favor of #609 as it was reported earlier. Thanks!

**Comment by aalmiray** [comment]
@ApfelSaucell you may download the latest `early-access` release to give it a try https://github.com/jreleaser/jreleaser/releases/download/early-access/jreleaser-standalone-early-access-osx-x86_64.zip
