### ISSUE TITLE
[brew] NPE due to invalid homebrew configuration

### ISSUE THREAD

**Issue by bitspittle** [jreleaser/jreleaser#699]
I'm not yet clear what I should be doing to create a brew configuration, so I thought I'd just experiment by setting dry-run to true and trying stuff.

At this point, in Gradle, all I have is this in the `packagers` section:

```
    packagers {
        brew {
            enabled.set(true)
            active.set(Active.RELEASE)
        }
    }
```

Running `jreleaserPublish`, I'm getting this:

```
> Task :cli:kobweb:jreleaserPublish FAILED
[INFO]  JReleaser 1.0.0-M1
[INFO]    - basedir set to /home/d9n/Code/1p/kobweb/cli/kobweb
[INFO]  Loading variables from /home/d9n/.jreleaser/config.properties
[WARN]  Variables source /home/d9n/.jreleaser/config.properties does not exist
[INFO]  Validating configuration
[INFO]  Project version set to 0.9.2
[INFO]  Release is not snapshot
[INFO]  Timestamp is 2022-01-24T14:16:31.823115-08:00
[INFO]  HEAD is at acf8fa1
[INFO]  Platform is linux-x86_64
[INFO]  dry-run set to true
[INFO]  Calculating checksums
[INFO]    [checksum] All checksums are up-to-date. Skipping
[INFO]  Preparing distributions
[INFO]    - Preparing kobweb distribution
[INFO]      [brew] preparing kobweb distribution
[INFO]  Writing output properties to build/jreleaser/output.properties
[ERROR] JReleaser failed after 0.011 s

Execution failed for task ':cli:kobweb:jreleaserPublish'.
> Unexpected error

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':cli:kobweb:jreleaserPublish'.
Caused by: org.jreleaser.util.JReleaserException: Unexpected error
	at org.jreleaser.engine.distribution.Distributions.processPackager(Distributions.java:127)
	at org.jreleaser.engine.distribution.Distributions.processDistribution(Distributions.java:102)
	at org.jreleaser.engine.distribution.Distributions.process(Distributions.java:88)
	at org.jreleaser.workflow.PrepareWorkflowItem.invoke(PrepareWorkflowItem.java:32)
	at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:66)
	at org.jreleaser.gradle.plugin.tasks.JReleaserPublishTask.performAction(JReleaserPublishTask.groovy:41)
Caused by: org.jreleaser.model.packager.spi.PackagerProcessingException: java.lang.NullPointerException
	at org.jreleaser.packagers.AbstractPackagerProcessor.prepareDistribution(AbstractPackagerProcessor.java:143)
	at org.jreleaser.packagers.BrewPackagerProcessor.prepareDistribution(BrewPackagerProcessor.java:73)
	at org.jreleaser.engine.distribution.DistributionProcessor.prepareDistribution(DistributionProcessor.java:75)
	at org.jreleaser.engine.distribution.Distributions.processPackager(Distributions.java:125)
	... 123 more
Caused by: java.lang.NullPointerException
	at org.jreleaser.model.util.Artifacts.resolveDownloadUrlFromUploader(Artifacts.java:383)
	at org.jreleaser.model.util.Artifacts.resolveDownloadUrl(Artifacts.java:293)
	at org.jreleaser.packagers.AbstractPackagerProcessor.verifyAndAddArtifacts(AbstractPackagerProcessor.java:313)
	at org.jreleaser.packagers.AbstractPackagerProcessor.verifyAndAddArtifacts(AbstractPackagerProcessor.java:294)
	at org.jreleaser.packagers.AbstractPackagerProcessor.fillProps(AbstractPackagerProcessor.java:199)
	at org.jreleaser.packagers.AbstractPackagerProcessor.prepareDistribution(AbstractPackagerProcessor.java:135)
	... 126 more
```

I know this is probably user error on my part, but maybe a better error message can be shown here?

**Comment by bitspittle** [comment]
In contrast, `snap` gives a much more informative error:

```
ERROR] == JReleaser ==
[ERROR] distribution.kobweb.snap.exportedLogin must not be empty

Execution failed for task ':cli:kobweb:jreleaserPublish'.
> JReleaser has not been properly configured.
  distribution.kobweb.snap.exportedLogin must not be empty
```

**Comment by aalmiray** [comment]
FWIW you don't set the `enabled` property, just `active` is enough.

**Comment by bitspittle** [comment]
By the way I spent a bit of time just reading about Homebrew, and I just set up my own `homebrew-tap` repository. I'm pretty sure what was missing was a downloadUrl. Investigating that right now, and will update this issue if that pans out.

**Comment by bitspittle** [comment]
OK, confirmed. When I set a downloadUrl, no more NPE.

So this bug could be closed if `brew` publishing gave a more informative error that no download URL could be determined.

**Comment by aalmiray** [comment]
An explicit downloadUrl is only needed if the artifact should be downloaded from another location that's not the default one (as a release asset). In this case it appears a check is missing in the code that resolves the default downloadUrl.

**Comment by aalmiray** [comment]
Just checked. This is indeed a bug in the code.

**Comment by aalmiray** [comment]
I see now what condition triggered this. 

https://github.com/varabyte/kobweb/blob/be9243caa54c88608e313f334c0e7b6e42109fdd/cli/kobweb/build.gradle.kts#L57
https://github.com/varabyte/kobweb/blob/be9243caa54c88608e313f334c0e7b6e42109fdd/cli/kobweb/build.gradle.kts#L92

JReleaser has been configured to skip the release and there are no uploaders configured. However release assets are still available as the release is created by other means. The use of the `downloadUrl` is mandatory in this case.

Two things should happen:
1. fix the NPE
2. find a way to enable the default downloadUrl as it was before. Previously packagers would always assume release assets were available from a git release.
