### ISSUE TITLE
[chocolatey] Illegal characters in path.

### ISSUE THREAD

**Issue by sualeh** [jreleaser/jreleaser#729]
I am using the "early-access" version, and I get the following with the Chocolatey packager. The [JReleaser out/ directory ](https://github.com/schemacrawler/SchemaCrawler-Installers/actions/runs/1780676765) is attached to this run of https://github.com/schemacrawler/SchemaCrawler-Installers

```
[INFO]      [chocolatey] Chocolatey v0.12.0
[INFO]      [chocolatey] Illegal characters in path.
[INFO]  Writing output properties to out\jreleaser\output.properties
[ERROR] JReleaser failed after 13.866 s
jreleaser.shadow.org.jreleaser.util.JReleaserException: Unexpected error
	at jreleaser.shadow.org.jreleaser.engine.distribution.Distributions.processPackager(Distributions.java:127)
	at jreleaser.shadow.org.jreleaser.engine.distribution.Distributions.processDistribution(Distributions.java:102)
	at jreleaser.shadow.org.jreleaser.engine.distribution.Distributions.process(Distributions.java:88)
	at jreleaser.shadow.org.jreleaser.workflow.PublishWorkflowItem.invoke(PublishWorkflowItem.java:32)
	at jreleaser.shadow.org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:66)
	at jreleaser.shadow.org.jreleaser.cli.FullRelease.doExecute(FullRelease.java:144)
	at jreleaser.shadow.org.jreleaser.cli.AbstractModelCommand.execute(AbstractModelCommand.java:81)
	at jreleaser.shadow.org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:38)
	at jreleaser.shadow.org.jreleaser.cli.AbstractModelCommand.call(AbstractModelCommand.java:47)
	at jreleaser.shadow.org.jreleaser.cli.AbstractCommand.call(AbstractCommand.java:29)
	at jreleaser.shadow.picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at jreleaser.shadow.picocli.CommandLine.access$1300(CommandLine.java:145)
	at jreleaser.shadow.picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at jreleaser.shadow.picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at jreleaser.shadow.picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at jreleaser.shadow.picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at jreleaser.shadow.picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at jreleaser.shadow.picocli.CommandLine.execute(CommandLine.java:2078)
	at jreleaser.shadow.org.jreleaser.cli.Main.execute(Main.java:72)
	at jreleaser.shadow.org.jreleaser.cli.Main.run(Main.java:68)
	at org.jreleaser.tool.JReleaser.main(JReleaser.java:45)
Caused by: jreleaser.shadow.org.jreleaser.model.packager.spi.PackagerProcessingException: Unexpected error
	at jreleaser.shadow.org.jreleaser.packagers.AbstractPackagerProcessor.executeCommand(AbstractPackagerProcessor.java:227)
	at jreleaser.shadow.org.jreleaser.packagers.ChocolateyPackagerProcessor.publishChocolateyPackage(ChocolateyPackagerProcessor.java:163)
	at jreleaser.shadow.org.jreleaser.packagers.ChocolateyPackagerProcessor.doPublishDistribution(ChocolateyPackagerProcessor.java:87)
	at jreleaser.shadow.org.jreleaser.packagers.AbstractPackagerProcessor.publishDistribution(AbstractPackagerProcessor.java:182)
	at jreleaser.shadow.org.jreleaser.packagers.ChocolateyPackagerProcessor.publishDistribution(ChocolateyPackagerProcessor.java:51)
	at jreleaser.shadow.org.jreleaser.engine.distribution.DistributionProcessor.publishDistribution(DistributionProcessor.java:141)
	at jreleaser.shadow.org.jreleaser.engine.distribution.Distributions.processPackager(Distributions.java:125)
	... 20 more
Caused by: jreleaser.shadow.org.jreleaser.util.command.CommandException: Command execution error. exitValue = 1
	at jreleaser.shadow.org.jreleaser.packagers.AbstractPackagerProcessor.executeCommand(AbstractPackagerProcessor.java:224)
	... 26 more
```

**Comment by aalmiray** [comment]
This may be a problem of running the `jreleaser/release-action` on bash by default

https://github.com/jreleaser/release-action/blob/f4b19f681fa6af6484112125481e5ace7806d35b/action.yml#L50-L55

Also, please add an `always()` condition to the step that uploads the logs, such as

```
      - name: JReleaser release output
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: jreleaser-release
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties
```

**Comment by aalmiray** [comment]
Release `2.1.0` or https://github.com/jreleaser/release-action is out. Please configure the running shell 

```
    - id: jreleaser
      name: Run JReleaser
      uses: jreleaser/release-action@v2
      with:
        shell: pwsh
```

With `v2` you also don't have to have an explicit setup java step as the action will do it for you.

**Comment by sualeh** [comment]
@aalmiray - I am just wondering if it makes sense to use "pwsh" on all platforms, and not make the shell configurable.

**Comment by aalmiray** [comment]
It works with "pwsh" as default. Will push `v2.1.1` which should be rolled automatically to tag `v2` thus you don't have to do anything if you're already on `v2`. I'll ping you again here once it's done.

**Comment by aalmiray** [comment]
@sualeh it's done.

**Comment by sualeh** [comment]
@aalmiray - wait - please re-open. The Chocolatey issue is still not fixed. I will point you to the logs.

**Comment by sualeh** [comment]
@aalmiray - did you push an early access release? I can verify the fix for you.

**Comment by aalmiray** [comment]
@sualeh Thanks! The `early-access` release is underway https://github.com/jreleaser/jreleaser/actions/runs/1786545010

**Comment by sualeh** [comment]
@aalmiray - I think it worked! Let me verify on choco.

**Comment by sualeh** [comment]
@adriens -how long will it take for the new release to show on Chocolatey?
