### ISSUE TITLE
[gitlab] Nullpointer when publishing to sdkman with gitlab+s3

### ISSUE THREAD

**Issue by martypitt** [jreleaser/jreleaser#748]
When packaging a release to sdkman from Gitlab with an s3 uploaded resource, a null pointer exception occurs.

### Steps to Reproduce
1. See config [here](https://gitlab.com/taxi-lang/taxi-lang/-/blob/2f7c2f6b0c665d3f7567848c7a17aefc17425ec0/taxi-cli/jreleaser.yml).
1. Run `mvn jreleaser:full-release` with the provided config

 

### Expected Behaviour
1. releases to sdkman

Tell us what should happen

### Actual Behaviour
1. mvn plugin exits with null pointer:

```
[INFO] Publishing distributions
[INFO]   - Publishing taxi distribution
[INFO]     [sdkman] publishing taxi distribution
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  20.311 s
[INFO] Finished at: 2022-02-14T13:33:21Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jreleaser:jreleaser-maven-plugin:1.0.0-M1:full-release (default-cli) on project taxi-cli: Execution default-cli of goal org.jreleaser:jreleaser-maven-plugin:1.0.0-M1:full-release failed.: NullPointerException -> [Help 1]
```

No null pointers present in the `trace.log` file.

Note that originally I had not provided the config entry at `packagers.sdkman.downloadUrl`.  However, that also failed with an NPE - but did yield a stack trace, provided below.

```yaml
packagers:
   #
   sdkman:
      active: ALWAYS
      continueOnError: false
      candidate: taxi
      command: MINOR

      ## Delete this line, and yields the below stack trace
      downloadUrl: https://repo.vyne.co/release/org/taxilang/taxi-cli/{{projectVersion}}/taxi.zip
```

```
[INFO]  Writing output properties to target/jreleaser/output.properties
[ERROR] JReleaser failed after 16.199 s
org.jreleaser.util.JReleaserException: Unexpected error
	at org.jreleaser.engine.distribution.Distributions.processPackager(Distributions.java:127)
	at org.jreleaser.engine.distribution.Distributions.processDistribution(Distributions.java:102)
	at org.jreleaser.engine.distribution.Distributions.process(Distributions.java:88)
	at org.jreleaser.workflow.PrepareWorkflowItem.invoke(PrepareWorkflowItem.java:32)
	at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:66)
	at org.jreleaser.maven.plugin.JReleaserFullReleaseMojo.execute(JReleaserFullReleaseMojo.java:48)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: org.jreleaser.model.packager.spi.PackagerProcessingException: java.lang.NullPointerException
	at org.jreleaser.packagers.AbstractPackagerProcessor.prepareDistribution(AbstractPackagerProcessor.java:143)
	at org.jreleaser.packagers.SdkmanPackagerProcessor.prepareDistribution(SdkmanPackagerProcessor.java:42)
	at org.jreleaser.engine.distribution.DistributionProcessor.prepareDistribution(DistributionProcessor.java:75)
	at org.jreleaser.engine.distribution.Distributions.processPackager(Distributions.java:125)
	... 27 more
Caused by: java.lang.NullPointerException
	at org.jreleaser.model.util.Artifacts.resolveDownloadUrlFromUploader(Artifacts.java:383)
	at org.jreleaser.model.util.Artifacts.resolveDownloadUrl(Artifacts.java:293)
	at org.jreleaser.packagers.AbstractPackagerProcessor.verifyAndAddArtifacts(AbstractPackagerProcessor.java:313)
	at org.jreleaser.packagers.AbstractPackagerProcessor.verifyAndAddArtifacts(AbstractPackagerProcessor.java:294)
	at org.jreleaser.packagers.AbstractPackagerProcessor.fillProps(AbstractPackagerProcessor.java:199)
	at org.jreleaser.packagers.AbstractPackagerProcessor.prepareDistribution(AbstractPackagerProcessor.java:135)
	... 30 more

```

### Environment Information

```
------------------------------------------------------------
jreleaser 1.0.0-M1
------------------------------------------------------------
Build time:   2022-01-22 09:38:55Z
Revision:     2489915b925abc10a1f0c4cf2afa2fae75f031ba
------------------------------------------------------------
```

- **Operating System**: Ubuntu 20.04
- **JReleaser Version:** Above
- **JDK Version:** 11.0.13

Please paste stacktraces from `[out|build|target]/jreleaser/trace.log`.

**Comment by aalmiray** [comment]
I believe you encountered the same problem reported at https://github.com/jreleaser/jreleaser/issues/699 which has been fixed in `1.0.0-M2`. Please upgrade and give it another try.
