### ISSUE TITLE
[release] Cannot update linked artifacts on Gitlab

### ISSUE THREAD

**Issue by martypitt** [jreleaser/jreleaser#749]
When releasing to gitlab, if a linked artifact already exists, publication fails, even if `release.gitlab.update = true`

### Steps to Reproduce

Using the [linked configuration]((https://gitlab.com/taxi-lang/taxi-lang/-/blob/2f7c2f6b0c665d3f7567848c7a17aefc17425ec0/taxi-cli/jreleaser.yml), attempt to publish to gitlab twice

### Expected Behaviour

Both publications should succeed

### Actual Behaviour

The second publication fails with a 400 Bad Request and `RestAPIException`.

Stack trace:

```
[INFO]  Releasing to https://gitlab.com/taxi-lang/taxi-lang
[DEBUG] looking up release with tag v1.32.1 at repository taxi-lang/taxi-lang
[DEBUG] fetching release on taxi-lang/taxi-lang with tag v1.32.1
[DEBUG] fetching project with GitLab id 3493030
[DEBUG] found taxi-lang / taxi-lang (ID: 3493030)
[DEBUG] release v1.32.1 exists
[DEBUG] updating release v1.32.1
[DEBUG] uploading assets to taxi-lang/taxi-lang
[INFO]   - uploading checksums_sha256.txt
[DEBUG] linking assets to taxi-lang/taxi-lang with tag v1.32.1
[DEBUG]  - linking checksums_sha256.txt
[ERROR]  x failed to link checksums_sha256.txt
400 Bad Request
org.jreleaser.sdk.commons.RestAPIException
	at org.jreleaser.sdk.commons.ClientUtils.lambda$builder$1(ClientUtils.java:82)
	at feign.AsyncResponseHandler.handleResponse(AsyncResponseHandler.java:96)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
	at com.sun.proxy.$Proxy36.linkAsset(Unknown Source)
	at org.jreleaser.sdk.gitlab.Gitlab.linkReleaseAssets(Gitlab.java:271)
	at org.jreleaser.sdk.gitlab.GitlabReleaser.createRelease(GitlabReleaser.java:124)
	at org.jreleaser.model.releaser.spi.AbstractReleaser.release(AbstractReleaser.java:51)
	at org.jreleaser.engine.release.Releasers.release(Releasers.java:44)
	at org.jreleaser.workflow.ReleaseWorkflowItem.invoke(ReleaseWorkflowItem.java:34)
	at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:66)
	at org.jreleaser.maven.plugin.JReleaserFullReleaseMojo.execute(JReleaserFullReleaseMojo.java:48)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[INFO]  Writing output properties to target/jreleaser/output.properties
[ERROR] JReleaser failed after 16.274 s
org.jreleaser.util.JReleaserException: Unexpected error when creating release
	at org.jreleaser.workflow.ReleaseWorkflowItem.invoke(ReleaseWorkflowItem.java:36)
	at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:66)
	at org.jreleaser.maven.plugin.JReleaserFullReleaseMojo.execute(JReleaserFullReleaseMojo.java:48)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: org.jreleaser.model.releaser.spi.ReleaseException: org.jreleaser.sdk.commons.RestAPIException
	at org.jreleaser.sdk.gitlab.GitlabReleaser.createRelease(GitlabReleaser.java:150)
	at org.jreleaser.model.releaser.spi.AbstractReleaser.release(AbstractReleaser.java:51)
	at org.jreleaser.engine.release.Releasers.release(Releasers.java:44)
	at org.jreleaser.workflow.ReleaseWorkflowItem.invoke(ReleaseWorkflowItem.java:34)
	... 24 more
Caused by: org.jreleaser.sdk.commons.RestAPIException
	at org.jreleaser.sdk.commons.ClientUtils.lambda$builder$1(ClientUtils.java:82)
	at feign.AsyncResponseHandler.handleResponse(AsyncResponseHandler.java:96)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
	at com.sun.proxy.$Proxy36.linkAsset(Unknown Source)
	at org.jreleaser.sdk.gitlab.Gitlab.linkReleaseAssets(Gitlab.java:271)
	at org.jreleaser.sdk.gitlab.GitlabReleaser.createRelease(GitlabReleaser.java:124)
	... 27 more
```

Note that the [documentation states](https://jreleaser.org/guide/latest/configuration/release/gitlab.html) the update section should be defined as follows:

```yaml
#
release:
  # Repo in which the release will be created.
  #
  gitlab:

    #
    update:
      # Appends artifacts to an existing release with matching tag,
      # useful if `overwrite` is set to `false`.
      # May define a `JRELEASER_UPDATE` environment variable instead.
      # Defaults to `false`.
      #
      enabled: true

      # Release sections to be updated.
      # Valid values are [`TITLE`, `BODY`, `ASSETS`].
      # Defaults to `ASSETS`.
      #
      sections:
        - ASSETS
```

This suggests the parameter should be `release.gitlab.update.enabled=true`.

However, when using that config, jreleaser fails to start with:

```
[ERROR] Failed to execute goal org.jreleaser:jreleaser-maven-plugin:1.0.0-M1:full-release (default-cli) on project taxi-cli: JReleaser for project taxi-cli has not been properly configured.: Unexpected error parsing config file. /home/marty/dev/taxi-lang/taxi-cli/jreleaser.yml: Cannot deserialize value of type `java.lang.Boolean` from Object value (token `JsonToken.START_OBJECT`)
```

Instead, using this config allows the app to start:

```yaml
#
release:
  # Repo in which the release will be created.
  #
  gitlab:

    #
    update: true
```

### Workaround
When using `release.gitlab.overwrite: true`, the gitlab phase completes.

### Environment Information

```
➜  taxi-cli git:(jreleaser) ✗ jreleaser --version
------------------------------------------------------------
jreleaser 1.0.0-M1
------------------------------------------------------------
Build time:   2022-01-22 09:38:55Z
Revision:     2489915b925abc10a1f0c4cf2afa2fae75f031ba
------------------------------------------------------------

➜  taxi-cli git:(jreleaser) ✗ javac --version
javac 11.0.13
```

**Comment by aalmiray** [comment]
The documentation points to `1.0.0-M2` at the moment which introduces the change in the `update` section. Please update to this version and give it a try one more. See https://github.com/jreleaser/jreleaser/issues/339

Updating an existing release does not override an existing asset. this feature has yet to be implemented hence why the docs state that artifacts will be appended to an existing release. Using the `overwrite` flag works as the release is dropped and recreated one more time.

**Comment by aalmiray** [comment]
To summarize:
 - `overwrite`: drops a matching release and creates a new one.
 - `update`: updates title, body. Appends artifacts as long as there are no intersecting artifacts in the existing release.

What's expected: `update` overwrites existing artifacts.

**Comment by martypitt** [comment]
Great, that solved the issue.  Thanks
