### ISSUE TITLE
Improve the error handling when working with an insufficient github token

### ISSUE THREAD

**Issue by mxab** [jreleaser/jreleaser#791]
### Task List

- [x ] Steps to reproduce provided

### Steps to Reproduce
1. Create a github token with no scopes checked
2. use this as the `JRELEASER_GITHUB_TOKEN=...`
3. `./gradlew jreleaserFullRelase`

### Expected Behavior

See an error message that hints that the token may not have sufficient rights to create a release

### Actual Behavior

Gradle's tasks fails. The stacktrace root cause is a FileNotFoundException when trying `api.github.com/..../releases`

After looking into code of the Github Api Client the HttpConnection getResponseCode throws this error message because of a 404. The 404 happend because my token didn't have enough rights. (I guess there is nothing you can do to prevent this strange behavior)

### Environment Information

- **Operating System**:  MacOS
- **JReleaser Version:** 1.0.0-M4
- **JDK Version:** 17 

Please paste stacktraces from `[out|build|target]/jreleaser/trace.log`.

**Comment by aalmiray** [comment]
Full stacktrace

```
Caused by: org.jreleaser.model.releaser.spi.ReleaseException: org.kohsuke.github.GHFileNotFoundException: https://api.github.com/repos/aalmiray/app/releases {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/repos#create-a-release"}
	at org.jreleaser.sdk.github.GithubReleaser.createRelease(GithubReleaser.java:134)
	at org.jreleaser.model.releaser.spi.AbstractReleaser.release(AbstractReleaser.java:51)
	at org.jreleaser.engine.release.Releasers.release(Releasers.java:44)
	at org.jreleaser.workflow.ReleaseWorkflowItem.invoke(ReleaseWorkflowItem.java:34)
	... 18 more
Caused by: org.kohsuke.github.GHFileNotFoundException: https://api.github.com/repos/aalmiray/app/releases {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/repos#create-a-release"}
	at org.kohsuke.github.GitHubClient.interpretApiError(GitHubClient.java:480)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:407)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:355)
	at org.kohsuke.github.Requester.fetch(Requester.java:76)
	at org.kohsuke.github.GHReleaseBuilder.create(GHReleaseBuilder.java:98)
	at org.jreleaser.sdk.github.GithubReleaser.createRelease(GithubReleaser.java:212)
	at org.jreleaser.sdk.github.GithubReleaser.createRelease(GithubReleaser.java:126)
	... 21 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/aalmiray/app/releases
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2048)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2043)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:2042)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1609)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at org.kohsuke.github.GitHubHttpUrlConnectionClient$HttpURLConnectionResponseInfo.bodyStream(GitHubHttpUrlConnectionClient.java:174)
	at org.kohsuke.github.GitHubResponse$ResponseInfo.getBodyAsString(GitHubResponse.java:314)
	at org.kohsuke.github.GitHubResponse.parseBody(GitHubResponse.java:92)
	at org.kohsuke.github.Requester.lambda$fetch$1(Requester.java:76)
	at org.kohsuke.github.GitHubClient.createResponse(GitHubClient.java:449)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:399)
	... 26 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/aalmiray/app/releases
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
	at org.kohsuke.github.GitHubHttpUrlConnectionClient.getResponseInfo(GitHubHttpUrlConnectionClient.java:63)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:387)
	... 26 more
```

**Comment by mxab** [comment]
Ah yeah sorry, I was in a hurry and didn't had the stacktrace at hand when I created the issue
