### ISSUE TITLE
[assemble] Jlink does not copy platform JARs

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#844]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone https://github.com/aalmiray/javafx-canvas-plasma
2. `mvn verify && mvn -Pjars verify`
3. `mvn -Passemble package`

### Expected Behaviour

There should be 3 Jlink runtime images

### Actual Behaviour

An exception occurs

### Environment Information

- **Operating System**: N/A
- **JReleaser Version:** 1.0.0
- **JDK Version:** N/A

```
[INFO]  Project version set to 1.0.0
[INFO]  Release is not snapshot
[INFO]  Timestamp is 2022-06-13T17:31:32.741653+02:00
[INFO]  HEAD is at 252937a
[INFO]  Platform is osx-x86_64
[INFO]  dry-run set to false
[INFO]  Assembling all distributions
[INFO]    [jlink] assembling plasmafx distribution
[DEBUG]   [jlink] creating props for jlink/plasmafx
[DEBUG]   [jlink] filling git properties into props
[DEBUG]   [jlink] filling assembler properties into props
[DEBUG]   [jlink] resolving templates for jlink/plasmafx
[DEBUG]   [jlink] resolving templates from classpath
[DEBUG]   [jlink] resolving template from classpath for jlink.jlink
[DEBUG]   [jlink] resolving template from classpath for jlink/jlink/launcher.tpl
[DEBUG]   [jlink] resolving template from classpath for jlink/jlink/launcher.bat.tpl
[DEBUG]   [jlink] evaluating template launcher.tpl for plasmafx/jlink
[DEBUG]   [jlink] writing template launcher.tpl for plasmafx/jlink
[DEBUG]   [jlink] evaluating template launcher.bat.tpl for plasmafx/jlink
[DEBUG]   [jlink] writing template launcher.bat.tpl for plasmafx/jlink
[DEBUG]   [jlink] jdk version is 17.0.1 /private/tmp/javafx-canvas-plasma/target/jdks/zulu17Osx/zulu17.30.15-ca-jdk17.0.1-macosx_x64/zulu-17.jdk/Contents/Home
[DEBUG]   [jlink] target version is 17.0.1 /private/tmp/javafx-canvas-plasma/target/jdks/zulu17Linux/zulu17.30.15-ca-jdk17.0.1-linux_x64
[DEBUG]   [jlink] target version is 17.0.1 /private/tmp/javafx-canvas-plasma/target/jdks/zulu17Osx/zulu17.30.15-ca-jdk17.0.1-macosx_x64/zulu-17.jdk/Contents/Home
[DEBUG]   [jlink] target version is 17.0.1 /private/tmp/javafx-canvas-plasma/target/jdks/zulu17Windows/zulu17.30.15-ca-jdk17.0.1-win_x64
[DEBUG]   [jlink] copying JARs to ../../private/tmp/javafx-canvas-plasma/target/jreleaser/assemble/plasmafx/jlink/inputs/jars/universal
[DEBUG]   [jlink] copying javafx-canvas-plasma-1.0.0.jar
[DEBUG]   [jlink] copying JARs to ../../private/tmp/javafx-canvas-plasma/target/jreleaser/assemble/plasmafx/jlink/inputs/jars/linux-x86_64
[DEBUG]   [jlink] /private/tmp/javafx-canvas-plasma/target/jdks/zulu17Osx/zulu17.30.15-ca-jdk17.0.1-macosx_x64/zulu-17.jdk/Contents/Home/bin/jdeps --multi-release 17 --ignore-missing-deps --print-module-deps universal/javafx-canvas-plasma-1.0.0.jar
[ERROR]   [jlink] Exception in thread "main" java.lang.module.FindException: Module javafx.controls not found, required by eu.openvalue
[ERROR]   [jlink] 	at java.base/java.lang.module.Resolver.findFail(Resolver.java:893)
[ERROR]   [jlink] 	at java.base/java.lang.module.Resolver.resolve(Resolver.java:192)
[ERROR]   [jlink] 	at java.base/java.lang.module.Resolver.resolve(Resolver.java:141)
[ERROR]   [jlink] 	at java.base/java.lang.module.Configuration.resolve(Configuration.java:421)
[ERROR]   [jlink] 	at java.base/java.lang.module.Configuration.resolve(Configuration.java:255)
[ERROR]   [jlink] 	at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration$Builder.build(JdepsConfiguration.java:564)
[ERROR]   [jlink] 	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.buildConfig(JdepsTask.java:603)
[ERROR]   [jlink] 	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:557)
[ERROR]   [jlink] 	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:533)
[ERROR]   [jlink] 	at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:49)
[ERROR]   [jlink] 
[INFO]  Writing output properties to ../../private/tmp/javafx-canvas-plasma/target/jreleaser/output.properties
[ERROR] JReleaser failed after 1.783 s
org.jreleaser.util.JReleaserException: Unexpected error
	at org.jreleaser.engine.assemble.Assemblers.assemble(Assemblers.java:106)
	at org.jreleaser.engine.assemble.Assemblers.assemble(Assemblers.java:92)
	at org.jreleaser.workflow.AssembleWorkflowItem.invoke(AssembleWorkflowItem.java:30)
	at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:66)
	at org.jreleaser.maven.plugin.JReleaserAssembleMojo.execute(JReleaserAssembleMojo.java:78)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: org.jreleaser.model.assembler.spi.AssemblerProcessingException: Unexpected error
	at org.jreleaser.assemblers.AbstractAssemblerProcessor.executeCommandCapturing(AbstractAssemblerProcessor.java:167)
	at org.jreleaser.assemblers.JlinkAssemblerProcessor.resolveModuleNames(JlinkAssemblerProcessor.java:306)
	at org.jreleaser.assemblers.JlinkAssemblerProcessor.doAssemble(JlinkAssemblerProcessor.java:108)
	at org.jreleaser.assemblers.AbstractJavaAssemblerProcessor.assemble(AbstractJavaAssemblerProcessor.java:82)
	at org.jreleaser.assemblers.JlinkAssemblerProcessor.assemble(JlinkAssemblerProcessor.java:60)
	at org.jreleaser.engine.assemble.DistributionAssembler.assemble(DistributionAssembler.java:62)
	at org.jreleaser.engine.assemble.Assemblers.assemble(Assemblers.java:102)
	... 26 more
Caused by: org.jreleaser.util.command.CommandException: Command execution error. exitValue = 1
	at org.jreleaser.assemblers.AbstractAssemblerProcessor.executeCommandCapturing(AbstractAssemblerProcessor.java:164)
	... 32 more
```

**Comment by aalmiray** [comment]
Found by @loiclefevre
