### ISSUE TITLE
[gradle] Unable to configure files artifact using Gradle

### ISSUE THREAD

**Issue by marceloverdijk** [jreleaser/jreleaser#87]
I was trying to setup jreleaser with Gradle like:

```
plugins {
	id "java"
	id "distribution"
	id "org.jreleaser" version "0.2.0"
}

jreleaser {
	files {
		artifact {
			path = 'path/to/some/file.txt'
		}
	}
}

```

with the `jreleaser` config copied from https://jreleaser.org/guide/latest/configuration/files.html

But this gives:

````
Caused by: groovy.lang.MissingMethodException: No signature of method: org.jreleaser.model.Files.add() is applicable for argument types: (org.jreleaser.model.Artifact) values: [org.jreleaser.model.Artifact@a491a751]
Possible solutions: any(), any(groovy.lang.Closure), wait(), find(), wait(long), is(java.lang.Object)
	at org.jreleaser.gradle.plugin.internal.JReleaserExtensionImpl.toModel(JReleaserExtensionImpl.groovy:157)
	at org.jreleaser.gradle.plugin.internal.JReleaserProjectConfigurer.configure(JReleaserProjectConfigurer.groovy:74)
	at org.jreleaser.gradle.plugin.JReleaserPlugin.configureJReleaser(JReleaserPlugin.groovy:66)
	at org.jreleaser.gradle.plugin.JReleaserPlugin.access$0(JReleaserPlugin.groovy)
	at org.jreleaser.gradle.plugin.JReleaserPlugin$1.execute(JReleaserPlugin.groovy:59)
	at org.jreleaser.gradle.plugin.JReleaserPlugin$1.execute(JReleaserPlugin.groovy)
````

**Comment by aalmiray** [comment]
This is indeed a bug. The static compiler did not catch the fact that the actual method to be invoked should be `files.addArtifact(file.toModel())`
