### ISSUE TITLE
Out of memory when performing a release on Linux

### ISSUE THREAD

**Issue by crschnick** [jreleaser/jreleaser#892]
### Steps to Reproduce

I'm currently trying to publish a release using GitHub actions.
I run a windows, a Linux, and mac runner, which all perform the same build process except that the artifacts uploaded differ.
However, on the Linux runner whatever I do it always runs out of memory when uploading the artifact.
This happens even when I allocate more than ten gigabytes of heap space.

I strongly suspect that this must be some kind of bug as the same GitHub actions runner can perform a GraalVM native build just fine beforehand but then runs out of memory when executing the jreleaser steps.

### Environment Information

- **Operating System**: Ubuntu 20-04
- **JReleaser Version:** 1.1
- **JDK Version:** GraalVM 21.3

        > Task :dist:jreleaserRelease
        [INFO]  JReleaser 1.1.0
        [INFO]    - basedir set to /home/runner/work/xpipe/xpipe/dist
        [INFO]  Loading variables from /home/runner/.jreleaser/config.properties
        [WARN]  Variables source /home/runner/.jreleaser/config.properties does not exist
        [INFO]  Validating configuration
        [INFO]  Project version set to 0.0.1.2
        [INFO]  Release is not snapshot
        [INFO]  Timestamp is 2022-08-14T14:36:34.656881171Z
        [INFO]  HEAD is at 23cb419
        [INFO]  Platform is linux-x86_64
        [INFO]  dry-run set to false
        [INFO]  Generating changelog: build/jreleaser/release/CHANGELOG.md
        [INFO]  Calculating checksums
        [INFO]    [checksum] build/jreleaser/artifacts/xpipe-portable-linux-0.0.1.2.tar.gz.sha256
        [INFO]  Signing files
        [INFO]    [sign] Signing is not enabled. Skipping
        [INFO]  Uploading is not enabled. Skipping
        [INFO]  Releasing to https://github.com/xpipe-io/xpipe-app
        [INFO]  updating release title to 0.0.1.2
        [INFO]  updating release body
        [INFO]   - uploading xpipe-portable-linux-0.0.1.2.tar.gz
        
        
        FAILURE: Build failed with an exception.
        
        * What went wrong:
        Execution failed for task ':dist:jreleaserRelease'.
        > Java heap space
        
        * Try:
        > Run with --info or --debug option to get more log output.
        > Run with --scan to get full insights.
        
        * Exception is:
        org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':dist:jreleaserRelease'.
	        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:147)
	        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
	        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:145)
	        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:133)
	        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
	        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
	        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        > Task :dist:jreleaserRelease FAILED
        
        Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
        
        You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
        
        See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings
        6 actionable tasks: 2 executed, 4 up-to-date
	        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)
	        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:333)
	        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:320)
	        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:313)
	        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:299)
	        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:143)
	        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:227)
	        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:218)
	        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:140)
	        at org.gradle.execution.plan.DefaultPlanExecutor.process(DefaultPlanExecutor.java:72)
	        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.executeWithServices(DefaultTaskExecutionGraph.java:144)
	        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.execute(DefaultTaskExecutionGraph.java:129)
	        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:42)
	        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:51)
	        at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor$ExecuteTasks.call(BuildOperationFiringBuildWorkerExecutor.java:54)
	        at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor$ExecuteTasks.call(BuildOperationFiringBuildWorkerExecutor.java:43)
	        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	        at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor.execute(BuildOperationFiringBuildWorkerExecutor.java:40)
	        at org.gradle.internal.build.DefaultBuildLifecycleController.lambda$executeTasks$7(DefaultBuildLifecycleController.java:165)
	        at org.gradle.internal.model.StateTransitionController.doTransition(StateTransitionController.java:238)
	        at org.gradle.internal.model.StateTransitionController.lambda$tryTransition$8(StateTransitionController.java:174)
	        at org.gradle.internal.work.DefaultSynchronizer.withLock(DefaultSynchronizer.java:44)
	        at org.gradle.internal.model.StateTransitionController.tryTransition(StateTransitionController.java:174)
	        at org.gradle.internal.build.DefaultBuildLifecycleController.executeTasks(DefaultBuildLifecycleController.java:165)
	        at org.gradle.internal.build.DefaultBuildWorkGraphController$DefaultBuildWorkGraph.runWork(DefaultBuildWorkGraphController.java:142)
	        at org.gradle.composite.internal.DefaultBuildController.doBuild(DefaultBuildController.java:231)
	        at org.gradle.internal.Factories$1.create(Factories.java:31)
	        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:270)
	        at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:119)
	        at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:124)
	        at org.gradle.composite.internal.DefaultBuildController.doRun(DefaultBuildController.java:204)
	        at org.gradle.composite.internal.DefaultBuildController.access$000(DefaultBuildController.java:51)
	        at org.gradle.composite.internal.DefaultBuildController$BuildOpRunnable.run(DefaultBuildController.java:264)
	        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        Caused by: java.lang.OutOfMemoryError: Java heap space
	        at org.kohsuke.github.GitHubHttpUrlConnectionClient$HttpURLConnectionResponseInfo.buildRequest(GitHubHttpUrlConnectionClient.java:145)
	        at org.kohsuke.github.GitHubHttpUrlConnectionClient$HttpURLConnectionResponseInfo.setupConnection(GitHubHttpUrlConnectionClient.java:119)
	        at org.kohsuke.github.GitHubHttpUrlConnectionClient.getResponseInfo(GitHubHttpUrlConnectionClient.java:55)
	        at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:387)
	        at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:355)
	        at org.kohsuke.github.Requester.fetch(Requester.java:76)
	        at org.kohsuke.github.GHRelease.uploadAsset(GHRelease.java:249)
	        at org.kohsuke.github.GHRelease.uploadAsset(GHRelease.java:224)
	        at org.jreleaser.sdk.github.Github.uploadAssets(Github.java:156)
	        at org.jreleaser.sdk.github.GithubReleaser.createRelease(GithubReleaser.java:110)
	        at org.jreleaser.model.releaser.spi.AbstractReleaser.release(AbstractReleaser.java:51)
	        at org.jreleaser.engine.release.Releasers.release(Releasers.java:44)
	        at org.jreleaser.workflow.ReleaseWorkflowItem.invoke(ReleaseWorkflowItem.java:34)
	        at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:70)
	        at org.jreleaser.gradle.plugin.tasks.JReleaserReleaseTask.performAction(JReleaserReleaseTask.groovy:86)
	        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
	        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
	        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
	        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
	        at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:242)
	        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)

**Comment by crschnick** [comment]
For the record, the uploaded file is 140MB in size.

**Comment by aalmiray** [comment]
This _might_ be an issue in hub4j. See https://github.com/hub4j/github-api/issues/1454

**Comment by crschnick** [comment]
As this kind of issue seems to be present for a while to come, I would suggest updating the documentation to explicitly mention this limitation and suggest to increase the allocated memory.

I think that quite a few people will run into the same issue otherwise, as uploading files around 100MB using GitHub actions should not be that uncommon.

**Comment by aalmiray** [comment]
Added some advice to the website regarding memory settings. Feel free to close this issue, hopefully hub4j provides a solution we can use in the future.

**Comment by bitwiseman** [comment]
@aalmiray @crschnick  PRs are welcome.
