### ISSUE TITLE
[assemble] Regression in Glob resolution

### ISSUE THREAD

**Issue by aalmiray** [jreleaser/jreleaser#917]
Regression of https://github.com/jreleaser/jreleaser/issues/844

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone https://github.com/aalmiray/q-cli-jlink/ at 291c22f3da6d5d6644553a8cf02bfa7f343093dc
2. `./mvnw -Passemble package`

### Expected Behaviour

3 Jlink images assembled

### Actual Behaviour

An NPE occurs

### Environment Information

- **Operating System**: N/A
- **JReleaser Version:** 1.1.0
- **JDK Version:** 11

```
java.lang.NullPointerException
    at java.base/sun.nio.fs.UnixPath.toUnixPath(UnixPath.java:196)
    at java.base/sun.nio.fs.UnixPath.resolve(UnixPath.java:410)
    at java.base/sun.nio.fs.UnixPath.resolve(UnixPath.java:43)
    at org.jreleaser.model.Glob.relativize(Glob.java:171)
    at org.jreleaser.model.Glob.normalizePattern(Glob.java:143)
    at org.jreleaser.model.Glob.getResolvedArtifactsPattern(Glob.java:93)
    at org.jreleaser.model.Glob.getResolvedArtifacts(Glob.java:87)
    at org.jreleaser.assemblers.AssemblerUtils.copyJars(AssemblerUtils.java:86)
    at org.jreleaser.assemblers.JlinkAssemblerProcessor.doAssemble(JlinkAssemblerProcessor.java:102)
    at org.jreleaser.assemblers.AbstractJavaAssemblerProcessor.assemble(AbstractJavaAssemblerProcessor.java:91)
    at org.jreleaser.assemblers.JlinkAssemblerProcessor.assemble(JlinkAssemblerProcessor.java:60)
    at org.jreleaser.engine.assemble.DistributionAssembler.assemble(DistributionAssembler.java:62)
    at org.jreleaser.engine.assemble.Assemblers.assemble(Assemblers.java:102)
    at org.jreleaser.engine.assemble.Assemblers.assemble(Assemblers.java:92)
    at org.jreleaser.workflow.AssembleWorkflowItem.doInvoke(AssembleWorkflowItem.java:35)
    at org.jreleaser.workflow.AbstractWorkflowItem.lambda$invoke$0(AbstractWorkflowItem.java:38)
    at org.jreleaser.engine.hooks.CommandHookExecutor.execute(CommandHookExecutor.java:52)
    at org.jreleaser.workflow.AbstractWorkflowItem.invoke(AbstractWorkflowItem.java:38)
    at org.jreleaser.workflow.WorkflowImpl.execute(WorkflowImpl.java:70)
    at org.jreleaser.maven.plugin.JReleaserAssembleMojo.execute(JReleaserAssembleMojo.java:78)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
```

**Comment by aalmiray** [comment]
Released in v1.3.0 -> https://github.com/jreleaser/jreleaser/releases/tag/v1.3.0
